/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Cliente;

import Regras.ClienteController;
import Regras.Formatacao;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Clientefechamento;

/**
 *
 * @author wolverine
 */
public class FrmCadastarClienteEntregaPF extends javax.swing.JFrame {
    
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Cliente cliente;
    private Icliente telaConsulta;
    private Clientefechamento clientefechamento;

    /**
     * Creates new form FrmCadastarClienteEntrega
     */
    public FrmCadastarClienteEntregaPF(Cliente cliente, Icliente telaConsulta, int tipoOperacao) {
        this.telaConsulta = telaConsulta;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        try {
            formatarCampos();
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastarClienteEntregaPF.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cliente!=null){
            this.cliente = cliente;
            preencherCampos();
        }else {
            dataCadastrojDateChooser.setDate(new Date());
            dataAtualizacaojDateChooser.setEnabled(false);
            this.cliente = new Cliente();
            this.clientefechamento = new Clientefechamento();
            this.clientefechamento.setLimiteCredito(0.0);
        }
        if (tipoOperacao>0){
            salvarjButton.setEnabled(false);
        }
       
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        nomejTextField.requestFocus();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        rgjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        foneFixojFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        foneCelularjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        situacaojComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        dataAtualizacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    observacaojTextField = new javax.swing.JTextField();
    dataCadastrojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jPanel7 = new javax.swing.JPanel();
salvarjButton = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Nome");

nomejTextField.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        nomejTextFieldActionPerformed(evt);
    }
    });

    jLabel3.setText("Nº CPF");

    cpfjFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cpfjFormattedTextFieldFocusLost(evt);
        }
    });

    jLabel4.setText("Nº RG");

    jLabel5.setText("Fone Fixo");

    jLabel6.setText("Fone Celular");

    jLabel7.setText("E-mail");

    jLabel9.setText("Situação");

    situacaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "ATUALIZAR", "BLOQUEADO", "INATIVO", " " }));

    jLabel10.setText("Data Cadastro");

    dataAtualizacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAtualizacaojDateChooserFocusGained(evt);
        }
    });

    jLabel11.setText("Data Atualização");

    jLabel12.setText("Observação");

    dataCadastrojDateChooser.setEnabled(false);
    dataCadastrojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCadastrojDateChooserFocusGained(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(emailjTextField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel12)
                                    .addGap(341, 341, 341)))))
                    .addGap(14, 14, 14))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(nomejTextField)
                    .addContainerGap())
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(observacaojTextField))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    salvarjButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    salvarjButton.setText("Salvar");
    salvarjButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    salvarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salvarjButtonActionPerformed(evt);
        }
    });
    jPanel7.add(salvarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton3.setText("Fechar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addGap(135, 135, 135)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfjFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldFocusLost
        if (!Formatacao.validaCPF(cpfjFormattedTextField.getText())){
            JOptionPane.showMessageDialog(rootPane, "Número do CNPJ Inválido");
        }
    }//GEN-LAST:event_cpfjFormattedTextFieldFocusLost

    private void dataAtualizacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAtualizacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAtualizacaojDateChooserFocusGained

    private void dataCadastrojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCadastrojDateChooserFocusGained

    }//GEN-LAST:event_dataCadastrojDateChooserFocusGained

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        String data= "11/11/1111";
        if (cliente.getDataAtualizacao()!=null){
            data = Formatacao.ConvercaoDataSql(cliente.getDataAtualizacao());
        }
        if (data.equalsIgnoreCase("1900/01/01")) {
            salvarDados();
            telaConsulta.carregarTodosClientes();
            this.dispose();
        } else {
            String validar = validarTelaDadosIdentificacao();
            if (validar != null) {
                JOptionPane.showMessageDialog(rootPane, validar);
            }else {
                salvarDados();
                telaConsulta.carregarTodosClientes();
                this.dispose();
            }
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private com.toedter.calendar.JDateChooser dataAtualizacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataCadastrojDateChooser;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JFormattedTextField foneCelularjFormattedTextField;
    private javax.swing.JFormattedTextField foneFixojFormattedTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField observacaojTextField;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JComboBox situacaojComboBox;
    // End of variables declaration//GEN-END:variables

    public void formatarCampos() throws ParseException{
        cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        foneFixojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneCelularjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
    }
    
    public void preencherCampos(){
        if (cliente!=null){
            popularTelaDadosIdentificacao();
        }else {
            this.cliente = new Cliente();
        }
    }
    
    public void popularTelaDadosIdentificacao(){
        nomejTextField.setText(cliente.getNome());
        cpfjFormattedTextField.setText(cliente.getDocFederal());
        rgjTextField.setText(cliente.getDocEstadual());
        foneFixojFormattedTextField.setText(cliente.getFoneFixo());
        foneCelularjFormattedTextField.setText(cliente.getFoneCelular());
        emailjTextField.setText(cliente.getEmail());
        situacaojComboBox.setSelectedItem(cliente.getSituacao());
        try {
            dataCadastrojDateChooser.setDate(cliente.getDataCadastro());
        } catch (Exception ex) {
            Logger.getLogger(FrmCadastrarClientePF.class.getName()).log(Level.SEVERE, null, ex);
        }
        dataAtualizacaojDateChooser.setDate(cliente.getDataAtualizacao());
        observacaojTextField.setText(cliente.getObservacoes());
    }
    
    public void salvarDados(){
        popularCliente();
        ClienteController clienteController = new ClienteController();
        cliente = clienteController.salvarCliente(cliente);
        if (this.clientefechamento.getLimiteCredito()!=null){
            popularFechamento();
            clientefechamento = clienteController.salvarFechamento(clientefechamento);
        }
    }
    
    public void popularCliente(){
        if (dataAtualizacaojDateChooser.getDate()!=null){
            cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        }
        if (dataCadastrojDateChooser.getDate()!=null){
            cliente.setDataCadastro(dataCadastrojDateChooser.getDate());
        }
        cliente.setDocEstadual(rgjTextField.getText());
        cliente.setDocFederal(cpfjFormattedTextField.getText());
        cliente.setEmail(emailjTextField.getText());
        cliente.setFoneCelular(foneCelularjFormattedTextField.getText());
        cliente.setFoneFixo(foneFixojFormattedTextField.getText());
        cliente.setNome(nomejTextField.getText());
        cliente.setObservacoes(observacaojTextField.getText());
        cliente.setSituacao(situacaojComboBox.getSelectedItem().toString());
        cliente.setTipo("PF");
        cliente.setOperacao(1);
    }
    
    public String validarTelaDadosIdentificacao(){
        if (nomejTextField.getText()==null){
            return "Razão Social campo obrigatório";
        }
        if (cpfjFormattedTextField.getText()==null){
            return  "CPF campo obrigatório";
        }
        return null;
    }
    
    public void popularFechamento(){
        if (clientefechamento==null){
            clientefechamento = new Clientefechamento();
        }
        clientefechamento.setClienteIdcliente(this.cliente.getIdcliente());
        clientefechamento.setDiaPagamento(0);
        clientefechamento.setFormaPagamento("Loja");
        clientefechamento.setLimiteCredito(0.0);
        clientefechamento.setNotaFiscal("Nao");
        clientefechamento.setTipoFechamento("Diario");
    }

}
