/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastrarClientePJ.java
 *
 * Created on 20/03/2012, 08:19:50
 */
package telas.Cliente;

import Regras.ClienteController;
import Regras.Formatacao;
import Regras.MunicipiosController;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Clienteendereco;
import model.Clientefechamento;
import model.Clientepessoafisica;
import model.Municipios;
import telas.Municipios.FrmConsultaMunicipios;



/**
 *
 * @author Wolverine
 */
public class FrmCadastrarClientePF extends javax.swing.JFrame implements Icliente{
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Cliente cliente;
    private Clientepessoafisica clientepessoafisica;
    private Clienteendereco clienteendereco;
    private Clientefechamento clientefechamento;
    private Icliente telaConsulta;
    private Municipios municipios;
   
    
    
    /** Creates new form FrmCadastrarClientePJ */
    public FrmCadastrarClientePF(Cliente cliente, Icliente telaConsulta, int tipoOperacao) {
        this.telaConsulta = telaConsulta;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        try {
            formatarCampos();
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastrarClientePF.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cliente!=null){
            this.cliente = cliente;
            preencherCampos();
        }else {
            dataCadastrojDateChooser.setDate(new Date());
            dataCosultaCNPJjDateChooser.setDate(new Date());
            dataAtualizacaojDateChooser.setEnabled(false);
            iniciarObjetos();
        }
        if (tipoOperacao>0){
            salvarjButton.setEnabled(false);
        }
       
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        nomejTextField.requestFocus();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        rgjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        foneFixojFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        foneCelularjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        situacaojComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        dataAtualizacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    observacaojTextField = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    tipoLogradourojComboBox = new javax.swing.JComboBox();
    jLabel14 = new javax.swing.JLabel();
    logradourojTextField = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    numerojTextField = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    complementojTextField = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    bairrojTextField = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    cepjFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel19 = new javax.swing.JLabel();
    cidadejTextField = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    dataCadastrojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
dataCosultaCNPJjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    estadojTextField = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    operadorajComboBox = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    jLabel22 = new javax.swing.JLabel();
    localTrabalhojTextField = new javax.swing.JTextField();
    jLabel50 = new javax.swing.JLabel();
    foneComercialjFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel69 = new javax.swing.JLabel();
    tipoLogradouroComercialjComboBox = new javax.swing.JComboBox();
    jLabel70 = new javax.swing.JLabel();
    logradouroComercialjTextField = new javax.swing.JTextField();
    jLabel71 = new javax.swing.JLabel();
    numeroComercialjTextField = new javax.swing.JTextField();
    jLabel72 = new javax.swing.JLabel();
    complementoComercialjTextField = new javax.swing.JTextField();
    jLabel73 = new javax.swing.JLabel();
    bairroComercialjTextField = new javax.swing.JTextField();
    jLabel74 = new javax.swing.JLabel();
    cepComercialjFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel75 = new javax.swing.JLabel();
    cidadeComercialjTextField = new javax.swing.JTextField();
    estadoComercialjComboBox = new javax.swing.JComboBox();
    jLabel76 = new javax.swing.JLabel();
    profissaojFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel77 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jLabel24 = new javax.swing.JLabel();
    nomeConjugeljTextField = new javax.swing.JTextField();
    jLabel26 = new javax.swing.JLabel();
    estadoCiviljComboBox = new javax.swing.JComboBox();
    jLabel30 = new javax.swing.JLabel();
    nomeMaejTextFiel = new javax.swing.JTextField();
    jLabel31 = new javax.swing.JLabel();
    nomePaijTextField = new javax.swing.JTextField();
    foneConjugejFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel21 = new javax.swing.JLabel();
    cpfConjugeFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel23 = new javax.swing.JLabel();
    dataNascimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel25 = new javax.swing.JLabel();
jLabel32 = new javax.swing.JLabel();
nomeReferencia01jTextFiel = new javax.swing.JTextField();
jLabel27 = new javax.swing.JLabel();
foneReferencia01jFormattedTextField = new javax.swing.JFormattedTextField();
nomereferencia02jTextFiel = new javax.swing.JTextField();
jLabel33 = new javax.swing.JLabel();
jLabel28 = new javax.swing.JLabel();
foneConjugejFormattedTextField3 = new javax.swing.JFormattedTextField();
foneReferencia02jFormattedTextField = new javax.swing.JFormattedTextField();
jLabel29 = new javax.swing.JLabel();
jPanel6 = new javax.swing.JPanel();
jLabel34 = new javax.swing.JLabel();
tipoFechamentojComboBox = new javax.swing.JComboBox();
jLabel35 = new javax.swing.JLabel();
diaPagamentojComboBox = new javax.swing.JComboBox();
jLabel44 = new javax.swing.JLabel();
formaPagamentojComboBox = new javax.swing.JComboBox();
jLabel45 = new javax.swing.JLabel();
emitirComprovantejComboBox = new javax.swing.JComboBox();
jLabel46 = new javax.swing.JLabel();
limiteCreditojTextField = new javax.swing.JTextField();
jLabel47 = new javax.swing.JLabel();
clienteDescontojComboBox = new javax.swing.JComboBox();
jPanel7 = new javax.swing.JPanel();
salvarjButton = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Cadastro de Cliente Pessoa Física");

jLabel1.setText("Nome");

jLabel3.setText("Nº CPF");

cpfjFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        cpfjFormattedTextFieldFocusLost(evt);
    }
    });

    jLabel4.setText("Nº RG");

    jLabel5.setText("Fone Fixo");

    jLabel6.setText("Fone Celular");

    jLabel7.setText("E-mail");

    jLabel8.setText("Data Consulta CPF");

    jLabel9.setText("Situação");

    situacaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "ATUALIZAR", "BLOQUEADO", "INATIVO", " " }));

    jLabel10.setText("Data Cadastro");

    dataAtualizacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAtualizacaojDateChooserFocusGained(evt);
        }
    });

    jLabel11.setText("Data Atualização");

    jLabel12.setText("Observação");

    jLabel13.setText("Tipo Logradouro");

    tipoLogradourojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AVENIDA", "BR", "ESTRADA", "RODOVIA", "RUA", "SERVIDÃO" }));

    jLabel14.setText("Logradouro");

    jLabel15.setText("Número");

    jLabel16.setText("Complemento");

    jLabel17.setText("Bairro");

    jLabel18.setText("CEP");

    jLabel19.setText("Cidade");

    cidadejTextField.setEditable(false);

    jLabel20.setText("Estado");

    dataCadastrojDateChooser.setEnabled(false);
    dataCadastrojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCadastrojDateChooserFocusGained(evt);
        }
    });

    dataCosultaCNPJjDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCosultaCNPJjDateChooserFocusGained(evt);
        }
    });

    estadojTextField.setEditable(false);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    operadorajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fixo", "Tim", "Vivo", "Claro", "Oi", "Nextel" }));

    jLabel2.setText("Operadora");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel13))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(cidadejTextField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1))
                                .addComponent(jLabel20)))
                        .addComponent(nomejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(operadorajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(emailjTextField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(288, 288, 288)
                                    .addComponent(jLabel15)
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(complementojTextField))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataCosultaCNPJjDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(819, 819, 819))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(12, 12, 12)
            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dataCosultaCNPJjDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(operadorajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(40, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados de Identificação", jPanel1);

    jLabel22.setText("Local Trabalho");

    jLabel50.setText("Fone Comercial");

    jLabel69.setText("Tipo Logradouro");

    tipoLogradouroComercialjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AVENIDA", "BR", "ESTRADA", "RODOVIA", "RUA", "SERVIDÃO" }));

    jLabel70.setText("Logradouro");

    jLabel71.setText("Número");

    jLabel72.setText("Complemento");

    jLabel73.setText("Bairro");

    jLabel74.setText("CEP");

    jLabel75.setText("Cidade");

    estadoComercialjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SC", "RS", "PR", "SP", "RJ", "ES", "MG", "MT", "MS", "BH" }));

    jLabel76.setText("Estado");

    jLabel77.setText("Profissão");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(localTrabalhojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel77)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(profissaojFormattedTextField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneComercialjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel50)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel73)
                                .addComponent(bairroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel74)
                                .addComponent(cepComercialjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cidadeComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel75))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel76)
                                .addComponent(estadoComercialjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(845, 845, 845))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel69)
                        .addComponent(tipoLogradouroComercialjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel70)
                        .addComponent(logradouroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel71)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel72))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(numeroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(complementoComercialjTextField)))
                    .addGap(843, 843, 843))))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(localTrabalhojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profissaojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel50)
                        .addComponent(jLabel77))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foneComercialjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoLogradouroComercialjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logradouroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel71)
                        .addComponent(jLabel72))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numeroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(complementoComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel73)
                .addComponent(jLabel74)
                .addComponent(jLabel75)
                .addComponent(jLabel76))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bairroComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cepComercialjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadeComercialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(estadoComercialjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(148, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Comerciais", jPanel5);

    jLabel24.setText("Nome do Conjuge");

    jLabel26.setText("Estado Civil");

    estadoCiviljComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado", "Divorciado", "Separado", "Solteiro", "União Estavel" }));

    jLabel30.setText("Nome da Mãe");

    jLabel31.setText("Nome Pai");

    jLabel21.setText("Fone Conjuge");

    cpfConjugeFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cpfConjugeFormattedTextFieldFocusLost(evt);
        }
    });

    jLabel23.setText("Nº CPF");

    jLabel25.setText("Data Nascimento");

    jLabel32.setText("Referencia Comercial 01");

    jLabel27.setText("Fone Referencia 01");

    jLabel33.setText("Referencia Comercial 02");

    jLabel28.setText("Fone Referencia 01");

    jLabel29.setText("Fone Referencia 02");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(nomeReferencia01jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(foneReferencia01jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)
                                .addComponent(foneReferencia02jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addComponent(nomeMaejTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(321, 321, 321))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(nomePaijTextField)
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25)
                                .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(estadoCiviljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(nomeConjugeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(cpfConjugeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(foneConjugejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(878, 878, 878))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addComponent(nomereferencia02jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(foneConjugejFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel24)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estadoCiviljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeConjugeljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneConjugejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cpfConjugeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel30)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeMaejTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomePaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel31)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataNascimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel32)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nomeReferencia01jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foneReferencia01jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nomereferencia02jTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foneConjugejFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel29)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(foneReferencia02jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(102, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Complementares", jPanel4);

    jLabel34.setText("Tipo Fechamento");

    tipoFechamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensal", "Decendio", "Quinzenal", "Semanal" }));

    jLabel35.setText("Dia Pagamento");

    diaPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

    jLabel44.setText("Forma de Pagamento");

    formaPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Cheque", "Cobrança", "Depósito", "Folha", "Loja", " " }));

    jLabel45.setText("Emitir NF-e");

    emitirComprovantejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

    jLabel46.setText("Limite de Crédito");

    limiteCreditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    limiteCreditojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            limiteCreditojTextFieldKeyReleased(evt);
        }
    });

    jLabel47.setText("Cliente com Desconto");

    clienteDescontojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel34)
                .addComponent(tipoFechamentojComboBox, 0, 202, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addComponent(emitirComprovantejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel46)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel47)
                        .addComponent(clienteDescontojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(limiteCreditojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(diaPagamentojComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE))
                    .addGap(72, 72, 72)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel44)
                        .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel34)
                .addComponent(jLabel35)
                .addComponent(jLabel44))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoFechamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(diaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel45)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(emitirComprovantejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel46)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(limiteCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel47)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(clienteDescontojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(185, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Fechamento", jPanel6);

    jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    salvarjButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    salvarjButton.setText("Salvar");
    salvarjButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    salvarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salvarjButtonActionPerformed(evt);
        }
    });
    jPanel7.add(salvarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton3.setText("Fechar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataAtualizacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAtualizacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAtualizacaojDateChooserFocusGained

    private void dataCadastrojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCadastrojDateChooserFocusGained
        
    }//GEN-LAST:event_dataCadastrojDateChooserFocusGained

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        String data= "11/11/1111";
        if (cliente.getDataAtualizacao()!=null){
            data = Formatacao.ConvercaoDataSql(cliente.getDataAtualizacao());
        }
        if (data.equalsIgnoreCase("1900/01/01")) {
            salvarDados();
            telaConsulta.carregarTodosClientes();
            this.dispose();
        } else {
            String validar = validarTelaDadosIdentificacao();
            if (validar != null) {
                JOptionPane.showMessageDialog(rootPane, validar);
            } else {
                validar = validarDadosComplementares();
                if (validar != null) {
                    JOptionPane.showMessageDialog(rootPane, validar);
                } else {
                    salvarDados();
                    telaConsulta.carregarTodosClientes();
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cpfjFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldFocusLost
        if (!Formatacao.validaCPF(cpfjFormattedTextField.getText())){
            JOptionPane.showMessageDialog(rootPane, "Número do CNPJ Inválido");
        }
    }//GEN-LAST:event_cpfjFormattedTextFieldFocusLost

    private void limiteCreditojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limiteCreditojTextFieldKeyReleased
        limiteCreditojTextField.setText(Formatacao.decinalValorMonetario(limiteCreditojTextField.getText()));
    }//GEN-LAST:event_limiteCreditojTextFieldKeyReleased

    private void cpfConjugeFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfConjugeFormattedTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfConjugeFormattedTextFieldFocusLost

    private void dataCosultaCNPJjDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCosultaCNPJjDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCosultaCNPJjDateChooserFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmConsultaMunicipios(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroComercialjTextField;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepComercialjFormattedTextField;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadeComercialjTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JComboBox clienteDescontojComboBox;
    private javax.swing.JTextField complementoComercialjTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JFormattedTextField cpfConjugeFormattedTextField;
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private com.toedter.calendar.JDateChooser dataAtualizacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataCadastrojDateChooser;
    private com.toedter.calendar.JDateChooser dataCosultaCNPJjDateChooser;
    private com.toedter.calendar.JDateChooser dataNascimentojDateChooser;
    private javax.swing.JComboBox diaPagamentojComboBox;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JComboBox emitirComprovantejComboBox;
    private javax.swing.JComboBox estadoCiviljComboBox;
    private javax.swing.JComboBox estadoComercialjComboBox;
    private javax.swing.JTextField estadojTextField;
    private javax.swing.JFormattedTextField foneCelularjFormattedTextField;
    private javax.swing.JFormattedTextField foneComercialjFormattedTextField;
    private javax.swing.JFormattedTextField foneConjugejFormattedTextField;
    private javax.swing.JFormattedTextField foneConjugejFormattedTextField3;
    private javax.swing.JFormattedTextField foneFixojFormattedTextField;
    private javax.swing.JFormattedTextField foneReferencia01jFormattedTextField;
    private javax.swing.JFormattedTextField foneReferencia02jFormattedTextField;
    private javax.swing.JComboBox formaPagamentojComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField limiteCreditojTextField;
    private javax.swing.JTextField localTrabalhojTextField;
    private javax.swing.JTextField logradouroComercialjTextField;
    private javax.swing.JTextField logradourojTextField;
    private javax.swing.JTextField nomeConjugeljTextField;
    private javax.swing.JTextField nomeMaejTextFiel;
    private javax.swing.JTextField nomePaijTextField;
    private javax.swing.JTextField nomeReferencia01jTextFiel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField nomereferencia02jTextFiel;
    private javax.swing.JTextField numeroComercialjTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField observacaojTextField;
    private javax.swing.JComboBox operadorajComboBox;
    private javax.swing.JFormattedTextField profissaojFormattedTextField;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JComboBox situacaojComboBox;
    private javax.swing.JComboBox tipoFechamentojComboBox;
    private javax.swing.JComboBox tipoLogradouroComercialjComboBox;
    private javax.swing.JComboBox tipoLogradourojComboBox;
    // End of variables declaration//GEN-END:variables

    public void preencherCampos(){
        popularObjetos();
        if (this.clienteendereco!=null){
            popularTelaEndereco();
        }else {
            this.clienteendereco = new Clienteendereco();
        }
        if (this.clientefechamento!=null){
            popularTelaFechamento();
        }else {
            this.clientefechamento = new Clientefechamento();
        }
        if (this.clientepessoafisica!=null){
            popularTelaDadosComplementares();
            popularTelaDadosComercial();
        }else {
            this.clientepessoafisica = new Clientepessoafisica();
        }
        if (cliente!=null){
            popularTelaDadosIdentificacao();
        }else {
            this.cliente = new Cliente();
        }
    }
    
    public void popularTelaDadosIdentificacao(){
        nomejTextField.setText(cliente.getNome());
        cpfjFormattedTextField.setText(cliente.getDocFederal());
        rgjTextField.setText(cliente.getDocEstadual());
        foneFixojFormattedTextField.setText(cliente.getFoneFixo());
        foneCelularjFormattedTextField.setText(cliente.getFoneCelular());
        operadorajComboBox.setSelectedItem(cliente.getOperadora());
        emailjTextField.setText(cliente.getEmail());
        dataCosultaCNPJjDateChooser.setDate(cliente.getDataConsultacpf());
        situacaojComboBox.setSelectedItem(cliente.getSituacao());
        try {
            dataCadastrojDateChooser.setDate(cliente.getDataCadastro());
        } catch (Exception ex) {
            Logger.getLogger(FrmCadastrarClientePF.class.getName()).log(Level.SEVERE, null, ex);
        }
        dataAtualizacaojDateChooser.setDate(cliente.getDataAtualizacao());
        observacaojTextField.setText(cliente.getObservacoes());
    }
    
    public void popularTelaDadosComplementares(){
        estadoCiviljComboBox.setSelectedItem(clientepessoafisica.getEstadoCivil());
        nomeConjugeljTextField.setText(clientepessoafisica.getNomeConjuge());
        cpfConjugeFormattedTextField.setText(clientepessoafisica.getCpfConjuge());
        foneConjugejFormattedTextField.setText(clientepessoafisica.getFoneConjuge());
        nomeMaejTextFiel.setText(clientepessoafisica.getNomeMae());
        nomePaijTextField.setText(clientepessoafisica.getNomePai());
        dataNascimentojDateChooser.setDate(clientepessoafisica.getDataNascimento());
        nomeReferencia01jTextFiel.setText(clientepessoafisica.getRefNome01());
        foneReferencia01jFormattedTextField.setText(clientepessoafisica.getReffone01());
        nomereferencia02jTextFiel.setText(clientepessoafisica.getRefNome02());
        foneReferencia02jFormattedTextField.setText(clientepessoafisica.getRefFone02());
    }
    
    public void popularTelaDadosComercial(){
        String tipoLogradouro = clientepessoafisica.getTipoLogradouro();
        tipoLogradouroComercialjComboBox.setSelectedItem(tipoLogradouro);
        logradouroComercialjTextField.setText(clientepessoafisica.getLogradouro());
        numeroComercialjTextField.setText(clientepessoafisica.getNumero());
        complementoComercialjTextField.setText(clientepessoafisica.getComplemento());
        bairroComercialjTextField.setText(clientepessoafisica.getBairro());
        cepComercialjFormattedTextField.setText(clientepessoafisica.getCep());
        cidadeComercialjTextField.setText(clientepessoafisica.getCidade());
        estadoComercialjComboBox.setSelectedItem(clientepessoafisica.getEstado());
        localTrabalhojTextField.setText(clientepessoafisica.getLocalTrabalho());
        profissaojFormattedTextField.setText(clientepessoafisica.getProfissao());
        foneComercialjFormattedTextField.setText(clientepessoafisica.getTelefoneComercial());
    }
            
    
    public void popularTelaFechamento(){
        tipoFechamentojComboBox.setSelectedItem(clientefechamento.getTipoFechamento());
        String diaPagto = String.valueOf(clientefechamento.getDiaPagamento());
        if (clientefechamento.getDiaPagamento()<10){
            diaPagto = "0" + diaPagto;
        }
        diaPagamentojComboBox.setSelectedItem(diaPagto);
        formaPagamentojComboBox.setSelectedItem(clientefechamento.getFormaPagamento());
        emitirComprovantejComboBox.setSelectedItem(clientefechamento.getNotaFiscal());
        limiteCreditojTextField.setText(Formatacao.foramtarDoubleString(clientefechamento.getLimiteCredito()));
        clienteDescontojComboBox.setSelectedItem(cliente.getPossuiDesconto());
    }
    
    public void popularTelaEndereco(){
        String tipoLogradouro = clienteendereco.getTipoLogradouro();
        tipoLogradourojComboBox.setSelectedItem(tipoLogradouro);
        logradourojTextField.setText(clienteendereco.getLogradouro());
        numerojTextField.setText(clienteendereco.getNumero());
        complementojTextField.setText(clienteendereco.getComplemento());
        bairrojTextField.setText(clienteendereco.getBairro());
        cepjFormattedTextField.setText(clienteendereco.getCep());
        if (clienteendereco.getMunicipios() == 0) {
            cidadejTextField.setText(clienteendereco.getCidade());
            estadojTextField.setText(clienteendereco.getEstado());
        } else {
            MunicipiosController municipiosController = new MunicipiosController();
            this.municipios = municipiosController.getMunicipio(clienteendereco.getMunicipios());
            if (municipios != null) {
                cidadejTextField.setText(municipios.getNomeMunicipio());
                estadojTextField.setText(municipios.getEstado());
            }
        }
    }
    
    public void popularObjetos(){
        ClienteController clienteController = new ClienteController();
        
        clientepessoafisica = clienteController.consultarClientePessoaFisica(cliente.getIdcliente());
        
        clienteendereco = clienteController.consultarClienteEndereco(cliente.getIdcliente());
        
        clientefechamento = clienteController.consultarClienteFechamento(cliente.getIdcliente());
    }
    
    public void iniciarObjetos(){
        cliente= new Cliente();
        clientepessoafisica = new Clientepessoafisica();
        clienteendereco = new Clienteendereco();
        clientefechamento = new Clientefechamento();
    }
    
    
    //Ppopular objetos
    
    public void popularCliente(){
        if (dataAtualizacaojDateChooser.getDate()!=null){
            cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        }
        if (dataCadastrojDateChooser.getDate()!=null){
            cliente.setDataCadastro(dataCadastrojDateChooser.getDate());
        }
        if (dataCosultaCNPJjDateChooser.getDate()!=null){
            cliente.setDataConsultacpf(dataCosultaCNPJjDateChooser.getDate());
        }
        cliente.setDocEstadual(rgjTextField.getText());
        cliente.setDocFederal(cpfjFormattedTextField.getText());
        cliente.setEmail(emailjTextField.getText());
        cliente.setFoneCelular(foneCelularjFormattedTextField.getText());
        cliente.setOperadora(operadorajComboBox.getSelectedItem().toString());
        cliente.setFoneFixo(foneFixojFormattedTextField.getText());
        cliente.setNome(nomejTextField.getText());
        cliente.setObservacoes(observacaojTextField.getText());
        cliente.setSituacao(situacaojComboBox.getSelectedItem().toString());
        cliente.setTipo("PF");
        cliente.setOperacao(10);
        cliente.setPossuiDesconto(clienteDescontojComboBox.getSelectedItem().toString());
    }
    
    public void popularEndereco(){
        if (clienteendereco==null){
            clienteendereco = new Clienteendereco();
        }
        clienteendereco.setBairro(bairrojTextField.getText());
        clienteendereco.setCep(cepjFormattedTextField.getText());
        clienteendereco.setClienteIdcliente(this.cliente.getIdcliente());
        clienteendereco.setComplemento(complementojTextField.getText());
        clienteendereco.setEstado(estadojTextField.getText());
        clienteendereco.setCidade(cidadejTextField.getText());
        clienteendereco.setLogradouro(logradourojTextField.getText());
        clienteendereco.setNumero(numerojTextField.getText());
        if (tipoLogradourojComboBox.getSelectedItem()!=null){
            clienteendereco.setTipoLogradouro(tipoLogradourojComboBox.getSelectedItem().toString());
        }clienteendereco.setTipoLogradouro("RUA");
        if (this.municipios!=null){
            clienteendereco.setMunicipios(this.municipios.getIdmunicipios());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro Código Municipio");
        }
        
    }
    
    public void popularFechamento(){
        if (clientefechamento==null){
            clientefechamento = new Clientefechamento();
        }
        clientefechamento.setClienteIdcliente(this.cliente.getIdcliente());
        clientefechamento.setDiaPagamento(Integer.parseInt(diaPagamentojComboBox.getSelectedItem().toString()));
        clientefechamento.setFormaPagamento(formaPagamentojComboBox.getSelectedItem().toString());
        if (limiteCreditojTextField.getText().length()>0){
            clientefechamento.setLimiteCredito(Formatacao.ConvercaoMonetariaDouble(limiteCreditojTextField.getText()));
        }else clientefechamento.setLimiteCredito(0.0);
        clientefechamento.setNotaFiscal(emitirComprovantejComboBox.getSelectedItem().toString());
        clientefechamento.setTipoFechamento(tipoFechamentojComboBox.getSelectedItem().toString());
    }
    
    
    
    public void popularPessoaFisica(){
        if (clientepessoafisica==null){
            clientepessoafisica = new Clientepessoafisica();
        }
        clientepessoafisica.setLocalTrabalho(localTrabalhojTextField.getText());
        clientepessoafisica.setProfissao(profissaojFormattedTextField.getText());
        clientepessoafisica.setTelefoneComercial(foneComercialjFormattedTextField.getText());
        clientepessoafisica.setTipoLogradouro(tipoLogradouroComercialjComboBox.getSelectedItem().toString());
        clientepessoafisica.setLogradouro(logradouroComercialjTextField.getText());
        clientepessoafisica.setNumero(numeroComercialjTextField.getText());
        clientepessoafisica.setComplemento(complementoComercialjTextField.getText());
        clientepessoafisica.setBairro(bairroComercialjTextField.getText());
        clientepessoafisica.setCep(cepComercialjFormattedTextField.getText());
        clientepessoafisica.setCidade(cidadeComercialjTextField.getText());
        clientepessoafisica.setEstado(estadoComercialjComboBox.getSelectedItem().toString());
        clientepessoafisica.setEstadoCivil(estadoCiviljComboBox.getSelectedItem().toString());
        clientepessoafisica.setNomeConjuge(nomeConjugeljTextField.getText());
        clientepessoafisica.setCpfConjuge(cpfConjugeFormattedTextField.getText());
        clientepessoafisica.setFoneConjuge(foneConjugejFormattedTextField.getText());
        clientepessoafisica.setNomeMae(nomeMaejTextFiel.getText());
        clientepessoafisica.setNomePai(nomePaijTextField.getText());
        if (dataNascimentojDateChooser.getDate()!=null){
            clientepessoafisica.setDataNascimento(dataNascimentojDateChooser.getDate());
        }
        clientepessoafisica.setRefNome01(nomeReferencia01jTextFiel.getText());
        clientepessoafisica.setReffone01(foneReferencia01jFormattedTextField.getText());
        clientepessoafisica.setRefNome02(nomereferencia02jTextFiel.getText());
        clientepessoafisica.setRefFone02(foneReferencia02jFormattedTextField.getText());
        clientepessoafisica.setClienteIdcliente(this.cliente.getIdcliente());
    }
    
    // Validar Campos
    
    public String validarTelaDadosIdentificacao(){
        if (this.municipios==null){
            return "Municipio e Estado campo obrigatório";
        }

        if (nomejTextField.getText()==null){
            return "Razão Social campo obrigatório";
        }
        if (cpfjFormattedTextField.getText()==null){
            return  "CNPJ campo obrigatório";
        }
        if (logradourojTextField.getText()==null){
            return "Logradouro campo obrigatório";
        }
        if (numerojTextField.getText()==null){
            return  "Número campo obrigatório";
        }
        if (bairrojTextField.getText()==null){
            return "Bairro campo obrigatório";
        }
        if (cepjFormattedTextField.getText()==null){
            return "CEP campo obrigatório";
        }
        if (cidadejTextField.getText()==null){
            return "Cidade campo obrigatório";
        }
        return null;
    }
    
    
    public String validarDadosComplementares(){
        if ((estadoCiviljComboBox.getSelectedItem().toString().equalsIgnoreCase("Casado"))
                || (estadoCiviljComboBox.getSelectedItem().toString().equalsIgnoreCase("União Estavel"))) {

            if (nomeConjugeljTextField.getText() == null) {
                return "Nome Conjuge campo obrigatório";
            }
            if (foneConjugejFormattedTextField.getText() == null) {
                return "Fone Conjuge campo obrigatório";
            }
            if (cpfConjugeFormattedTextField.getText() == null) {
                return "CPF  Conjuge campo obrigatório";
            }
        }
        if (dataNascimentojDateChooser.getDate()==null){
            return "Data Nascimento campo obrigatório";
        }
        if (nomeMaejTextFiel.getText()==null){
            return "Nome da Mãe campo obrigatório";
        }
        if (nomePaijTextField.getText()==null){
            return "Nome do Pai campo obrigatório";
        }
        if (nomeReferencia01jTextFiel.getText()==null){
            return "Nome da Referência 01 campo obrigatório";
        }
        if (foneReferencia01jFormattedTextField.getText()==null){
            return "Fone Referência 01 campo obrigatório";
        }
        if (nomereferencia02jTextFiel.getText()==null){
            return "Nome da Referência 02 campo obrigatório";
        }
        if (foneReferencia02jFormattedTextField.getText()==null){
            return "Fone Referência 02 campo obrigatório";
        }
        return null;
    }
    
    
    public void salvarDados(){
        popularCliente();
        ClienteController clienteController = new ClienteController();
        cliente = clienteController.salvarCliente(cliente);
        
        popularEndereco();
        clienteendereco = clienteController.salvarEndereco(clienteendereco);
        
        popularFechamento();
        clientefechamento = clienteController.salvarFechamento(clientefechamento);
        
        
        
        
        if (clientepessoafisica==null){
            clientepessoafisica = new Clientepessoafisica();
        }
       

        
        popularPessoaFisica();
        clientepessoafisica= clienteController.salvarPessoaFisica(clientepessoafisica);
        
    }
    
    
    public void formatarCampos() throws ParseException{
        cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        foneFixojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneCelularjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        cpfConjugeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        foneComercialjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneConjugejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        cepComercialjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        foneReferencia02jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneReferencia01jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
    }
    
    
    public void carregarTodosClientes() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setMunicipio(Municipios municipios) {
        if (municipios!=null){
            this.municipios = municipios;
            cidadejTextField.setText(this.municipios.getNomeMunicipio());
            estadojTextField.setText(this.municipios.getEstado());
        }
    }

    public void resetMunicipio() {
        this.municipios=null;
        cidadejTextField.setText("");
        estadojTextField.setText("");
    }
}
