/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastrarClientePJ.java
 *
 * Created on 20/03/2012, 08:19:50
 */
package telas.Cliente;

import Regras.ClienteController;
import Regras.Formatacao;
import Regras.MunicipiosController;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Clientecondominio;
import model.Clienteendereco;
import model.Clienteenderecoentrega;
import model.Clientefechamento;
import model.Municipios;
import telas.Municipios.FrmConsultaMunicipios;



/**
 *
 * @author Wolverine
 */
public class FrmCadastrarClienteCondominio extends javax.swing.JFrame implements Icliente{
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Cliente cliente;
    private Clientecondominio clientecondominio;
    private Clienteendereco clienteendereco;
    private Clientefechamento clientefechamento;
    private Icliente telaConsulta;
    private Municipios municipios;

    
    /** Creates new form FrmCadastrarClientePJ */
    public FrmCadastrarClienteCondominio(Cliente cliente, Icliente telaConsulta, int tipoOperacao) {
        this.telaConsulta = telaConsulta;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.telaConsulta = telaConsulta;
        initComponents();
        try {
            formatarCampos();
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastrarClienteCondominio.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cliente!=null){
            this.cliente = cliente;
            preencherCampos();
        }else {
            dataCadastrojDateChooser.setDate(new Date());
            dataCosultaCNPJjDateChooser.setDate(new Date());
            dataAtualizacaojDateChooser.setEnabled(false);
            iniciarObjetos();
        }
        
        if (tipoOperacao>0){
            salvarjButton.setEnabled(false);
        }
       
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        razaoSocialjTextField.requestFocus();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        razaoSocialjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnpjjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        iejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        foneFixojFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        foneCelularjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataCosultaCNPJjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel9 = new javax.swing.JLabel();
    situacaojComboBox = new javax.swing.JComboBox();
    jLabel10 = new javax.swing.JLabel();
    dataAtualizacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel11 = new javax.swing.JLabel();
jLabel12 = new javax.swing.JLabel();
observacaojTextField = new javax.swing.JTextField();
jLabel13 = new javax.swing.JLabel();
tipoLogradourojComboBox = new javax.swing.JComboBox();
jLabel14 = new javax.swing.JLabel();
logradourojTextField = new javax.swing.JTextField();
jLabel15 = new javax.swing.JLabel();
numerojTextField = new javax.swing.JTextField();
jLabel16 = new javax.swing.JLabel();
complementojTextField = new javax.swing.JTextField();
jLabel17 = new javax.swing.JLabel();
bairrojTextField = new javax.swing.JTextField();
jLabel18 = new javax.swing.JLabel();
cepjFormattedTextField = new javax.swing.JFormattedTextField();
jLabel19 = new javax.swing.JLabel();
cidadejTextField = new javax.swing.JTextField();
jLabel20 = new javax.swing.JLabel();
dataCadastrojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    estadojTextField = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel24 = new javax.swing.JLabel();
    nomeSindicoljTextField = new javax.swing.JTextField();
    jLabel26 = new javax.swing.JLabel();
    dataAberturaContajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel36 = new javax.swing.JLabel();
tipoLogradouroSindicojComboBox = new javax.swing.JComboBox();
jLabel37 = new javax.swing.JLabel();
logradouroSindicojTextField = new javax.swing.JTextField();
jLabel38 = new javax.swing.JLabel();
numeroSindicojTextField = new javax.swing.JTextField();
jLabel39 = new javax.swing.JLabel();
complementoSindicojTextField = new javax.swing.JTextField();
jLabel40 = new javax.swing.JLabel();
bairroSindicojTextField = new javax.swing.JTextField();
jLabel41 = new javax.swing.JLabel();
cepSindicojFormattedTextField1 = new javax.swing.JFormattedTextField();
jLabel42 = new javax.swing.JLabel();
cidadeSindicojTextField = new javax.swing.JTextField();
estadoSindicojComboBox = new javax.swing.JComboBox();
jLabel43 = new javax.swing.JLabel();
jLabel27 = new javax.swing.JLabel();
foneContatojFormattedTextField = new javax.swing.JFormattedTextField();
jLabel28 = new javax.swing.JLabel();
jLabel32 = new javax.swing.JLabel();
foneSindicojFormattedTextField = new javax.swing.JFormattedTextField();
jLabel33 = new javax.swing.JLabel();
emailSindicojTextField = new javax.swing.JTextField();
nomeContatojTextField = new javax.swing.JTextField();
jLabel47 = new javax.swing.JLabel();
cpfSindicojFormattedTextField = new javax.swing.JFormattedTextField();
jLabel29 = new javax.swing.JLabel();
dataPossejDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel48 = new javax.swing.JLabel();
    dataFimMandatojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jPanel6 = new javax.swing.JPanel();
jLabel34 = new javax.swing.JLabel();
tipoFechamentojComboBox = new javax.swing.JComboBox();
jLabel45 = new javax.swing.JLabel();
emitirComprovantejComboBox = new javax.swing.JComboBox();
limiteCreditojTextField = new javax.swing.JTextField();
jLabel46 = new javax.swing.JLabel();
diaPagamentojComboBox = new javax.swing.JComboBox();
jLabel35 = new javax.swing.JLabel();
jLabel44 = new javax.swing.JLabel();
formaPagamentojComboBox = new javax.swing.JComboBox();
jLabel49 = new javax.swing.JLabel();
clienteDescontojComboBox = new javax.swing.JComboBox();
jPanel7 = new javax.swing.JPanel();
salvarjButton = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Cadastro de Cliente Condominio");

jLabel1.setText("Razão Social");

jLabel3.setText("Nº CNPJ");

cnpjjFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        cnpjjFormattedTextFieldFocusLost(evt);
    }
    });

    jLabel4.setText("Nº Inscrição Estadual");

    jLabel5.setText("Fone Fixo");

    jLabel6.setText("Fone Celular");

    jLabel7.setText("E-mail");

    jLabel8.setText("Data Consulta CNPJ");

    jLabel9.setText("Situação");

    situacaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "ATUALIZAR", "BLOQUEADO", "INATIVO", " " }));

    jLabel10.setText("Data Cadastro");

    dataAtualizacaojDateChooser.setEnabled(false);
    dataAtualizacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAtualizacaojDateChooserFocusGained(evt);
        }
    });

    jLabel11.setText("Data Atualização");

    jLabel12.setText("Observação");

    jLabel13.setText("Tipo Logradouro");

    tipoLogradourojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avenida", "BR", "Estrada", "Rodovia", "Rua", "Servidão" }));

    jLabel14.setText("Logradouro");

    jLabel15.setText("Número");

    jLabel16.setText("Complemento");

    jLabel17.setText("Bairro");

    jLabel18.setText("CEP");

    jLabel19.setText("Cidade");

    cidadejTextField.setEditable(false);

    jLabel20.setText("Estado");

    dataCadastrojDateChooser.setEnabled(false);
    dataCadastrojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCadastrojDateChooserFocusGained(evt);
        }
    });

    estadojTextField.setEditable(false);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGap(1555, 1555, 1555))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cidadejTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addComponent(jLabel20)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cnpjjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(iejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emailjTextField))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(288, 288, 288)
                                        .addComponent(jLabel15)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(complementojTextField))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(dataCosultaCNPJjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(observacaojTextField))))
                            .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(845, 845, 845)))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cnpjjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(iejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(jLabel18)
                .addComponent(jLabel19)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dataCosultaCNPJjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(situacaojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataCadastrojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(dataAtualizacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(41, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados de Identificação", jPanel1);

    jLabel24.setText("Nome do Sindico");

    jLabel26.setText("Nome Contato");

    dataAberturaContajDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAberturaContajDateChooserFocusGained(evt);
        }
    });

    jLabel36.setText("Tipo Logradouro");

    tipoLogradouroSindicojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avenida", "BR", "Estrada", "Rodovia", "Rua", "Servidão" }));

    jLabel37.setText("Logradouro");

    jLabel38.setText("Número");

    jLabel39.setText("Complemento");

    jLabel40.setText("Bairro");

    jLabel41.setText("CEP");

    jLabel42.setText("Cidade");

    estadoSindicojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SC", "RS", "PR", "SP", "RJ", "ES", "MG", "MT", "MS", "BH" }));

    jLabel43.setText("Estado");

    jLabel27.setText("Fone Contato");

    jLabel28.setText("Data Abertura Conta");

    jLabel32.setText("Fone Sindico");

    jLabel33.setText("E-mail Sindico");

    jLabel47.setText("CPF Sindico");

    jLabel29.setText("Data Posse");

    dataPossejDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataPossejDateChooserFocusGained(evt);
        }
    });

    jLabel48.setText("Data Fim Mandato");

    dataFimMandatojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataFimMandatojDateChooserFocusGained(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addComponent(dataPossejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel48)
                        .addComponent(dataFimMandatojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(dataAberturaContajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33))
                    .addGap(855, 855, 855))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel24)
                                .addComponent(nomeSindicoljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foneSindicojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32)))
                        .addComponent(nomeContatojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel47)
                        .addComponent(cpfSindicojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneContatojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addGap(855, 855, 855))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel40)
                                .addComponent(bairroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel41)
                                .addComponent(cepSindicojFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cidadeSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel43)
                                .addComponent(estadoSindicojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(tipoLogradouroSindicojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addGap(288, 288, 288)
                                    .addComponent(jLabel38)
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel39))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(logradouroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numeroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(complementoSindicojTextField))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(845, 845, 845))))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel26)
                .addComponent(jLabel27))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(foneContatojFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomeContatojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel24)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nomeSindicoljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(jLabel32))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfSindicojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foneSindicojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataPossejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel48)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataFimMandatojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataAberturaContajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel36)
                .addComponent(jLabel37)
                .addComponent(jLabel38)
                .addComponent(jLabel39))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoLogradouroSindicojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradouroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numeroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(complementoSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel40)
                .addComponent(jLabel41)
                .addComponent(jLabel42)
                .addComponent(jLabel43))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bairroSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cepSindicojFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidadeSindicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(estadoSindicojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(46, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Complementares", jPanel4);

    jLabel34.setText("Tipo Fechamento");

    tipoFechamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensal", "Decendio", "Quinzenal", "Semanal" }));

    jLabel45.setText("Emitir Comprovatne");

    emitirComprovantejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

    limiteCreditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    limiteCreditojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            limiteCreditojTextFieldKeyReleased(evt);
        }
    });

    jLabel46.setText("Limite de Crédito");

    diaPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

    jLabel35.setText("Dia Pagamento");

    jLabel44.setText("Forma de Pagamento");

    formaPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Cheque", "Cobrança", "Depósito", "Folha", "Loja", " " }));

    jLabel49.setText("Cliente com Desconto");

    clienteDescontojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAO", "SIM" }));

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel34)
                .addComponent(tipoFechamentojComboBox, 0, 202, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addComponent(emitirComprovantejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel46)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel49)
                        .addComponent(clienteDescontojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(limiteCreditojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(diaPagamentojComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE))
                    .addGap(72, 72, 72)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel44)
                        .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel34)
                .addComponent(jLabel35)
                .addComponent(jLabel44))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoFechamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(diaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel45)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(emitirComprovantejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel46)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(limiteCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel49)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(clienteDescontojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(194, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Dados Fechamento", jPanel6);

    jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    salvarjButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    salvarjButton.setText("Salvar");
    salvarjButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    salvarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salvarjButtonActionPerformed(evt);
        }
    });
    jPanel7.add(salvarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton3.setText("Fechar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataAtualizacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAtualizacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAtualizacaojDateChooserFocusGained

    private void dataAberturaContajDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAberturaContajDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAberturaContajDateChooserFocusGained

    private void dataCadastrojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCadastrojDateChooserFocusGained
        
    }//GEN-LAST:event_dataCadastrojDateChooserFocusGained

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        String data= "11/11/1111";
        if (cliente.getDataAtualizacao()!=null){
            data = Formatacao.ConvercaoDataSql(cliente.getDataAtualizacao());
        }
        if (data.equalsIgnoreCase("1900/01/01")) {
            salvarDados();
            telaConsulta.carregarTodosClientes();
            this.dispose();
        } else {
            String validar = validarTelaDadosIdentificacao();
            if (validar != null) {
                JOptionPane.showMessageDialog(rootPane, validar);
            } else {
                validar = validarDadosComplementares();
                if (validar != null) {
                    JOptionPane.showMessageDialog(rootPane, validar);
                } else {
                    salvarDados();
                    telaConsulta.carregarTodosClientes();
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cnpjjFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpjjFormattedTextFieldFocusLost
        if (!Formatacao.ValidaCNPJ(cnpjjFormattedTextField.getText())){
            JOptionPane.showMessageDialog(rootPane, "Número do CNPJ Inválido");
        }
    }//GEN-LAST:event_cnpjjFormattedTextFieldFocusLost

    private void dataPossejDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataPossejDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPossejDateChooserFocusGained

    private void dataFimMandatojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFimMandatojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFimMandatojDateChooserFocusGained

    private void limiteCreditojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limiteCreditojTextFieldKeyReleased
        limiteCreditojTextField.setText(Formatacao.decinalValorMonetario(limiteCreditojTextField.getText()));
    }//GEN-LAST:event_limiteCreditojTextFieldKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmConsultaMunicipios(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroSindicojTextField;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepSindicojFormattedTextField1;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadeSindicojTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JComboBox clienteDescontojComboBox;
    private javax.swing.JFormattedTextField cnpjjFormattedTextField;
    private javax.swing.JTextField complementoSindicojTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JFormattedTextField cpfSindicojFormattedTextField;
    private com.toedter.calendar.JDateChooser dataAberturaContajDateChooser;
    private com.toedter.calendar.JDateChooser dataAtualizacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataCadastrojDateChooser;
    private com.toedter.calendar.JDateChooser dataCosultaCNPJjDateChooser;
    private com.toedter.calendar.JDateChooser dataFimMandatojDateChooser;
    private com.toedter.calendar.JDateChooser dataPossejDateChooser;
    private javax.swing.JComboBox diaPagamentojComboBox;
    private javax.swing.JTextField emailSindicojTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JComboBox emitirComprovantejComboBox;
    private javax.swing.JComboBox estadoSindicojComboBox;
    private javax.swing.JTextField estadojTextField;
    private javax.swing.JFormattedTextField foneCelularjFormattedTextField;
    private javax.swing.JFormattedTextField foneContatojFormattedTextField;
    private javax.swing.JFormattedTextField foneFixojFormattedTextField;
    private javax.swing.JFormattedTextField foneSindicojFormattedTextField;
    private javax.swing.JComboBox formaPagamentojComboBox;
    private javax.swing.JTextField iejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField limiteCreditojTextField;
    private javax.swing.JTextField logradouroSindicojTextField;
    private javax.swing.JTextField logradourojTextField;
    private javax.swing.JTextField nomeContatojTextField;
    private javax.swing.JTextField nomeSindicoljTextField;
    private javax.swing.JTextField numeroSindicojTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField observacaojTextField;
    private javax.swing.JTextField razaoSocialjTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JComboBox situacaojComboBox;
    private javax.swing.JComboBox tipoFechamentojComboBox;
    private javax.swing.JComboBox tipoLogradouroSindicojComboBox;
    private javax.swing.JComboBox tipoLogradourojComboBox;
    // End of variables declaration//GEN-END:variables

    public void preencherCampos(){
        popularObjetos();
        if (this.clienteendereco!=null){
            popularTelaEndereco();
        }
        if (this.clientefechamento!=null){
            popularTelaFechamento();
        }
        if (this.clientecondominio!=null){
            popularTelaDadosComplementares();
        }
        if (cliente!=null){
            popularTelaDadosIdentificacao();
        }
    }
    
    public void popularTelaDadosIdentificacao(){
        razaoSocialjTextField.setText(cliente.getNome());
        cnpjjFormattedTextField.setText(cliente.getDocFederal());
        iejTextField.setText(cliente.getDocEstadual());
        foneFixojFormattedTextField.setText(cliente.getFoneFixo());
        foneCelularjFormattedTextField.setText(cliente.getFoneCelular());
        emailjTextField.setText(cliente.getEmail());
        dataCosultaCNPJjDateChooser.setDate(cliente.getDataConsultacpf());
        situacaojComboBox.setSelectedItem(cliente.getSituacao());
        try {
            dataCadastrojDateChooser.setDate(cliente.getDataCadastro());
        } catch (Exception ex) {
            Logger.getLogger(FrmCadastrarClienteCondominio.class.getName()).log(Level.SEVERE, null, ex);
        }
        dataAtualizacaojDateChooser.setDate(cliente.getDataAtualizacao());
        observacaojTextField.setText(cliente.getObservacoes());
    }
    
    public void popularTelaDadosComplementares(){
        nomeContatojTextField.setText(clientecondominio.getNomeContato());
        foneContatojFormattedTextField.setText(clientecondominio.getFoneContato());
        nomeSindicoljTextField.setText(clientecondominio.getNomeSindico());
        foneSindicojFormattedTextField.setText(clientecondominio.getFoneSindico());
        cpfSindicojFormattedTextField.setText(clientecondominio.getCpfSindico());
        dataPossejDateChooser.setDate(clientecondominio.getDataPosse());
        dataFimMandatojDateChooser.setDate(clientecondominio.getDataFimMandato());
        dataAberturaContajDateChooser.setDate(clientecondominio.getDataAberturaConta());
        emailSindicojTextField.setText(clientecondominio.getEmailSindico());
        tipoLogradouroSindicojComboBox.setSelectedItem(clientecondominio.getTipoLogradouro());
        logradouroSindicojTextField.setText(clientecondominio.getLogradouro());
        numeroSindicojTextField.setText(clientecondominio.getNumero());
        complementoSindicojTextField.setText(clientecondominio.getComplemento());
        bairroSindicojTextField.setText(clientecondominio.getBairro());
        cepSindicojFormattedTextField1.setText(clientecondominio.getCep());
        cidadeSindicojTextField.setText(clientecondominio.getCidade());
        estadoSindicojComboBox.setSelectedItem(clientecondominio.getEstado()); 
    }
            
    
    public void popularTelaFechamento(){
        tipoFechamentojComboBox.setSelectedItem(clientefechamento.getTipoFechamento());
        diaPagamentojComboBox.setSelectedItem(clientefechamento.getDiaPagamento());
        formaPagamentojComboBox.setSelectedItem(clientefechamento.getFormaPagamento());
        emitirComprovantejComboBox.setSelectedItem(clientefechamento.getNotaFiscal());
        limiteCreditojTextField.setText(Formatacao.foramtarDoubleString(clientefechamento.getLimiteCredito()));
        if(cliente.getPossuiDesconto()==0){
            clienteDescontojComboBox.setSelectedItem("NAO");
        }else clienteDescontojComboBox.setSelectedItem("SIM");
    }
    
    public void popularTelaEndereco(){
        tipoLogradourojComboBox.setSelectedItem(clienteendereco.getTipoLogradouro());
        logradourojTextField.setText(clienteendereco.getLogradouro());
        numerojTextField.setText(clienteendereco.getNumero());
        complementojTextField.setText(clienteendereco.getComplemento());
        bairrojTextField.setText(clienteendereco.getBairro());
        cepjFormattedTextField.setText(clienteendereco.getCep());
        if (clienteendereco.getMunicipios() == 0) {
            cidadejTextField.setText(clienteendereco.getCidade());
            estadojTextField.setText(clienteendereco.getEstado());
        } else {
            MunicipiosController municipiosController = new MunicipiosController();
            this.municipios = municipiosController.getMunicipio(clienteendereco.getMunicipios());
            if (municipios != null) {
                cidadejTextField.setText(municipios.getNomeMunicipio());
                estadojTextField.setText(municipios.getEstado());
            }
        }
    }
    
    public void popularObjetos(){
        ClienteController clienteController = new ClienteController();
        
        clientecondominio = clienteController.consultarClientecondominio(cliente.getIdcliente());
        
        clienteendereco = clienteController.consultarClienteEndereco(cliente.getIdcliente());
        
        clientefechamento = clienteController.consultarClienteFechamento(cliente.getIdcliente());
    }
    
    public void iniciarObjetos(){
        cliente= new Cliente();
        clientecondominio = new Clientecondominio();
        clienteendereco = new Clienteendereco();
        clientefechamento = new Clientefechamento();
    }
    
    
    //Ppopular objetos
    
    public void popularCliente(){
        cliente.setDataAtualizacao(dataAtualizacaojDateChooser.getDate());
        cliente.setDataCadastro(dataCadastrojDateChooser.getDate());
        cliente.setDataConsultacpf(dataCosultaCNPJjDateChooser.getDate());
        cliente.setDocEstadual(iejTextField.getText());
        cliente.setDocFederal(cnpjjFormattedTextField.getText());
        cliente.setEmail(emailjTextField.getText());
        cliente.setFoneCelular(foneCelularjFormattedTextField.getText());
        cliente.setFoneFixo(foneFixojFormattedTextField.getText());
        cliente.setNome(razaoSocialjTextField.getText());
        cliente.setObservacoes(observacaojTextField.getText());
        cliente.setSituacao(situacaojComboBox.getSelectedItem().toString());
        cliente.setTipo("CD");
        cliente.setOperacao(10);
        if (clienteDescontojComboBox.getSelectedItem().toString().equalsIgnoreCase("NAO")){
            cliente.setPossuiDesconto(0);
        }else cliente.setPossuiDesconto(1);
    }
    
    public void popularEndereco(){
        if (clienteendereco==null){
            clienteendereco = new Clienteendereco();
        }
        clienteendereco.setBairro(bairrojTextField.getText());
        clienteendereco.setCep(cepjFormattedTextField.getText());
        clienteendereco.setClienteIdcliente(this.cliente.getIdcliente());
        clienteendereco.setComplemento(complementojTextField.getText());
        clienteendereco.setEstado(estadojTextField.getText());
        clienteendereco.setLogradouro(logradouroSindicojTextField.getText());
        clienteendereco.setNumero(numerojTextField.getText());
        clienteendereco.setCidade(cidadejTextField.getText());
       if (tipoLogradourojComboBox.getSelectedItem()!=null){
            clienteendereco.setTipoLogradouro(tipoLogradourojComboBox.getSelectedItem().toString());
        }clienteendereco.setTipoLogradouro("RUA");
        if (this.municipios!=null){
            clienteendereco.setMunicipios(this.municipios.getIdmunicipios());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro Código Municipio");
        }
    }
    
    public void popularFechamento(){
        if (clientefechamento==null){
            clientefechamento= new  Clientefechamento();
        }
        clientefechamento.setClienteIdcliente(this.cliente.getIdcliente());
        clientefechamento.setDiaPagamento(Integer.parseInt(diaPagamentojComboBox.getSelectedItem().toString()));
        clientefechamento.setFormaPagamento(formaPagamentojComboBox.getSelectedItem().toString());
        clientefechamento.setLimiteCredito(Formatacao.ConvercaoMonetariaDouble(limiteCreditojTextField.getText()));
        clientefechamento.setNotaFiscal(emitirComprovantejComboBox.getSelectedItem().toString());
        clientefechamento.setTipoFechamento(tipoFechamentojComboBox.getSelectedItem().toString());
    }
    
    
    
    public void popularCondominio(){
        if (clientecondominio==null){
            clientecondominio = new  Clientecondominio();
        }
        clientecondominio.setNomeContato(nomeContatojTextField.getText());
        clientecondominio.setFoneContato(foneContatojFormattedTextField.getText());
        clientecondominio.setNomeSindico(nomeSindicoljTextField.getText());
        clientecondominio.setFoneSindico(foneSindicojFormattedTextField.getText());
        clientecondominio.setCpfSindico(cpfSindicojFormattedTextField.getText());
        clientecondominio.setDataPosse(dataPossejDateChooser.getDate());
        clientecondominio.setDataFimMandato(dataFimMandatojDateChooser.getDate());
        clientecondominio.setDataAberturaConta(dataAberturaContajDateChooser.getDate());
        clientecondominio.setEmailSindico(emailSindicojTextField.getText());
        clientecondominio.setTipoLogradouro(tipoLogradouroSindicojComboBox.getSelectedItem().toString());
        clientecondominio.setLogradouro(logradouroSindicojTextField.getText());
        clientecondominio.setNumero(numeroSindicojTextField.getName());
        clientecondominio.setComplemento(complementoSindicojTextField.getText());
        clientecondominio.setBairro(bairroSindicojTextField.getText());
        clientecondominio.setCep(cepSindicojFormattedTextField1.getText());
        clientecondominio.setCidade(cidadeSindicojTextField.getText());
        clientecondominio.setEstado(estadoSindicojComboBox.getSelectedItem().toString());
        clientecondominio.setClienteIdcliente(this.cliente.getIdcliente());
    }
    
    // Validar Campos
    
    public String validarTelaDadosIdentificacao(){
        if (this.municipios==null){
            return "Municipio e Estado campo obrigatório";
        }
        if (razaoSocialjTextField.getText()==null){
            return "Razão Social campo obrigatório";
        }
        if (cnpjjFormattedTextField.getText()==null){
            return  "CNPJ campo obrigatório";
        }
        if (logradourojTextField.getText()==null){
            return "Logradouro campo obrigatório";
        }
        if (numerojTextField.getText()==null){
            return  "Número campo obrigatório";
        }
        if (bairrojTextField.getText()==null){
            return "Bairro campo obrigatório";
        }
        if (cepjFormattedTextField.getText()==null){
            return "CEP campo obrigatório";
        }
        if (cidadejTextField.getText()==null){
            return "Cidade campo obrigatório";
        }
        return null;
    }
    
    public String validarDadosComplementares(){
        if (nomeContatojTextField.getText()==null){
            return "Nome Contato campo obrigatório";
        }
        if (foneContatojFormattedTextField.getText()==null){
            return "Fone Contato campo obrigatório";
        }
        if (dataAberturaContajDateChooser.getDate()==null){
            return  "Data Fundaçãp campo obrigatório";
        }
        if (foneSindicojFormattedTextField.getText()==null){
            return "Fone Sócio campo obrigatório";
        }
        if (dataPossejDateChooser.getDate()==null){
            return "Data Posse campo obrigatório";
        }
        if (dataFimMandatojDateChooser.getDate()==null){
            return "Data Posse campo obrigatório";
        }
        
        
        
        if (foneSindicojFormattedTextField.getText()==null){
            return "Fone Sindico campo obrigatório";
        }
        if (cpfSindicojFormattedTextField.getText()==null){
            return "CPF Sindico campo obrigatório";
        }
        if (emailSindicojTextField.getText()==null){
            return "E-mail Sindico campo obrigatório";
        }
        if (logradouroSindicojTextField.getText()==null){
            return "Logradouro Sindico campo obrigatório";
        }
        if (numeroSindicojTextField.getText()==null){
            return "Numero Sindico campo obrigatório";
        }
        if (bairroSindicojTextField.getText()==null){
            return "Bairro Sindico campo obrigatório";
        }
        if (cepSindicojFormattedTextField1.getText()==null){
            return "CEP Sindico campo obrigatório";
        }
        if (cidadeSindicojTextField.getText()==null){
            return "Cidade Sindico campo obrigatório";
        }
        return null;
    }
    
    
    
    
    public void salvarDados(){
        popularCliente();
        ClienteController clienteController = new ClienteController();
        cliente = clienteController.salvarCliente(cliente);
        
        popularEndereco();
        clienteendereco = clienteController.salvarEndereco(clienteendereco);
        
        popularFechamento();
        clientefechamento = clienteController.salvarFechamento(clientefechamento);
        
        if (clientecondominio==null){
            clientecondominio = new Clientecondominio();
        }
        
        
        popularCondominio();
        clientecondominio= clienteController.salvarCondominio(clientecondominio);
        
   
    }
    
    
    public void formatarCampos() throws ParseException{
        cnpjjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        foneFixojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneCelularjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        cpfSindicojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        foneContatojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        foneSindicojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        cepSindicojFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        foneContatojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
    }

    public void carregarTodosClientes() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

   public void setMunicipio(Municipios municipios) {
        if (municipios!=null){
            this.municipios = municipios;
            cidadejTextField.setText(this.municipios.getNomeMunicipio());
            estadojTextField.setText(this.municipios.getEstado());
        }
    }

    public void resetMunicipio() {
        this.municipios=null;
        cidadejTextField.setText("");
        estadojTextField.setText("");
    }

}
