/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasReceber.Fechamento;

import Regras.FechamentoContasReceberController;
import Regras.Formatacao;
import controler.ConfiguracaoSistema;
import controler.Sigap;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Configuracao;
import model.FechamentoMes;
import org.springframework.core.env.JOptCommandLinePropertySource;
import view.ViewClienteFechamento;

/**
 *
 * @author wolverine
 */
public class FrmConsultaFechamentoMes extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultaFechamentoMes
     */
    private FechamentoMesTableModel modelFechamento;
    private List<ViewClienteFechamento> listaFechamento;
    private FechamentoMes mes;
    
    public FrmConsultaFechamentoMes() {
        initComponents();
         URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mesjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fechamentojTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        valorContajTextField = new javax.swing.JTextField();
        valorCreditosjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorReceberjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Fechamento Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Mes (MM/AAAA)");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(mesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        fechamentojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Fone Fixo", "Fone Celular", "Valor Conta", "Data Vencimento", "Valor Creditos", "Valor Receber", "Situação", "Tipo Fechamento", "Dia Pagto", "Forma Pagto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(fechamentojTable);
        fechamentojTable.getColumnModel().getColumn(0).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(1).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(2).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(3).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(4).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(5).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(6).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(7).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(8).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(9).setResizable(false);
        fechamentojTable.getColumnModel().getColumn(10).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Total Geral");

        valorContajTextField.setEditable(false);
        valorContajTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        valorContajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorContajTextField.setText("0,00");

        valorCreditosjTextField.setEditable(false);
        valorCreditosjTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        valorCreditosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorCreditosjTextField.setText("0,00");

        jLabel3.setText("Total dos Creditos");

        valorReceberjTextField.setEditable(false);
        valorReceberjTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        valorReceberjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorReceberjTextField.setText("0,00");

        jLabel4.setText("Total a Receber");

        jButton2.setText("Exportar Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(valorContajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(valorCreditosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(valorReceberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorReceberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorCreditosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorContajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (mesjTextField.getText().length()>0){
            pesquisarFechamentoMes();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(listaFechamento!=null){
            if (listaFechamento.size()>0) {
                exportaFechamentoClienteExcel();
            }else JOptionPane.showMessageDialog(rootPane, "Fechamento não foi gerado");
        }else JOptionPane.showMessageDialog(rootPane, "Fechamento não foi gerado");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fechamentojTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField mesjTextField;
    private javax.swing.JTextField valorContajTextField;
    private javax.swing.JTextField valorCreditosjTextField;
    private javax.swing.JTextField valorReceberjTextField;
    // End of variables declaration//GEN-END:variables

    public void pesquisarFechamentoMes(){
        FechamentoContasReceberController fechamentoContasReceberController = new FechamentoContasReceberController();
        mes = fechamentoContasReceberController.consultaFechamentoMes(mesjTextField.getText());
        if (mes!=null){
            listaFechamento = fechamentoContasReceberController.consultaFechamentoCliente(mes.getIdfechamentoMes());
            if (listaFechamento==null){
                listaFechamento = new ArrayList<ViewClienteFechamento>();
            }
            gerarFechamentoModel();
            calcularValotesTotais();
        }
    }
    
    
    public void gerarFechamentoModel(){
        modelFechamento = new FechamentoMesTableModel(listaFechamento);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        fechamentojTable.setModel(modelFechamento);
        fechamentojTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        fechamentojTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        fechamentojTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        fechamentojTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        fechamentojTable.getColumnModel().getColumn(5).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(6).setCellRenderer(renderer);
        fechamentojTable.getColumnModel().getColumn(6).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(7).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(8).setPreferredWidth(50);
        fechamentojTable.getColumnModel().getColumn(9).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(10).setPreferredWidth(40);
        fechamentojTable.getColumnModel().getColumn(11).setPreferredWidth(40);
        fechamentojTable.repaint();
        
    }
    
    public void calcularValotesTotais(){
        if (listaFechamento!=null){
            double valorPagar=0;
            double valorConta=0;
            double valorCredito=0;
            for(int i=0;i<listaFechamento.size();i++){
                valorConta+= listaFechamento.get(i).getValorConta();
                valorCredito+= listaFechamento.get(i).getValorCredito();
                valorPagar+= listaFechamento.get(i).getValorPagar();
            }
            valorContajTextField.setText(Formatacao.foramtarDoubleString(valorConta));
            valorCreditosjTextField.setText(Formatacao.foramtarDoubleString(valorCredito));
            valorReceberjTextField.setText(Formatacao.foramtarDoubleString(valorPagar));
        }
        
    }
    
    public void exportaFechamentoClienteExcel(){
        FechamentoContasReceberController fechamentoContasReceberController = new FechamentoContasReceberController();
        Sigap utilitario = new Sigap();
        ConfiguracaoSistema configura = new ConfiguracaoSistema();
        configura = (ConfiguracaoSistema) utilitario.deserializarConfiguracao();
        Map mapa = new HashMap();
        String banco = "use " + configura.getBdNome();
        String sql = "Select * from viewClienteFechamento where fechamentomes_idfechamentomes=" + mes.getIdfechamentoMes() + " order by nome";
        String linhaBanco = "jdbc:mysql://" + configura.getBdlocal()+ ":" + configura.getBdporta() + "/" +
                configura.getBdNome();
        fechamentoContasReceberController.exportarFechamentoClinte("Fechamento Cliente", linhaBanco, banco, sql, configura.getBdusuario(), configura.getBdSenha());
    }


}
