/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastrarFormaPagamento.java
 *
 * Created on 26/01/2012, 08:45:40
 */
package telas.FormasPagamento;

import Regras.BancoController;
import Regras.BandeiraCartaoController;
import Regras.FormaPagamentoController;
import Regras.Formatacao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.List;
import javax.swing.JComboBox;
import model.Banco;
import model.BandeirasCartao;
import model.Formapagamento;

/**
 *
 * @author Wolverine
 */
public class FrmCadastrarFormaPagamento extends javax.swing.JFrame {
    
    private Formapagamento formaPagamento;
    private IFormaPagamento telaCosulta;
    private int idEmpresa;

    /** Creates new form FrmCadastrarFormaPagamento */
    public FrmCadastrarFormaPagamento(Formapagamento formaPagamento, IFormaPagamento telaConsulta, int idEmpresa) {
        this.formaPagamento = formaPagamento;
        this.idEmpresa = idEmpresa;
        this.telaCosulta = telaConsulta;
        initComponents();
        if (formaPagamento!=null){
            preencherAlteracao();
        }
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        descricaojTextField.requestFocus();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descricaojTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        localjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comissaoDebitojTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comissaoParceladojTextField = new javax.swing.JTextField();
        bancojComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        prazoCreditojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numeroParcelasjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bandeirajComboBox = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        salvarjButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Forma de Pagamento");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Descrição");

        jLabel2.setText("Local Registro");

        localjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caixa", "Banco", "Conta" }));
        localjComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                localjComboBoxFocusLost(evt);
            }
        });

        jLabel3.setText("Comissão a Vista");

        comissaoDebitojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        comissaoDebitojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comissaoDebitojTextFieldFocusGained(evt);
            }
        });

        jLabel5.setText("Comissão Parcelado");

        comissaoParceladojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        comissaoParceladojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comissaoParceladojTextFieldFocusGained(evt);
            }
        });

        bancojComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bancojComboBoxFocusLost(evt);
            }
        });

        jLabel4.setText("Banco");

        prazoCreditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prazoCreditojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prazoCreditojTextFieldFocusGained(evt);
            }
        });

        jLabel6.setText("Prazo Crédito");

        numeroParcelasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numeroParcelasjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroParcelasjTextFieldFocusGained(evt);
            }
        });

        jLabel7.setText("No. Parcelas");

        jLabel8.setText("Bandeira do Cartão");

        bandeirajComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bandeirajComboBoxFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comissaoDebitojTextField))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comissaoParceladojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(370, 370, 370))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bandeirajComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(numeroParcelasjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(prazoCreditojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(bancojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descricaojTextField)
                                .addGap(18, 18, 18)
                                .addComponent(localjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bancojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comissaoParceladojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comissaoDebitojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroParcelasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(25, 25, 25))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prazoCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandeirajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarjButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        salvarjButton2.setText("Salvar");
        salvarjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salvarjButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        salvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButton2SalvarCadastroAssociado(evt);
            }
        });
        jPanel4.add(salvarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButton2SalvarCadastroAssociado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButton2SalvarCadastroAssociado
        FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
        formaPagamento.setDescricao(descricaojTextField.getText());
        formaPagamento.setLocalRegistro(localjComboBox.getSelectedItem().toString());
        if (formaPagamento.getLocalRegistro().equalsIgnoreCase("Banco")){
        Banco banco = (Banco) bancojComboBox.getSelectedItem();
        formaPagamento.setBanco(banco.getIdbanco());
        BandeirasCartao bandeira = (BandeirasCartao) bandeirajComboBox.getSelectedItem();
        formaPagamento.setBandeiraCartao(bandeira.getIdbandeirasCartao());
        formaPagamento.setComissaoVista(Double.parseDouble(comissaoDebitojTextField.getText()));
        formaPagamento.setComissaoParcelado(Double.parseDouble(comissaoParceladojTextField.getText()));
        formaPagamento.setNumeroParcelas(Integer.parseInt(numeroParcelasjTextField.getText()));
        formaPagamento.setPrazo(Integer.parseInt(prazoCreditojTextField.getText()));
        }else {
            formaPagamento.setBandeiraCartao(1);
            formaPagamento.setComissaoVista(0.0);
            formaPagamento.setComissaoParcelado(0.0);
            formaPagamento.setNumeroParcelas(0);
            formaPagamento.setPrazo(0);
        }
        formaPagamento.setEmpresa(idEmpresa);
        formaPagamentoController.salvarFormapagamento(formaPagamento);
        telaCosulta.carregarListaFormaPagamento();
        this.dispose();
    }//GEN-LAST:event_salvarjButton2SalvarCadastroAssociado

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void localjComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_localjComboBoxFocusLost
        if (localjComboBox.getSelectedItem().toString().equalsIgnoreCase("Banco")){
            bancojComboBox.setEnabled(true);
            comissaoDebitojTextField.setEnabled(true);
            comissaoParceladojTextField.setEnabled(true);
            numeroParcelasjTextField.setEnabled(true);
            prazoCreditojTextField.setEnabled(true);
            bandeirajComboBox.setEnabled(true);
        }else {
            bancojComboBox.setEnabled(false);
            comissaoDebitojTextField.setEnabled(false);
            comissaoParceladojTextField.setEnabled(false);
            numeroParcelasjTextField.setEnabled(false);
            prazoCreditojTextField.setEnabled(false);
            bancojComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_localjComboBoxFocusLost

    private void comissaoDebitojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoDebitojTextFieldFocusGained
        comissaoDebitojTextField.selectAll();
    }//GEN-LAST:event_comissaoDebitojTextFieldFocusGained

    private void comissaoParceladojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoParceladojTextFieldFocusGained
        comissaoParceladojTextField.selectAll();
    }//GEN-LAST:event_comissaoParceladojTextFieldFocusGained

    private void bancojComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bancojComboBoxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bancojComboBoxFocusLost

    private void prazoCreditojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prazoCreditojTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_prazoCreditojTextFieldFocusGained

    private void numeroParcelasjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroParcelasjTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroParcelasjTextFieldFocusGained

    private void bandeirajComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bandeirajComboBoxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bandeirajComboBoxFocusLost

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bancojComboBox;
    private javax.swing.JComboBox bandeirajComboBox;
    private javax.swing.JTextField comissaoDebitojTextField;
    private javax.swing.JTextField comissaoParceladojTextField;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox localjComboBox;
    private javax.swing.JTextField numeroParcelasjTextField;
    private javax.swing.JTextField prazoCreditojTextField;
    private javax.swing.JButton salvarjButton2;
    // End of variables declaration//GEN-END:variables

    
    
    public void preencherAlteracao(){
        if (formaPagamento.getLocalRegistro().equalsIgnoreCase("Banco")){
            preencherBandeiraCartao();
            preencherBanco();
            bancojComboBox.setEnabled(true);
            bandeirajComboBox.setEnabled(true);
            comissaoDebitojTextField.setEnabled(true);
            comissaoParceladojTextField.setEnabled(true);
            numeroParcelasjTextField.setEnabled(true);
            prazoCreditojTextField.setEnabled(true);
            BandeiraCartaoController bandeiraCartaoController = new BandeiraCartaoController();
            BandeirasCartao bandeira = bandeiraCartaoController.pesquisarid(formaPagamento.getBandeiraCartao());
            if (bandeira!=null){
                bancojComboBox.setSelectedItem(bandeira);
            }
            comissaoDebitojTextField.setText(Formatacao.foramtarDoubleString(formaPagamento.getComissaoVista()));
            comissaoParceladojTextField.setText(Formatacao.foramtarDoubleString(formaPagamento.getComissaoParcelado()));
            numeroParcelasjTextField.setText(String.valueOf(formaPagamento.getNumeroParcelas()));
            prazoCreditojTextField.setText(String.valueOf(formaPagamento.getPrazo()));
        }else {
            bandeirajComboBox.setEditable(false);
            bancojComboBox.setEnabled(false);
            comissaoDebitojTextField.setEnabled(false);
            comissaoParceladojTextField.setEnabled(false);
            numeroParcelasjTextField.setEnabled(false);
            prazoCreditojTextField.setEnabled(false);
        }
        descricaojTextField.requestFocus();
    }
    
    public void preencherBandeiraCartao(){
        BandeiraCartaoController bandeiraCartaoController = new BandeiraCartaoController();
        bancojComboBox = new JComboBox();
        List<BandeirasCartao> listaBandeiraCarta = bandeiraCartaoController.listar();
        if (listaBandeiraCarta!=null){
            for(int i=0;i<listaBandeiraCarta.size();i++){
                bancojComboBox.addItem(listaBandeiraCarta.get(i));
            }
        }
    }
    
    public void preencherBanco(){
        BancoController bancoController = new BancoController();
        List<Banco> listaBanco = bancoController.listar();
        if(listaBanco!=null){
            for(int i=0;i<listaBanco.size();i++){
                bancojComboBox.addItem(listaBanco.get(i));
            }
        }
    }
    
}
