/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAlterarValorVenda.java
 *
 * Created on 28/04/2011, 13:37:36
 */

package telas.Entrada;

import Regras.Formatacao;
import Interfaces.ItelaConsulta;
import controler.Sigap;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Estoque;

/**
 *
 * @author Wolverine
 */
public class FrmAlterarValorVenda extends javax.swing.JFrame {

    /** Creates new form FrmAlterarValorVenda */
    private Estoque estoque;
    private ItelaConsulta telaConsulta;
    private Double valorCusto;

    public FrmAlterarValorVenda(Estoque estoque, ItelaConsulta telaConsulta, Double valorCusto) {
        if (estoque==null){
            this.estoque = new Estoque();
        }else this.estoque = estoque;
        this.telaConsulta = telaConsulta;
        this.valorCusto = valorCusto;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        if (this.estoque != null) {
            if (this.estoque.getIdestoque() != null) {
                percentualVendasjTextField.setText(Sigap.ConvercaoMonetaria(this.estoque.getPercentualVendas()));
                valorVendajTextField.setText(Sigap.ConvercaoMonetaria(this.estoque.getValorVenda()));
            }
        }
        percentualVendasjTextField.requestFocus();
        percentualVendasjTextField.selectAll();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        percentualVendasjTextField = new javax.swing.JTextField();
        valorVendajTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        salvarjButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de Valores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        percentualVendasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        percentualVendasjTextField.setText("0,00");
        percentualVendasjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                percentualVendasjTextFieldFocusGained(evt);
            }
        });
        percentualVendasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                percentualVendasjTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                percentualVendasjTextFieldKeyReleased(evt);
            }
        });

        valorVendajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorVendajTextField.setText("0,00");
        valorVendajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorVendajTextFieldFocusGained(evt);
            }
        });
        valorVendajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valorVendajTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorVendajTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("% de Vendas");

        jLabel2.setText("Valor de Venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(percentualVendasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(valorVendajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentualVendasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorVendajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarjButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        salvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        salvarjButton2.setText("Salvar");
        salvarjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salvarjButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        salvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButton2SalvarCadastroAssociado(evt);
            }
        });
        jPanel4.add(salvarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2FecharCadastro(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButton2SalvarCadastroAssociado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButton2SalvarCadastroAssociado
        estoque.setPercentualVendas(Sigap.ConvercaoMonetariaDouble(percentualVendasjTextField.getText()));
        estoque.setValorVenda(Formatacao.formatarStringfloat(valorVendajTextField.getText()));
        telaConsulta.setAlterarValorVenda(estoque);
        this.dispose();
}//GEN-LAST:event_salvarjButton2SalvarCadastroAssociado

    private void jButton2FecharCadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2FecharCadastro
        this.dispose();
}//GEN-LAST:event_jButton2FecharCadastro

    private void percentualVendasjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentualVendasjTextFieldKeyReleased
        percentualVendasjTextField.setText(Sigap.decinalValorMonetario(percentualVendasjTextField.getText()));
    }//GEN-LAST:event_percentualVendasjTextFieldKeyReleased

    private void valorVendajTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorVendajTextFieldKeyReleased
        valorVendajTextField.setText(Sigap.decinalValorMonetario(valorVendajTextField.getText()));
    }//GEN-LAST:event_valorVendajTextFieldKeyReleased

    private void percentualVendasjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentualVendasjTextFieldKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER) {
           Double percentual = Sigap.ConvercaoMonetariaDouble(percentualVendasjTextField.getText());           
           Double valorVenda = Formatacao.calcularValorPercentual(percentual, valorCusto);
           valorVendajTextField.setText(Sigap.ConvercaoMonetaria(valorVenda));
       }
    }//GEN-LAST:event_percentualVendasjTextFieldKeyPressed

    private void valorVendajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorVendajTextFieldKeyPressed
       if (evt.getKeyCode() == evt.VK_ENTER) {
           Double valorVenda = Sigap.ConvercaoMonetariaDouble(valorVendajTextField.getText());
           Double percentual = Formatacao.calcularValorValorVenda(valorVenda, valorCusto);
           percentualVendasjTextField.setText(Sigap.ConvercaoMonetaria(percentual));
       }
    }//GEN-LAST:event_valorVendajTextFieldKeyPressed

    private void percentualVendasjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_percentualVendasjTextFieldFocusGained
        percentualVendasjTextField.selectAll();
    }//GEN-LAST:event_percentualVendasjTextFieldFocusGained

    private void valorVendajTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorVendajTextFieldFocusGained
        valorVendajTextField.selectAll();
    }//GEN-LAST:event_valorVendajTextFieldFocusGained

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField percentualVendasjTextField;
    private javax.swing.JButton salvarjButton2;
    private javax.swing.JTextField valorVendajTextField;
    // End of variables declaration//GEN-END:variables

}
