/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.NotaSaida;

import Regras.AliquotaController;
import Regras.CodigoFiscalController;
import Regras.EstoqueController;
import Regras.Formatacao;
import Regras.IbptController;
import Regras.MunicipiosController;
import Regras.NotaSaidaController;
import Regras.ParametroLocalController;
import Regras.ProdutoController;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import controler.UsuarioLogado;
import facade.TerminalVendasFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Aliquota;
import model.Cliente;
import model.Codigofiscal;
import model.Estoque;
import model.Fornecedor;
import model.Ibpt;
import model.Municipios;
import model.NotaSaida;
import model.ParametrosLocal;
import model.Produto;
import model.Terminalcliente;
import model.Terminalproduto;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.NotaSaida.Fatura.DuplicataBean;
import telas.NotaSaida.Fatura.FaturaBean;

/**
 *
 * @author wolverine
 */
public class FrmEmitirNotaSaidaDevolucao extends javax.swing.JFrame implements INotaSaidaBean{
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private NotaSaidaBean notaSaidaBean;
    private List<NotaSaidaProdutoBean> listaProdutoBean;
    private Fornecedor fornecedor;
    private Config config;
    private ListaProdutoSaidaBeanTableModel modelProduto;
    private UsuarioLogado usuarioLogado;
    private FileWriter arquivo;
    private String caminhoXML;
    private File arquivoXML;
    private boolean notaCarregarda;
    private String chaveAutorizacao;
    private ParametrosLocal parametrosLocal;
    private INotaSaidaBean telaConsulta;
    private String numeroECFVenda;

    /**
     * Creates new form FrmEmitirNotaSaida
     */
    public FrmEmitirNotaSaidaDevolucao(Config config, UsuarioLogado usuarioLogado, INotaSaidaBean telaConsulta) {
        notaSaidaBean = new NotaSaidaBean();
        this.telaConsulta = telaConsulta;
        this.notaCarregarda = false;
        notaSaidaBean.setNumeroOrdemECF("0");
        this.usuarioLogado = usuarioLogado;
        listaProdutoBean = new ArrayList<NotaSaidaProdutoBean>();
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.config = config;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarComboBoxCFOP();
        gerarNumeroNFe();
        ParametroLocalController parametroLocalController = new ParametroLocalController();
        parametrosLocal = parametroLocalController.localizarEmpresa(this.config.getEmpresa().getIdparametros());
        dataEmissaojDateChooser.setDate(new Date());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comSTjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        semSTjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tipoNFejComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroNFejTextField = new javax.swing.JTextField();
        seriejTextField = new javax.swing.JTextField();
        naturezaOperacaojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataEmissaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    totalProdutojTextField = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    totalNotajTextField = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    observacaojTextField = new javax.swing.JTextField();
    jLabel23 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    gerarjButton = new javax.swing.JButton();
    valorDescontojTextField = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    valorTributosjTextField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    nomejTextField = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    cpfjFormattedTextField = new javax.swing.JFormattedTextField();
    rgjTextField = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    foneFixojFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel13 = new javax.swing.JLabel();
    emailjTextField = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    complementojTextField = new javax.swing.JTextField();
    jLabel24 = new javax.swing.JLabel();
    numerojTextField = new javax.swing.JTextField();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    logradourojTextFiel = new javax.swing.JTextField();
    cidadejTextField = new javax.swing.JTextField();
    jLabel27 = new javax.swing.JLabel();
    cepjFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel28 = new javax.swing.JLabel();
    bairrojTextField = new javax.swing.JTextField();
    jLabel29 = new javax.swing.JLabel();
    estadojComboBox = new javax.swing.JComboBox();
    jLabel30 = new javax.swing.JLabel();
    jButton7 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    produtojTable = new javax.swing.JTable();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Emitir NF-e");

    jLabel1.setText("CFOP com ST");

    jLabel2.setText("CFOP sem ST");

    jLabel3.setText("Tipo de NF-e");

    tipoNFejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saida", "Entrada", " " }));

    jLabel4.setText("No. da NF-e");

    jLabel5.setText("Série");

    seriejTextField.setEditable(false);

    naturezaOperacaojTextField.setText("Venda de Mercadorias");

    jLabel6.setText("Natureza da Operação");

    dataEmissaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataEmissaojDateChooserFocusGained(evt);
        }
    });

    jLabel7.setText("Data Emissão");

    jLabel8.setText("Valor Total Produtos");

    totalProdutojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    totalProdutojTextField.setText("0");

    jLabel9.setText("Valor Total da Nota");

    totalNotajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    totalNotajTextField.setText("0");

    jButton1.setText("Calcular");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    observacaojTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            observacaojTextFieldActionPerformed(evt);
        }
    });

    jLabel23.setText("Informações Adcionais");

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    gerarjButton.setText("Gerar NF-e");
    gerarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            gerarjButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(278, 278, 278)
            .addComponent(gerarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(gerarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    valorDescontojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorDescontojTextField.setText("0");

    jLabel16.setText("Valor Desconto");

    jLabel17.setText("Valor Tributos");

    valorTributosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorTributosjTextField.setText("0");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(numeroNFejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(seriejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(naturezaOperacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3)
                        .addComponent(tipoNFejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(semSTjComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 777, Short.MAX_VALUE)
                            .addComponent(comSTjComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel7))
                                .addComponent(dataEmissaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(totalProdutojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(valorDescontojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(valorTributosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(totalNotajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comSTjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(semSTjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tipoNFejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(numeroNFejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(seriejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(naturezaOperacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataEmissaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalProdutojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorDescontojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorTributosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalNotajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addComponent(jLabel23)
            .addGap(4, 4, 4)
            .addComponent(observacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(93, 93, 93))
    );

    jTabbedPane1.addTab("Dados da NF-e", jPanel1);

    jLabel10.setText("Nome");

    nomejTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nomejTextFieldActionPerformed(evt);
        }
    });

    jLabel11.setText("Nº CNPJ");

    cpfjFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cpfjFormattedTextFieldFocusLost(evt);
        }
    });

    jLabel12.setText("Inscrição Estadual");

    jLabel13.setText("Fone Fixo");

    jLabel15.setText("E-mail");

    jLabel24.setText("Logradouro");

    jLabel25.setText("Número");

    jLabel26.setText("Complemento");

    cidadejTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cidadejTextFieldActionPerformed(evt);
        }
    });

    jLabel27.setText("Cidade");

    jLabel28.setText("CEP");

    jLabel29.setText("Bairro");

    estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SC", "RS", "PR", "SP", "RJ", "ES", "MG", "MT", "MS", "BH" }));

    jLabel30.setText("Estado");

    jButton7.setText("Consultar Fornecedor");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logradourojTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(complementojTextField)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addComponent(nomejTextField)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(emailjTextField)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel27)
                            .addGap(303, 303, 303))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(estadojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 70, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addGap(0, 769, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton7)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12)
                .addComponent(jLabel13)
                .addComponent(jLabel15))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneFixojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24)
                .addComponent(jLabel25)
                .addComponent(jLabel26))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradourojTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jLabel28)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton7)
            .addContainerGap(236, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Fornecedor", jPanel2);

    produtojTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Código", "Descrição", "Unidade", "NCM", "Quantidade", "Valor Unitario", "Valor Total"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane1.setViewportView(produtojTable);
    if (produtojTable.getColumnModel().getColumnCount() > 0) {
        produtojTable.getColumnModel().getColumn(0).setResizable(false);
        produtojTable.getColumnModel().getColumn(1).setResizable(false);
        produtojTable.getColumnModel().getColumn(2).setResizable(false);
        produtojTable.getColumnModel().getColumn(3).setResizable(false);
        produtojTable.getColumnModel().getColumn(4).setResizable(false);
        produtojTable.getColumnModel().getColumn(5).setResizable(false);
        produtojTable.getColumnModel().getColumn(6).setResizable(false);
    }

    jButton3.setText("Incluir Produtos Venda");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jButton4.setText("Excluir Produtos");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jButton5.setText("Alterar NCM");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(147, 147, 147)
            .addComponent(jButton3)
            .addGap(91, 91, 91)
            .addComponent(jButton4)
            .addGap(96, 96, 96)
            .addComponent(jButton5)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3)
                .addComponent(jButton4)
                .addComponent(jButton5))
            .addContainerGap())
    );

    jTabbedPane1.addTab("Produtos", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataEmissaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataEmissaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEmissaojDateChooserFocusGained

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    private void cpfjFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldFocusLost
    }//GEN-LAST:event_cpfjFormattedTextFieldFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int linha = produtojTable.getSelectedRow();
        if (linha>=0){
            listaProdutoBean.remove(linha);
            setModelProduto();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       int linha = produtojTable.getSelectedRow();
       if (linha>=0){
           String ncm = "";
           ncm = JOptionPane.showInputDialog("Informe NCM Somente Numeros");
           listaProdutoBean.get(linha).getProduto().setNcm(ncm);
           ProdutoController produtoController = new ProdutoController();
           Produto prod = produtoController.consultarProdutoid(listaProdutoBean.get(linha).getProduto().getIdProduto());
           if (prod!=null){
               prod.setNcm(ncm);
               produtoController.salvarProduto(prod);
           }
           setModelProduto();
       }else{
           JOptionPane.showMessageDialog(rootPane, "Selecione um produto");
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void observacaojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observacaojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observacaojTextFieldActionPerformed

    private void cidadejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadejTextFieldActionPerformed

    private void gerarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarjButtonActionPerformed
        gerarjButton.setText("Aguarde Gerando NF-e");
        String erro = validarDadosNFe();
        if (erro != null) {
            JOptionPane.showMessageDialog(rootPane, erro);
            gerarjButton.setText("Gerar NF-e");
        } else {
            
            notaSaidaBean.setFornecedor(fornecedor);
            notaSaidaBean.setEmpresa(this.config.getEmpresa());
            notaSaidaBean.setDataEmissao((dataEmissaojDateChooser.getDate()));
            notaSaidaBean.setDataSaida((dataEmissaojDateChooser.getDate()));
            notaSaidaBean.setFormaPagamento("Á Vista");
            notaSaidaBean.setListaProdutos(listaProdutoBean);
            notaSaidaBean.setNaturezaOperacao(naturezaOperacaojTextField.getText());
            notaSaidaBean.setCodigo(numeroNFejTextField.getText());
            notaSaidaBean.setNuemro(numeroNFejTextField.getText());
            notaSaidaBean.setTipo(tipoNFejComboBox.getSelectedItem().toString());
            notaSaidaBean.setSerie1(seriejTextField.getText());
            notaSaidaBean.setSerie2("");
            calcularTotaisNotaFiscal();
            notaSaidaBean.setInfoTexto("EMPRESA ENQUADRADA NO SIMPLES NACIONAL");
            try {
                gerarArquivoNFe();
//                salvarNumeroNFe();
                String texto = "NFE.CriarEnviarNFeSefaz(" +
                this.config.getCaminhoNFe() + "ctexto.txt,1)";
                gerarArquivoAcbr(texto);
                Timer timer = new Timer();
                timer.schedule(new RemindTask(), 20 * 1000);
            } catch (IOException ex) {
                Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_gerarjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            new FrmSelecionarClienteTerminal(this);
        } catch (Exception ex) {
            Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularTotaisNotaFiscal();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param ags the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JComboBox comSTjComboBox;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private com.toedter.calendar.JDateChooser dataEmissaojDateChooser;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JComboBox estadojComboBox;
    private javax.swing.JFormattedTextField foneFixojFormattedTextField;
    private javax.swing.JButton gerarjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField logradourojTextFiel;
    private javax.swing.JTextField naturezaOperacaojTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroNFejTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField observacaojTextField;
    private javax.swing.JTable produtojTable;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JComboBox semSTjComboBox;
    private javax.swing.JTextField seriejTextField;
    private javax.swing.JComboBox tipoNFejComboBox;
    private javax.swing.JTextField totalNotajTextField;
    private javax.swing.JTextField totalProdutojTextField;
    private javax.swing.JTextField valorDescontojTextField;
    private javax.swing.JTextField valorTributosjTextField;
    // End of variables declaration//GEN-END:variables
    public void setModelProduto(){
        if (listaProdutoBean==null){
            listaProdutoBean = new ArrayList<NotaSaidaProdutoBean>();
        }
        modelProduto = new ListaProdutoSaidaBeanTableModel(listaProdutoBean);
        produtojTable.setModel(modelProduto);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        produtojTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        produtojTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        produtojTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        produtojTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        produtojTable.getColumnModel().getColumn(4).setCellRenderer(renderer);
        produtojTable.getColumnModel().getColumn(4).setPreferredWidth(30);
        produtojTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        produtojTable.getColumnModel().getColumn(5).setPreferredWidth(30);
        produtojTable.getColumnModel().getColumn(6).setCellRenderer(renderer);
        produtojTable.getColumnModel().getColumn(6).setPreferredWidth(30);
        produtojTable.repaint();
    }

    
    

    public void incluirProdutoVenda(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    public void carregarComboBoxCFOP(){
        CodigoFiscalController codigoFiscalController = new CodigoFiscalController();
        List<Codigofiscal> listaCodigoFiscal = codigoFiscalController.listarCodigoFiscal("SST");
        if (listaCodigoFiscal!=null){
            for(int i=0;i<listaCodigoFiscal.size();i++){
                comSTjComboBox.addItem(listaCodigoFiscal.get(i));
            }
        }
        listaCodigoFiscal = codigoFiscalController.listarCodigoFiscal("CST");
        if (listaCodigoFiscal!=null){
            for(int i=0;i<listaCodigoFiscal.size();i++){
                semSTjComboBox.addItem(listaCodigoFiscal.get(i));
            }
        }
    }
    
   public void gerarArquivoAcbr(String texto) {
        try {
            FileWriter acbr = new FileWriter(new File(this.config.getCaminhoAcbr() + "ENTNFE.txt"));
            acbr.write(texto);
            acbr.close();
        } catch (IOException ex) {
            Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
   
   public void lerArquivoSaidaAcbr() throws IOException{
       File arqSaida = new File(this.config.getCaminhoAcbr() + "sainfe.txt");
        String xml = null;
        BufferedReader leitor = null;
        FileReader sainfe;
        while (!arqSaida.exists()) {
            arqSaida = new File(this.config.getCaminhoAcbr() + "sainfe.txt");
        }
        if (!arqSaida.exists()){
            JOptionPane.showMessageDialog(rootPane, "Arquivo de Saída não Localizado");
        }
        sainfe = new FileReader(arqSaida);
        leitor = new BufferedReader(sainfe);
        xml = leitor.readLine();

        String linha = xml.substring(0, 2);
        if (linha.equalsIgnoreCase("OK")) {
            if (verificarRetornoNFe(leitor)){
                JOptionPane.showMessageDialog(rootPane, "Nota Fiscal Gerada com Sucesso");
                gerarjButton.setText("Gerar NF-e");
                carregarCahveAutorizacao(leitor);
                new FrmLocalizarArquivoNFe(this, this.config.getCaminhoNFe());
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Erro oa gerar Nota Fiscal");
            gerarjButton.setText("Gerar NF-e");
            new FrmMostrarErroNotaSaida(leitor);
            leitor.close();
            apagarArquivoSaidaAcbr();
        }
        leitor.close();
        
    }
    
    public void gerarArquivoNFe() throws IOException{
        arquivo = new FileWriter(new File(this.config.getCaminhoNFe() + "cTexto.txt"));
        notaSaidaBean.setHoraSaida(Formatacao.foramtarHoraString());
        //Identificaoção
        arquivo.write("NOTAFISCAL|1" + "\r\n");
        gerarDadosNotaFiscal();
        gerarDadosCupomFiscalReferenciado();
        gerarDadosEmitente();
        gerarDadosDestinatario();
        gerarDadosProduto();
        gerarTotaisSimplesNacional();
        if (notaSaidaBean.getFormaPagamento().equalsIgnoreCase("A PRAZO")){
            if (notaSaidaBean.getFatura()!=null){
                gerarFatura();
                if (notaSaidaBean.getFatura().getListaDuplicata()!=null){
                    gerarDuplicatas();
                }
            }
        }
        arquivo.close();
    }
    
    public void gerarDadosNotaFiscal() throws IOException{
        arquivo.write("A|2.00||" + "\r\n");
        arquivo.write("B|");
        arquivo.write("42|");//Codigo do Estado SC=42
        arquivo.write("|");
        arquivo.write(validarTamanho(notaSaidaBean.getNaturezaOperacao()) + "|");
        arquivo.write("0" + "|");
        arquivo.write("55|");
        arquivo.write(notaSaidaBean.getSerie1()+ "|");
        arquivo.write(notaSaidaBean.getNuemro() + "|");
//        arquivo.write(Formatacao.ConvercaoDataNfe(notaSaidaBean.getDataEmissao()) + "|");
    //    arquivo.write(Formatacao.ConvercaoDataNfe(notaSaidaBean.getDataSaida()) + "|");
        arquivo.write(notaSaidaBean.getHoraSaida() + "|");
        arquivo.write(verificarTipoNFe() + "|");
        arquivo.write("4205407|");//Codigo Municipio
        arquivo.write("1|");//Formato de Impressao do Danfe
        arquivo.write("1|");//Forma de Emissao da NF-e
        arquivo.write("|");//Digito verificar do Chave de acesso na informar na importacao
        arquivo.write("1|");//Identificaocao do Hambiente
        arquivo.write("1|");//finalidade da Emissao da NF-e 1 - Normal
        arquivo.write("3|" + parametrosLocal.getVersaonfe());//Processo de emissao da NF-e
        arquivo.write("|||");
        arquivo.write("\r\n");
    }
    
    public void gerarDadosCupomFiscalReferenciado() throws IOException{        
        if (!notaSaidaBean.getNumeroOrdemECF().equalsIgnoreCase("0")){
            arquivo.write("B20j|");
            arquivo.write("2D|");
            arquivo.write(notaSaidaBean.getNumeroOrdemECF() + "|");
            arquivo.write(notaSaidaBean.getNumeroCOO() + "|");
            arquivo.write("\r\n");
        }
    }
    
    public void gerarDadosEmitente() throws IOException{
        // Dados do Emitente
        arquivo.write("C|");//Classe Dados do Emitente
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getRazaoSocial()) + "|");//RazaoSocial
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getNomeFantasia()) + "|");//Nome Fantasia
        arquivo.write(retirarPontos(notaSaidaBean.getEmpresa().getInscricaoEstadual() + "|"));//Inscricao Estadual
        arquivo.write("|");//Inscricao Estadual ST
        arquivo.write(notaSaidaBean.getEmpresa().getInscricaoMunicipal() + "|"); //Inscricao Municipal
        arquivo.write(notaSaidaBean.getEmpresa().getCnae() + "|"); //Numero da Codigo Ativadade Economoca
        arquivo.write(notaSaidaBean.getEmpresa().getCrt() + "|"); //Se a empresa e enquadrada ou nao no Simples
        arquivo.write("\r\n");
        
        //Dados do CNPJ
        arquivo.write("C02|");
        arquivo.write(retirarPontos(notaSaidaBean.getEmpresa().getCnpj()) + "|" + "\r\n");
        
        //Dados do Endereco
        arquivo.write("C05|");
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getTipoLogradouro() + " " +  notaSaidaBean.getEmpresa().getLogradouro()) + "|");
        arquivo.write(notaSaidaBean.getEmpresa().getNumero() + "|");
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getComplemento()) + "|");
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getBairro()) + "|");
        arquivo.write(consultarCodgioMunicipio(notaSaidaBean.getEmpresa().getMunicipios()) + "|");
        arquivo.write(validarTamanho(notaSaidaBean.getEmpresa().getCidade()) + "|");
        arquivo.write(notaSaidaBean.getEmpresa().getUf() + "|");
        arquivo.write(retirarPontos(notaSaidaBean.getEmpresa().getCep()) + "|");
        arquivo.write("1058" + "|");//Codigo Pais
        arquivo.write("Brasil" + "|"); //Pais
        arquivo.write(retirarPontos(notaSaidaBean.getEmpresa().getFoneComercial()) + "|");
        arquivo.write("\r\n");
    }
    
    public void gerarDadosDestinatario() throws IOException{
        //Dados do Destinatario
        arquivo.write("E|");
        arquivo.write(validarTamanho(nomejTextField.getText()) + "|");
        arquivo.write(retirarPontos(rgjTextField.getText()) + "|");
        arquivo.write("|");//Inscricao Suframa
        arquivo.write(emailjTextField.getText() + "|");
        arquivo.write("\r\n");
        arquivo.write("E02|");
        arquivo.write(retirarPontos(cpfjFormattedTextField.getText()) + "|");
        arquivo.write("\r\n");
        
        //Endereco do Destinatario
        arquivo.write("E05|");
        arquivo.write(validarTamanho(logradourojTextFiel.getText()) + "|");
        arquivo.write(numerojTextField.getText() + "|");
        arquivo.write(validarTamanho(complementojTextField.getText()) + "|");
        arquivo.write(validarTamanho(bairrojTextField.getText()) + "|");
        arquivo.write(consultarCodgioMunicipio(notaSaidaBean.getFornecedor().getMunicipios()) + "|");
        arquivo.write(validarTamanho(cidadejTextField.getText()) + "|");
        arquivo.write(estadojComboBox.getSelectedItem().toString() + "|");
        arquivo.write(retirarPontos(cepjFormattedTextField.getText()) + "|");
        arquivo.write("1058" + "|");
        arquivo.write("Brasil" + "|");
        arquivo.write(retirarPontos(notaSaidaBean.getFornecedor().getTelefone()) + "|");
        arquivo.write("\r\n");
    }
    
    public void gerarDadosProduto() throws IOException{
        for (int i = 0; i < listaProdutoBean.size(); i++) {
            arquivo.write("H|");
            arquivo.write((i+1) + "|");//Numero do item
            arquivo.write("VALOR APROXIMADO DOS TRIBUTOS R$ " + Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValorTributo()) +"|");//Informacoes Adicionais
            arquivo.write("\r\n");
            arquivo.write("I|");
            arquivo.write(String.valueOf(listaProdutoBean.get(i).getProduto().getReferencia()) + "|");
            arquivo.write(verificarCodgioBarras(listaProdutoBean.get(i).getProduto().getIdProduto()) + "|");//codigo Barras
            arquivo.write(listaProdutoBean.get(i).getProduto().getDescricao() + "|");
            arquivo.write(listaProdutoBean.get(i).getProduto().getNcm() + "|");
            arquivo.write("|");
            arquivo.write(listaProdutoBean.get(i).getCfop() + "|");
            arquivo.write(listaProdutoBean.get(i).getProduto().getUnidade() + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getQuantidade())) +"00" + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValorUnitario())) + "00000000" + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValortotal())) + "|");
            arquivo.write(verificarCodgioBarras(listaProdutoBean.get(i).getProduto().getIdProduto()) + "|");
            arquivo.write(listaProdutoBean.get(i).getProduto().getUnidade() + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getQuantidade())) +"00" + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValorUnitario())) + "00000000" + "|");
            arquivo.write("|");
            arquivo.write("|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValorDesconto())) + "|");
            arquivo.write("|");
            arquivo.write("1" + "|");
            arquivo.write("|");
            arquivo.write("|");
            arquivo.write("\r\n");
            arquivo.write("M|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(listaProdutoBean.get(i).getValorTributo())) + "|");
            arquivo.write("\r\n");
            arquivo.write("N|");
            arquivo.write("\r\n");
            if (listaProdutoBean.get(i).getProduto().getAliquota()==6){
                arquivo.write("N10g|0|500||||");
            }else {
                arquivo.write("N10g|0|102||||");
            }
            arquivo.write("\r\n");
            gerarPisSimplesNacional();
            gerarCofinsSimplesNacional();
            
        }
    }
    
    
    public void gerarTotaisSimplesNacional() throws IOException{
        arquivo.write("W|");
        arquivo.write("\r\n");
        arquivo.write("W02|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(notaSaidaBean.getTotalValoProdutos())) + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(notaSaidaBean.getValorDesconto())) + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write("0.00" + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(notaSaidaBean.getValorNota())) + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarDoubleString(notaSaidaBean.getTotalTributios())) + "|");
        arquivo.write("\r\n");
        arquivo.write("X|9|");
        arquivo.write("\r\n");
        arquivo.write("Z||" + notaSaidaBean.getInfoTexto() + " - VALOR APROXIMADO DOS TRIBUTOS R$ " +
                Formatacao.foramtarDoubleString(notaSaidaBean.getTotalTributios()) + "|");
    }
    
    public void gerarPisSimplesNacional() throws IOException{
        arquivo.write("Q|");
        arquivo.write("\r\n");
        arquivo.write("Q05|");
        arquivo.write("99"+ "|");
        arquivo.write("0.00"+ "|");
        arquivo.write("\r\n");
        arquivo.write("Q07|");
        arquivo.write("0.00"+ "|");
        arquivo.write("0.00"+ "|");
        arquivo.write("\r\n");
    }
    
    public void gerarCofinsSimplesNacional() throws IOException{
        arquivo.write("S|");
        arquivo.write("\r\n");
        arquivo.write("S05|");
        arquivo.write("99"+ "|");
        arquivo.write("0.00"+ "|");
        arquivo.write("\r\n");
        arquivo.write("S07|");
        arquivo.write("0.00"+ "|");
        arquivo.write("0.00"+ "|");
        arquivo.write("\r\n");
    }
    
    public void gerarFatura() throws IOException{
        arquivo.write("Y|");
        arquivo.write("\r\n");
        arquivo.write("Y02|");
        arquivo.write(notaSaidaBean.getFatura().getNumero() + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarFloatString(notaSaidaBean.getFatura().getValorOrigianl())) + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarFloatString(notaSaidaBean.getFatura().getValorDesconto())) + "|");
        arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarFloatString(notaSaidaBean.getFatura().getValorLiquido())) + "|");
        arquivo.write("\r\n");
    }
    
    public void gerarDuplicatas() throws IOException{
        for(int i=0;i<notaSaidaBean.getFatura().getListaDuplicata().size();i++){
            arquivo.write("Y07|");
            arquivo.write(notaSaidaBean.getFatura().getListaDuplicata().get(i).getNumero() + "|");
//            arquivo.write(Formatacao.ConvercaoDataNfe(notaSaidaBean.getFatura().getListaDuplicata().get(i).getDataVencimento()) + "|");
            arquivo.write(FormatarValoreMonetarios(Formatacao.foramtarFloatString(notaSaidaBean.getFatura().getListaDuplicata().get(i).getValor()))+ "|");
            arquivo.write("\r\n");
        }   
    }
    
    public String retirarPontos(String dado){
        String formatado ="";
        char c = ' ';
        for(int i=0;i<dado.length();i++){
            c = dado.charAt(i);
            if ((c!='.') && (c!=',') && (c!='-') && (c!='/') && (c!='(') && (c!=')')){
               formatado+= c;
            }
        }
        return formatado;
    }
    
    public String FormatarValoreMonetarios(String dado){
        String formatado ="";
        char c = ' ';
        for(int i=0;i<dado.length();i++){
            c = dado.charAt(i);
            if ((c!='.')){
               if (c==','){
                   formatado+= '.';
               } else {
                   formatado+= c;
               }
            }
        }
        return formatado;
    }
    
    public String verificarTipoNFe(){
        if (tipoNFejComboBox.getSelectedItem().toString().equalsIgnoreCase("Saida")){
            return "1";
        }else if (tipoNFejComboBox.getSelectedItem().toString().equalsIgnoreCase("Entrada")){
            return "0";
        }else {
            return "1";
        }
    }
    
    public String verificarMMAACupomFiscal() {
        String dados;
        if (notaSaidaBean.getDataEmissaoCupomFiscal() != null) {
            dados = Formatacao.ConvercaoDataPadrao(notaSaidaBean.getDataEmissaoCupomFiscal());
            String ano = dados.substring(8, 9);
            String mes = dados.substring(3, 5);
            return ano + mes;
        }
        return "";
    }
    
    public String validarTamanho(String dados){
        if (dados.length()>60){
            return dados.substring(0, 59);
        }else return dados;
    }
    
    public String verificarCodgioBarras(int idProduto){
//        CodigoBarrasController codigoBarrasController = new CodigoBarrasController();
//        List<CodigoBarras> listaCodigoBarras = codigoBarrasController.pesquisarProduto(idProduto);
//        if (listaCodigoBarras!=null){
//            if (listaCodigoBarras.size()>0){
//                return listaCodigoBarras.get(0).getBarras();
//            }
//        }
        return "";
    }
    
    public String gerarCodigoNumeroChaveNFe(String numero){
        String zeros = "00000000";
        String dados = zeros.substring(numero.length()) + numero;
        return dados;
    }

    public void finalizarBuscaTerminalCliente(Terminalcliente terminalCliente) {
        
        TerminalVendasFacade terminalVendasFacade = new TerminalVendasFacade();
        List<Terminalproduto>  listaTerminalProduto = null;
        try {
            listaTerminalProduto = terminalVendasFacade.consultaTerminalProduto(terminalCliente);
        } catch (SQLException ex) {
            Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
        EstoqueController estoqueController = new EstoqueController();
        for (int i=0;i<listaTerminalProduto.size();i++){
            Terminalproduto terminalProduto = listaTerminalProduto.get(i);
            NotaSaidaProdutoBean notaSaidaProdutoBean = new NotaSaidaProdutoBean();
            Produto produto = new Produto();
            ProdutoController produtoController = new ProdutoController();
            produto= produtoController.consultarProdutoid(terminalProduto.getProduto());
            if (produto!=null){
                Estoque estoque = estoqueController.consultarEstoque(produto.getIdProduto(), config.getEmpresa().getIdempresa());
                notaSaidaProdutoBean.setProduto(produto);
                notaSaidaProdutoBean.setQuantidade(terminalProduto.getQuantidade());
                notaSaidaProdutoBean.setValorDesconto(0.0f);
                notaSaidaProdutoBean.setValorUnitario(estoque.getValorCompra());
                notaSaidaProdutoBean.setValortotal(estoque.getValorCompra() * terminalProduto.getQuantidade());
                String aliquota = pesquisarAliquota(notaSaidaProdutoBean.getProduto().getAliquota());
                if (aliquota.equalsIgnoreCase("ST")){
                    Codigofiscal cf = (Codigofiscal) comSTjComboBox.getSelectedItem();
                    notaSaidaProdutoBean.setCfop(cf.getCfop());
                }else{
                    Codigofiscal cf = (Codigofiscal) semSTjComboBox.getSelectedItem();
                    notaSaidaProdutoBean.setCfop(cf.getCfop());
                }
                listaProdutoBean.add(notaSaidaProdutoBean);
            }
        }
            
        try {
            terminalVendasFacade.excluirTerminalCliente(terminalCliente);
        } catch (SQLException ex) {
            Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
        setModelProduto();
    }
    
    public void inlcluirProdutoContas(Object objeto) {
        List<NotaSaidaProdutoBean> lista = (List<NotaSaidaProdutoBean>) objeto;
        if (lista.size()>0){
            for(int i=0;i<lista.size();i++){
                NotaSaidaProdutoBean notaSaidaProdutoBean = lista.get(i);
                String aliquota = pesquisarAliquota(notaSaidaProdutoBean.getProduto().getAliquota());
                if (aliquota.equalsIgnoreCase("ST")){
                    Codigofiscal cf = (Codigofiscal) comSTjComboBox.getSelectedItem();
                    notaSaidaProdutoBean.setCfop(cf.getCfop());
                }else{
                    Codigofiscal cf = (Codigofiscal) semSTjComboBox.getSelectedItem();
                    notaSaidaProdutoBean.setCfop(cf.getCfop());
                }
                listaProdutoBean.add(notaSaidaProdutoBean);
            }
            setModelProduto();
        }
        
    }
    
    public void gerarNumeroNFe(){
        //Empresa emp = new Empresa();
        //emp = this.config.getEmpresa();
        NotaSaidaController notaSaidaController = new NotaSaidaController();
        int numeroNFe = notaSaidaController.consultarUltimaNotaEmitida();//emp.getNumeroNFe();
        if (numeroNFe>0){
            numeroNFe = numeroNFe + 1;
            numeroNFejTextField.setText(String.valueOf(numeroNFe));
            seriejTextField.setText(String.valueOf(this.config.getEmpresa().getSerieNFe()));
        }else {
            JOptionPane.showMessageDialog(rootPane, "Erro Gerar Numero Nota Fiscal");
        }
    }
    
//    public void salvarNumeroNFe(){
//        Empresa emp = new Empresa();
//        emp = this.config.getEmpresa();
//        emp.setNumeroNFe(Integer.parseInt(numeroNFejTextField.getText()));
//        EmpresaController empresaController = new EmpresaController();
//        emp = empresaController.salvar(emp);
//        this.config.setEmpresa(emp);
//    }
    
    
     public void calcularTotaisNotaFiscal(){
         notaSaidaBean.setValorDesconto(Formatacao.ConvercaoMonetariaDouble(valorDescontojTextField.getText()));
        calcularRateioDesconto();
        double valorTotalProdutos=0; 
        double valorTributos=0;
        double totalDesconto=0;
        double valorCalcualdo=0;
        IbptController ibptController = new IbptController();
        for(int i=0;i<listaProdutoBean.size();i++){
            valorTotalProdutos+=listaProdutoBean.get(i).getValortotal();
            Ibpt ibpt = new Ibpt();
            ibpt = ibptController.cunsultarIbpt(listaProdutoBean.get(i).getProduto().getNcm());
            double valor =0.0;
            if (ibpt!=null){
                valor = listaProdutoBean.get(i).getValortotal()*(ibpt.getAliquotaImposto()/100);
            }else {
                valor = listaProdutoBean.get(i).getValortotal()*(26.75/100);
            }
            listaProdutoBean.get(i).setValorTributo(valor);
            valorTributos+=listaProdutoBean.get(i).getValorTributo();
            if (notaSaidaBean.getPercentualDesconto()>0){
                double valorDesconto =  (listaProdutoBean.get(i).getValortotal() * notaSaidaBean.getPercentualDesconto());
                totalDesconto = totalDesconto + valorDesconto;
                if (totalDesconto> notaSaidaBean.getValorDesconto()){
                    valorDesconto = notaSaidaBean.getValorDesconto() - (totalDesconto - valorDesconto);
                }
                listaProdutoBean.get(i).setValorDesconto(valorDesconto);
                valorCalcualdo = valorCalcualdo + listaProdutoBean.get(i).getValorDesconto();
            }
        }
        notaSaidaBean.setTotalValoProdutos(valorTotalProdutos);
        notaSaidaBean.setValorNota(valorTotalProdutos - notaSaidaBean.getValorDesconto());
        notaSaidaBean.setTotalBaseICMS(0);
        notaSaidaBean.setTotalValorICMS(0);
        notaSaidaBean.setTotalTributios(valorTributos);
        totalProdutojTextField.setText(Formatacao.foramtarDoubleString(notaSaidaBean.getTotalValoProdutos()));
        totalNotajTextField.setText(Formatacao.foramtarDoubleString(notaSaidaBean.getValorNota())); 
        valorTributosjTextField.setText(Formatacao.foramtarDoubleString(notaSaidaBean.getTotalTributios()));
    }
     
     
   public String validarDadosNFe(){
       String erro=null;
      if (fornecedor.getMunicipios()==0){
           erro = "Falta código Municipio";
           return erro;
       }
       if (emailjTextField.getText().length()==0){
           erro = "Email inválido";
           return erro;
       }
       for(int i=0;i<listaProdutoBean.size();i++){
           if (listaProdutoBean.get(i).getProduto().getNcm().equalsIgnoreCase("0")){
               erro="Lista de Produtos possui NCM inválido";
               return erro;
           }
       }
       return erro;
   }
   
   public void gravarNotaSaida(){
       NotaSaida notaSaida = new NotaSaida();
       notaSaida.setIdfornecedor(fornecedor.getIdfornecedor());
       notaSaida.setIdcliente(0);
       notaSaida.setTipo("D");
       notaSaida.setDataEmissao(notaSaidaBean.getDataEmissao());
       notaSaida.setEmpresa(this.config.getEmpresa().getIdempresa());
       notaSaida.setNumero(Integer.parseInt(notaSaidaBean.getNuemro()));
       notaSaida.setSerie(Integer.parseInt(notaSaidaBean.getSerie1()));
       notaSaida.setSituacao("AUTORIZADA");
       notaSaida.setNomeArquivoXML(this.arquivoXML.getName());
       notaSaida.setUsuario(this.usuarioLogado.getUsuario().getIdusuarios());
       Double valor = notaSaidaBean.getValorNota();
       notaSaida.setValorNotaFiscal(valor.floatValue());
       valor = notaSaidaBean.getTotalValoProdutos();
       notaSaida.setValorProdutos(valor.floatValue());
        try {
            notaSaida.setXml(carregarXML());
        } catch (IOException ex) {
            Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
        notaSaida.setCahveAutorizacao(chaveAutorizacao);
        NotaSaidaController notaSaidaController = new NotaSaidaController();
        notaSaida = notaSaidaController.salvarNotaSaida(notaSaida);
   }
   
    public byte[] carregarXML() throws IOException {
        File file = this.arquivoXML;
        InputStream is = new FileInputStream(file);
        byte[] xml = new byte[(int) file.length()];
        int offset = 0;
        int numRead = 0;
        while (offset < xml.length
                && (numRead = is.read(xml, offset, xml.length - offset)) >= 0) {
            offset += numRead;
        }
        return xml;
    }

    public void carregarArquivoXMLLocalizado(File file) {
        if (file != null) {
            this.arquivoXML = file;
            this.notaCarregarda = true;
            if (notaCarregarda) {
                gravarNotaSaida();
                enviarEmailNFeCliente();
                imprimirDANFE();
            }
            this.telaConsulta.setModel();
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro carregar Arquivo XML");
            this.notaCarregarda = false;
        }
    }
    
    public void enviarEmailNFeCliente(){
        String cEmailDestino = emailjTextField.getText();
        String cArqXML = this.config.getCaminhoNFe() + this.arquivoXML.getName();
        String cEnviaPDF = "1";
        String cAssunto = "Segue em Anexo NF-e da empresa " + this.config.getEmpresa().getRazaoSocial();
        String cEmailsCopias = "angelacLenz@ig.com.br;jizidoro@globo.com";
        String texto = "NFe.EnviarEmail(" + cEmailDestino+ "," + 
                cArqXML + "," + cEnviaPDF + "," + cAssunto + "," +
                        cEmailsCopias+")";
        gerarArquivoAcbr(texto);
    }
    
    public void imprimirDANFE(){
        String cArqXML = this.config.getCaminhoNFe() + this.arquivoXML.getName();
        String texto = "NFe.ImprimirDANFE("+ cArqXML + ")";
        gerarArquivoAcbr(texto);
    }

    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void filtrarNotaSaida(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void consultarCliente(Cliente cliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void consultaFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
        if (fornecedor!=null){
            nomejTextField.setText(fornecedor.getRazaoSocial());
            cpfjFormattedTextField.setText(fornecedor.getCnpj());
            rgjTextField.setText(fornecedor.getIe());
            foneFixojFormattedTextField.setText(fornecedor.getTelefone());
            emailjTextField.setText(fornecedor.getEmail());
            logradourojTextFiel.setText(fornecedor.getEndereco());
            complementojTextField.setText(fornecedor.getComplemento());
            bairrojTextField.setText(fornecedor.getBairro());
            cidadejTextField.setText(fornecedor.getCidade());
            cepjFormattedTextField.setText(fornecedor.getCep());
            estadojComboBox.setSelectedItem(fornecedor.getUf());
            if (emailjTextField.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "Email é obrigatório");
            }
        }
    }

    public void carregarFaturas(FaturaBean fatura, List<DuplicataBean> listaDuplicata) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    class RemindTask extends TimerTask {

        public void run() {
            try {
                lerArquivoSaidaAcbr();
            } catch (IOException ex) {
                Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void carregarCahveAutorizacao(BufferedReader leitor){
        String linha=null;
        for(int i=0;i<1000;i++){
            try {
                linha = leitor.readLine();
                String dados = linha.substring(0, 5);
                if (dados.equalsIgnoreCase("ChNFe")){
                    chaveAutorizacao = linha.substring(6);
                    i=5000;
                }
            } catch (IOException ex) {
                Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
    }
    
    public boolean verificarRetornoNFe(BufferedReader leitor) {
        String linha = null;
        for (int i = 0; i < 1000; i++) {
            try {
                linha = leitor.readLine();
                String dados = "";
                if (linha != null) {
                    if (linha.length() > 8) {
                        dados = linha.substring(0, 7);
                    } else {
                        dados = linha.substring(0);
                    }
                } else {
                    linha = " ";
                }
                if (dados.equalsIgnoreCase("XMotivo")) {
                    String motivo = linha.substring(8);
                    if (motivo.equalsIgnoreCase("Autorizado o uso da NF-e")) {
                        JOptionPane.showMessageDialog(rootPane, motivo);
                        i = 5000;
                        return true;
                    }else {
                        if (!motivo.equalsIgnoreCase("Lote recebido com sucesso")){
                            JOptionPane.showMessageDialog(rootPane, motivo);
                            i = 5000;
                        }
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(FrmEmitirNotaSaidaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }

    public String consultarCodgioMunicipio(int idMunicipio) {
        MunicipiosController municipiosController = new MunicipiosController();
        Municipios municipios = new Municipios();
        municipios = municipiosController.getMunicipio(idMunicipio);
        if (municipios != null) {
            return municipios.getCodigo();
        } else {
            return "0";
        }
    }

    
    
    
    
    public void calcularRateioDesconto(){
        Float desconto = Formatacao.formatarStringfloat(valorDescontojTextField.getText());
        Float valorTotal = Formatacao.formatarStringfloat(totalNotajTextField.getText());
        Float perDesconto= (desconto*100) / valorTotal;
        perDesconto = perDesconto/100;
        String vDesconto="";
        if (perDesconto>0){
            vDesconto = Formatacao.foramtarFloatString(perDesconto);
            perDesconto = Formatacao.formatarStringfloat(vDesconto);
        }
        
        notaSaidaBean.setPercentualDesconto(perDesconto);
    }
    
    public void apagarArquivoSaidaAcbr() throws IOException {
        File arqSaida = new File(this.config.getCaminhoAcbr() + "sainfe.txt");
        if (arqSaida.exists()) {
            arqSaida.delete();
        }
        File folder = new File(this.config.getCaminhoNFe());
        if (folder.isDirectory()) {
            File[] sun = folder.listFiles();
            for (File toDelete : sun) {
                toDelete.delete();
            }
        }
    }
    
    public String pesquisarAliquota(int idAliquota){
        AliquotaController aliquotaController = new AliquotaController();
        Aliquota aliquota = aliquotaController.buscarAliquotaid(idAliquota);
        if (aliquota!=null){
            return aliquota.getDescricao();
        }
        return "";
    }
    
}