/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.NotaSaida;

import Regras.NotaSaidaController;
import controler.Config;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Wolverine
 */
public class FrmInutilizarNFe extends javax.swing.JFrame {
    
    private Config config;

    /**
     * Creates new form FrmInutilizarNFe
     */
    public FrmInutilizarNFe(Config config) {
        this.config = config;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        motivojTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        salvarjButton2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inutilizar NF-e");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nº NF-e");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton1.setText("Validar");
        jButton1.setToolTipText("Validar número da NF-e");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Motivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addComponent(motivojTextField))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motivojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarjButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        salvarjButton2.setText("Confirmar");
        salvarjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salvarjButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        salvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButton2SalvarCadastroAssociado(evt);
            }
        });
        jPanel4.add(salvarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2FecharCadastro(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 190, 250, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButton2SalvarCadastroAssociado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButton2SalvarCadastroAssociado
        if (motivojTextField.getText().length() > 0) {
            gerarArquivoInutilzacao();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencher o motivo da inutilização");
        }
    }//GEN-LAST:event_salvarjButton2SalvarCadastroAssociado

    private void jButton2FecharCadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2FecharCadastro
        this.dispose();
    }//GEN-LAST:event_jButton2FecharCadastro

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (numerojTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane,"Nenhum número informado");
        }else {
            int numero = Integer.parseInt(numerojTextField.getText());
            NotaSaidaController notaSaidaController = new NotaSaidaController();
            if (notaSaidaController.validarNumero(numero)){
                JOptionPane.showMessageDialog(rootPane, "Número pode ser inutilizado");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Número não pode ser inutilizado");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField motivojTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JButton salvarjButton2;
    // End of variables declaration//GEN-END:variables

    public void gerarArquivoInutilzacao(){
        //InutilizarNFe( cCNPJ, cJustificativa, nAno, nModelo, nSerie, nNumInicial, nNumFinal
        String texto = retirarPontos(config.getEmpresa().getCnpj());
        texto = texto + "," + motivojTextField.getText();
        texto = texto + "," +  anoCorrente();
        texto = texto + "," + "55,1";
        texto = texto + "," + numerojTextField.getText() + "," + numerojTextField.getText();
        texto = "NFe.InutilizarNFe(" + texto + ")";
        try {
            FileWriter acbr = new FileWriter(new File(this.config.getCaminhoAcbr() + "ENTNFE.txt"));
            acbr.write(texto);
            acbr.close();
        } catch (IOException ex) {
            Logger.getLogger(FrmEmitirNotaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Timer timer = new Timer();
        timer.schedule(new RemindTask(), 5 * 1000);
        //imprimirInutilizacao();
    }
    
    public void imprimirInutilizacao(){
        String texto = "NFe.ImprimirInutilizacao()";
        try {
            FileWriter acbr = new FileWriter(new File(this.config.getCaminhoAcbr() + "ENTNFE.txt"));
            acbr.write(texto);
            acbr.close();
        } catch (IOException ex) {
            Logger.getLogger(FrmEmitirNotaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Timer timer = new Timer();
        timer.schedule(new RemindTask(), 5 * 1000);
    }
    
    class RemindTask extends TimerTask {

        public void run() {
            try {
                lerArquivoSaidaAcbr();
            } catch (IOException ex) {
                Logger.getLogger(FrmConsultaNotaSaida.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void lerArquivoSaidaAcbr() throws IOException{
       File arqSaida = new File(this.config.getCaminhoAcbr() + "sainfe.txt");
        String xml = null;
        while (!arqSaida.exists()) {
            arqSaida = new File(this.config.getCaminhoAcbr() + "sainfe.txt");
        }
        if (!arqSaida.exists()){
            JOptionPane.showMessageDialog(rootPane, "Arquivo de Saída não Localizado");
        }
        FileReader sainfe = new FileReader(arqSaida);
        BufferedReader leitor = new BufferedReader(sainfe);
        xml = leitor.readLine();
        String linha = xml.substring(0, 2);
        if (linha.equalsIgnoreCase("OK")) {
            JOptionPane.showMessageDialog(rootPane, "Número Inutilizado com Sucesso");
        }else {
            JOptionPane.showMessageDialog(rootPane, "Erro oa gerar Nota Fiscal");
        }
        leitor.close();
    }
    
    public String anoCorrente(){
        Calendar cal = Calendar.getInstance();
        int ano = cal.get(Calendar.YEAR);
        ano = ano - 2000;
        return String.valueOf(ano);
    }
    
    public String retirarPontos(String dado){
        String formatado = "";
        char c = ' ';
        if (dado != null) {
            for (int i = 0; i < dado.length(); i++) {
                c = dado.charAt(i);
                if ((c != '.') && (c != ',') && (c != '-') && (c != '/') && (c != '(') && (c != ')')) {
                    formatado += c;
                }
            }
        }
        return formatado;
    }
}