/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Produtos;

import Regras.FornecedorController;
import controler.Config;
import controler.relatoriosJasper;
import facade.AliquotaFacade;
import facade.GrupoProdutoFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Aliquota;
import model.Fornecedor;
import model.Grupoproduto;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.RelatorioVendas.FrmRelatorioVenda;

/**
 *
 * @author Wolverine
 */
public class FrmRelatorioAliquotas extends javax.swing.JFrame implements IRelatorioAliquota{
    
    private Grupoproduto grupoProduto;
    private Fornecedor fornecedor;
    private Aliquota aliquota;
    private Config config;
    /**
     * Creates new form FrmRelatorioAliquotas
     */
    public FrmRelatorioAliquotas(Config config) {
        initComponents();
        this.config = config;
        preencherAliquota();
        preencherGrupoProduto();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public final void preencherGrupoProduto(){
        GrupoProdutoFacade grupoProdutoFacade = new GrupoProdutoFacade();
        grupojComboBox.addItem("Todos");
        try {
            List<Grupoproduto> listaGrupoProduto = grupoProdutoFacade.listarGrupoProduto();
            for(int i=0;i<listaGrupoProduto.size();i++){
                grupojComboBox.addItem(listaGrupoProduto.get(i));
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmRelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void consultarFornecedor(Fornecedor fornecedor){
        this.fornecedor = fornecedor;
        codigoFornecedorjTextField.setText(String.valueOf(this.fornecedor.getIdfornecedor()));
        razaoSocialjTextField.setText(this.fornecedor.getRazaoSocial());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aliquotajComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        grupojComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        codigoFornecedorjTextField = new javax.swing.JTextField();
        consultaFornecedorjButton = new javax.swing.JButton();
        razaoSocialjTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório por Aliquotas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Aliquota");

        aliquotajComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aliquotajComboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Grupo");

        grupojComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupojComboBoxItemStateChanged(evt);
            }
        });

        jLabel4.setText("Fornecedor");

        codigoFornecedorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoFornecedorjTextFieldKeyPressed(evt);
            }
        });

        consultaFornecedorjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        consultaFornecedorjButton.setToolTipText("Consultar Fornecedor");
        consultaFornecedorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFornecedorjButtonActionPerformed(evt);
            }
        });

        razaoSocialjTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grupojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(aliquotajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoFornecedorjTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaFornecedorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(razaoSocialjTextField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aliquotajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoFornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(consultaFornecedorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fechar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFornecedorjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoFornecedorjTextFieldKeyPressed
        FornecedorController fornecedorController = new FornecedorController();
        this.fornecedor = fornecedorController.consultarFornecedor(Integer.parseInt(codigoFornecedorjTextField.getText()));
        consultarFornecedor(fornecedor);
    }//GEN-LAST:event_codigoFornecedorjTextFieldKeyPressed

    private void consultaFornecedorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFornecedorjButtonActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_consultaFornecedorjButtonActionPerformed

    private void aliquotajComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aliquotajComboBoxItemStateChanged
        Object obj = aliquotajComboBox.getSelectedItem();
        if (obj!=null){
            if (obj instanceof Aliquota){
                this.aliquota = (Aliquota) obj;
            }else {
                this.aliquota=null;
            }
        }
    }//GEN-LAST:event_aliquotajComboBoxItemStateChanged

    private void grupojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupojComboBoxItemStateChanged
        Object obj = grupojComboBox.getSelectedItem();
        if (obj!=null){
            if (obj instanceof Grupoproduto){
                this.grupoProduto = (Grupoproduto) obj;
            }else {
                grupoProduto=null;
            }
        }
    }//GEN-LAST:event_grupojComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = "SELECT * FROM viewrelatorioaliquota where ";
        boolean marcacao=false;
        if (this.aliquota!=null){
            sql = sql + " idaliquota=" + aliquota.getIdaliquota();
            marcacao=true;
        }
        if (grupoProduto!=null){
            if (marcacao){
                sql = sql + " and ";
            }
            sql = sql + " idgrupoproduto=" + grupoProduto.getIdgrupoProduto();
        }
        if (fornecedor!=null){
            if (marcacao){
                sql = sql + " and ";
            }
            sql = sql + " idfornecedor=" + fornecedor.getIdfornecedor();
        }
        sql = sql + " order by descricao";
        String url = ("telas/Produtos/reportAliquota.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("sql", sql);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aliquotajComboBox;
    private javax.swing.JTextField codigoFornecedorjTextField;
    private javax.swing.JButton consultaFornecedorjButton;
    private javax.swing.JComboBox grupojComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField razaoSocialjTextField;
    // End of variables declaration//GEN-END:variables

    public final void preencherAliquota(){
        AliquotaFacade aliquotaFacade = new AliquotaFacade();
        aliquotajComboBox.addItem("Todas");
        try {
            List<Aliquota> listaAliquota = aliquotaFacade.buscarAliquota();
            for (int i=0;i<listaAliquota.size();i++){
                aliquotajComboBox.addItem(listaAliquota.get(i));
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
        codigoFornecedorjTextField.setText(String.valueOf(this.fornecedor.getIdfornecedor()));
        razaoSocialjTextField.setText(this.fornecedor.getRazaoSocial());
    }

}
