/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasReceber;

import Regras.ClienteController;
import Regras.ContasReceberController;
import Regras.Formatacao;
import Regras.VendedorController;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import controler.relatoriosJasper;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Banco;
import model.Cliente;
import model.Contasreceber;
import model.Contasreceberpagamento;
import model.Faturasreceber;
import model.Vendedor;


/**
 *
 * @author wolverine
 */
public class FrmAlterarFatura extends javax.swing.JFrame {

    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Faturasreceber fatura;
    private Config config;
    private double valorFatura;
    private List<Contasreceber> listaParcelas;
    /**
     * Creates new form FrmAlterarFatura
     */
    public FrmAlterarFatura(Config config, Faturasreceber fatura) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.fatura = fatura;
        this.valorFatura =0;
        this.config = config;
        initComponents();
        carregarDadosdaFatura();
        carregarListaParcelas();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroFaturajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeClientejTextField = new javax.swing.JTextField();
        diaPagamentojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        formaPagamentojTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataFaturajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel5 = new javax.swing.JLabel();
    notaFiscaljTextField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    dataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel7 = new javax.swing.JLabel();
valorDescontojTextField = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
dataDescontojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel9 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    dataParcela01jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel10 = new javax.swing.JLabel();
valorParcela01jTextField = new javax.swing.JTextField();
jLabel11 = new javax.swing.JLabel();
dataParcela02jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    valorParcela02jTextField = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    dataParcela03jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
valorParcela03jTextField = new javax.swing.JTextField();
jLabel15 = new javax.swing.JLabel();
dataParcela04jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel16 = new javax.swing.JLabel();
    valorParcela04jTextField = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    informacoesjTextField = new javax.swing.JTextField();
    valorCreditojTextField = new javax.swing.JTextField();
    valorFaturajTextField = new javax.swing.JTextField();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    marcarContajButton = new javax.swing.JButton();
    desmarcarContajButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Fatura - Alteração");

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Nº Fatura");

    numeroFaturajTextField.setEditable(false);

    jLabel2.setText("Cliente");

    nomeClientejTextField.setEditable(false);

    diaPagamentojTextField.setEditable(false);

    jLabel3.setText("Dia Pagto");

    formaPagamentojTextField.setEditable(false);

    jLabel4.setText("Forma Pagto");

    jLabel5.setText("Data Fatura");

    jLabel6.setText("Nº Nota Fiscal");

    jLabel7.setText("Data Vencimento");

    valorDescontojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorDescontojTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            valorDescontojTextFieldActionPerformed(evt);
        }
    });
    valorDescontojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldKeyReleased(evt);
        }
    });

    jLabel8.setText("Valor Desconto");

    jLabel9.setText("Data Desconto");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(numeroFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(diaPagamentojTextField)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(formaPagamentojTextField)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataFaturajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(notaFiscaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(valorDescontojTextField))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataDescontojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(numeroFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(diaPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(formaPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(3, 3, 3)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataFaturajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(notaFiscaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorDescontojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataDescontojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel10.setText("Data Parcela 01");

    valorParcela01jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela01jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela01jTextFieldKeyReleased(evt);
        }
    });

    jLabel11.setText("Valor Parcela 01");

    valorParcela02jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela02jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela02jTextFieldKeyReleased(evt);
        }
    });

    jLabel12.setText("Valor Parcela 02");

    jLabel13.setText("Data Parcela 02");

    jLabel14.setText("Data Parcela 03");

    valorParcela03jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela03jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela03jTextFieldKeyReleased(evt);
        }
    });

    jLabel15.setText("Valor Parcela 03");

    jLabel16.setText("Data Parcela 04");

    valorParcela04jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela04jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela04jTextFieldKeyReleased(evt);
        }
    });

    jLabel17.setText("Valor Parcela 04");

    jLabel18.setText("Informações de Cobrança e Pagamento");

    valorCreditojTextField.setEditable(false);
    valorCreditojTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    valorCreditojTextField.setForeground(new java.awt.Color(255, 0, 0));
    valorCreditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    valorFaturajTextField.setEditable(false);
    valorFaturajTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    valorFaturajTextField.setForeground(new java.awt.Color(0, 0, 255));
    valorFaturajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel19.setText("Valor Creditos");

    jLabel20.setText("Valor da Fatura");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela01jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(valorParcela01jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela02jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(valorParcela02jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela03jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(valorParcela03jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela04jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(valorParcela04jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(informacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(valorFaturajTextField))))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela02jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela02jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela01jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela01jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela04jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela04jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela03jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela03jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(jLabel19)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(informacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    marcarContajButton.setText("Confirmar");
    marcarContajButton.setToolTipText("Marca conta para gerar Fatura");
    marcarContajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            marcarContajButtonActionPerformed(evt);
        }
    });

    desmarcarContajButton.setText("Fechar");
    desmarcarContajButton.setToolTipText("Desmarcar Contas ");
    desmarcarContajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            desmarcarContajButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(149, Short.MAX_VALUE)
            .addComponent(marcarContajButton)
            .addGap(69, 69, 69)
            .addComponent(desmarcarContajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(158, 158, 158))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(marcarContajButton)
                .addComponent(desmarcarContajButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 607, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap()))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 366, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorDescontojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDescontojTextFieldActionPerformed

    private void valorDescontojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (valorDescontojTextField.getText().length()>0){
                double valorDesconto = Formatacao.ConvercaoMonetariaDouble(valorDescontojTextField.getText());
                valorFatura = valorFatura - valorDesconto;
                valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
            }
        }
    }//GEN-LAST:event_valorDescontojTextFieldKeyPressed

    private void valorDescontojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldKeyReleased
        valorDescontojTextField.setText(Formatacao.decinalValorMonetario(valorDescontojTextField.getText()));
    }//GEN-LAST:event_valorDescontojTextFieldKeyReleased

    private void valorParcela01jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela01jTextFieldKeyReleased
        valorParcela01jTextField.setText(Formatacao.decinalValorMonetario(valorParcela01jTextField.getText()));
    }//GEN-LAST:event_valorParcela01jTextFieldKeyReleased

    private void valorParcela02jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela02jTextFieldKeyReleased
        valorParcela02jTextField.setText(Formatacao.decinalValorMonetario(valorParcela02jTextField.getText()));
    }//GEN-LAST:event_valorParcela02jTextFieldKeyReleased

    private void valorParcela03jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela03jTextFieldKeyReleased
        valorParcela03jTextField.setText(Formatacao.decinalValorMonetario(valorParcela03jTextField.getText()));
    }//GEN-LAST:event_valorParcela03jTextFieldKeyReleased

    private void valorParcela04jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela04jTextFieldKeyReleased
        valorParcela04jTextField.setText(Formatacao.decinalValorMonetario(valorParcela04jTextField.getText()));
    }//GEN-LAST:event_valorParcela04jTextFieldKeyReleased

    private void marcarContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarContajButtonActionPerformed
         if (fatura.getValorFatura()>0){
            if (dataParcela01jDateChooser.getDate()==null){
                dataParcela01jDateChooser.setDate(dataVencimentojDateChooser.getDate());
                valorParcela01jTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
            }
            int idFatura = gerarFatura();
            gerarRelatorio(idFatura, Formatacao.valorPorExtenso(fatura.getValorFatura()));
            JOptionPane.showMessageDialog(rootPane, "Fatura Gerada com Sucesso");
            this.dispose();
        }
    }//GEN-LAST:event_marcarContajButtonActionPerformed

    private void desmarcarContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desmarcarContajButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_desmarcarContajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataDescontojDateChooser;
    private com.toedter.calendar.JDateChooser dataFaturajDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela01jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela02jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela03jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela04jDateChooser;
    private com.toedter.calendar.JDateChooser dataVencimentojDateChooser;
    private javax.swing.JButton desmarcarContajButton;
    private javax.swing.JTextField diaPagamentojTextField;
    private javax.swing.JTextField formaPagamentojTextField;
    private javax.swing.JTextField informacoesjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton marcarContajButton;
    private javax.swing.JTextField nomeClientejTextField;
    private javax.swing.JTextField notaFiscaljTextField;
    private javax.swing.JTextField numeroFaturajTextField;
    private javax.swing.JTextField valorCreditojTextField;
    private javax.swing.JTextField valorDescontojTextField;
    private javax.swing.JTextField valorFaturajTextField;
    private javax.swing.JTextField valorParcela01jTextField;
    private javax.swing.JTextField valorParcela02jTextField;
    private javax.swing.JTextField valorParcela03jTextField;
    private javax.swing.JTextField valorParcela04jTextField;
    // End of variables declaration//GEN-END:variables

    public void carregarDadosdaFatura(){
        numeroFaturajTextField.setText(fatura.getNumeroFatura());
        ClienteController clienteController = new ClienteController();
        Cliente cliente = clienteController.consultarClienteId(fatura.getCliente());
        nomeClientejTextField.setText(cliente.getNome());
        dataFaturajDateChooser.setDate(fatura.getDataLancamento());
        numeroFaturajTextField.setText(fatura.getNumeroNotaFiscal());
        dataVencimentojDateChooser.setDate(fatura.getDataVencimento());
        valorDescontojTextField.setText(Formatacao.foramtarDoubleString(fatura.getValorDesconto()));
        dataDescontojDateChooser.setDate(fatura.getDataDesconto());
        informacoesjTextField.setText(fatura.getInstrucoes());
        valorFaturajTextField.setText(Formatacao.foramtarDoubleString(fatura.getValorFatura()));
    }
    
    public void carregarListaParcelas(){
        ContasReceberController contasReceberController = new ContasReceberController();
        listaParcelas = contasReceberController.listarFaturaReceberParcelas(this.fatura.getIdFaturasReceber());
        if (listaParcelas!=null){
            for(int i=0;i<listaParcelas.size();i++){
                if (i==0){
                    dataParcela01jDateChooser.setDate(listaParcelas.get(i).getDataVencimento());
                    valorParcela01jTextField.setText(Formatacao.foramtarDoubleString(listaParcelas.get(i).getValorConta()));
                }else if (i==1){
                    dataParcela02jDateChooser.setDate(listaParcelas.get(i).getDataVencimento());
                    valorParcela02jTextField.setText(Formatacao.foramtarDoubleString(listaParcelas.get(i).getValorConta()));
                }else if (i==2){
                    dataParcela03jDateChooser.setDate(listaParcelas.get(i).getDataVencimento());
                    valorParcela03jTextField.setText(Formatacao.foramtarDoubleString(listaParcelas.get(i).getValorConta()));
                }else if (i==3){
                    dataParcela04jDateChooser.setDate(listaParcelas.get(i).getDataVencimento());
                    valorParcela04jTextField.setText(Formatacao.foramtarDoubleString(listaParcelas.get(i).getValorConta()));
                }
            }
        }
        
    }
    
    
    public int gerarFatura(){
        apagarParcelas();
        fatura.setCliente(fatura.getCliente());
        fatura.setContasreceberpagamento(1);
        fatura.setDataLancamento(dataFaturajDateChooser.getDate());
        fatura.setDataVencimento(dataVencimentojDateChooser.getDate());
        fatura.setEmpresa(this.config.getEmpresa().getIdempresa());
        fatura.setInstrucoes(informacoesjTextField.getText());
        fatura.setNumeroNotaFiscal(notaFiscaljTextField.getText());
        fatura.setNumeroParcelas(verifcarNumeroParcelas());
        if (dataDescontojDateChooser.getDate()!=null){
            fatura.setDataDesconto(dataDescontojDateChooser.getDate());
        }
        if (valorDescontojTextField.getText().length()>0){
            fatura.setValorDesconto(Formatacao.formatarStringDouble(valorDescontojTextField.getText()));
        }
        if (dataParcela01jDateChooser.getDate()!=null){
            fatura.setDataParcela01(dataParcela01jDateChooser.getDate());
        }
        if (valorParcela01jTextField.getText().length()>0){
            fatura.setValorParcela01(Formatacao.formatarStringDouble(valorParcela01jTextField.getText()));
        }
        if (dataParcela02jDateChooser.getDate()!=null){
            fatura.setDataParcela02(dataParcela02jDateChooser.getDate());
        }
        if (valorParcela02jTextField.getText().length()>0){
            fatura.setValorParcela02(Formatacao.formatarStringDouble(valorParcela02jTextField.getText()));
        }
        if (dataParcela03jDateChooser.getDate()!=null){
            fatura.setDataParcela03(dataParcela03jDateChooser.getDate());
        }
        if (valorParcela03jTextField.getText().length()>0){
            fatura.setValorParcela03(Formatacao.formatarStringDouble(valorParcela03jTextField.getText()));
        }
        if (dataParcela04jDateChooser.getDate()!=null){
            fatura.setDataParcela04(dataParcela04jDateChooser.getDate());
        }
        if (valorParcela04jTextField.getText().length()>0){
            fatura.setValorParcela04(Formatacao.formatarStringDouble(valorParcela04jTextField.getText()));
        }
        
        
        ContasReceberController contasReceberController = new ContasReceberController();
        fatura = contasReceberController.salvarFatura(fatura);
        verifcarParcelasSalvar();

        
       return fatura.getIdFaturasReceber(); 
    }
    
    public void verifcarParcelasSalvar(){
        String numeroFatura = fatura.getNumeroFatura();
        if (dataParcela01jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getIdFaturasReceber(), dataParcela01jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela01jTextField.getText()), 
                    numeroFatura+"01", 01);
        }
        if (dataParcela02jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getIdFaturasReceber(), dataParcela02jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela02jTextField.getText()), 
                    numeroFatura+"02", 02);
        }
        if (dataParcela03jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getIdFaturasReceber(), dataParcela03jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela03jTextField.getText()), 
                    numeroFatura+"03", 03);
        }
        if (dataParcela04jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getIdFaturasReceber(), dataParcela04jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela04jTextField.getText()), 
                    numeroFatura+"04", 04);
        }
    }
    
    public void salvarParcelas(int numeroFatura, Date dataVencimento, double valorParcela, String numeroDocumento, int numeroParcela){
        ContasReceberController contasReceberController = new ContasReceberController();
        Contasreceberpagamento contasreceberpagamento = contasReceberController.consultarContaReceberPagamento(1);
        VendedorController vendedorController = new VendedorController();
        Vendedor vendedor = vendedorController.consultarVendedorId(1);
        Contasreceber parcela = new Contasreceber();
        ClienteController clienteController = new ClienteController();
        parcela.setCliente(clienteController.consultarClienteId(fatura.getCliente()));
        parcela.setContasreceberpagamento(contasreceberpagamento);
        parcela.setDataLancamento(fatura.getDataLancamento());
        parcela.setNumeroFatura(fatura.getIdFaturasReceber());
        parcela.setDataVencimento(dataVencimento);
        parcela.setNumeroDocumento(numeroDocumento);
        parcela.setNumeroParcelas(numeroParcela);
        parcela.setValorConta(valorParcela);
        parcela.setEmpresa(this.config.getEmpresa());
        parcela.setVendedor(vendedor);
        parcela.setTipo("P");
        contasReceberController.salvarContasReceber(parcela);
    }    
    
    public int verifcarNumeroParcelas(){
        int numeroParcelas = 0;
        if (dataParcela01jDateChooser.getDate()!=null){
            numeroParcelas = 1;
        }else return numeroParcelas;
        if (dataParcela02jDateChooser.getDate()!=null){
            numeroParcelas = 2;
        }else return numeroParcelas;
        if (dataParcela03jDateChooser.getDate()!=null){
            numeroParcelas = 3;
        }else return numeroParcelas;
        if (dataParcela04jDateChooser.getDate()!=null){
            numeroParcelas = 4;
        }else return numeroParcelas;
        return numeroParcelas;
    }
    
    public void gerarRelatorio(int idFatura, String valorExtenso){
        String url = ("telas/ContasReceber/Relatorios/faturaReceber.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("idFatura", idFatura);
            parameters.put("valorExtenso", valorExtenso);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }
    
    public void apagarParcelas(){
        if (listaParcelas!=null){
            ContasReceberController contasReceberController = new ContasReceberController();
            for(int i=0;i<listaParcelas.size();i++){
                contasReceberController.excluirContasReceber(listaParcelas.get(i));
            }
        }
    }

}
