/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasReceber;

import Regras.ContasReceberController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Contasreceber;
import model.Faturasreceber;

/**
 *
 * @author Wolverine
 */
public class FrmConusltaContasFatura extends javax.swing.JFrame {
    
    private List<Contasreceber> listaContas;
    private ConsultaContasReceberTableModel modelContas;
   

    /**
     * Creates new form FrmConusltaContasFatura
     */
    public FrmConusltaContasFatura(String numeroFatura) {
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelContas(numeroFatura);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        vencidasjScrollPane = new javax.swing.JScrollPane();
        contasjTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas da Fatura");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        contasjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº Conta", "Data Conta", "Cedente", "Data Vencimento", "Valor Conta"
            }
        ));
        contasjTable.getTableHeader().setReorderingAllowed(false);
        contasjTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        contasjTable.getColumnModel().getColumn(1).setPreferredWidth(30);
        contasjTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        contasjTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        contasjTable.getColumnModel().getColumn(4).setPreferredWidth(30);
        vencidasjScrollPane.setViewportView(contasjTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vencidasjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vencidasjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(203, 203, 203))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contasjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane vencidasjScrollPane;
    // End of variables declaration//GEN-END:variables

    private void carregarModelContas(String numeroFatura){
        ContasReceberController contasReceberController = new ContasReceberController();
        String sql = "Select f from Faturasreceber f where idFaturasReceber=" + Integer.valueOf(numeroFatura);
        List<Faturasreceber> listaFatura = contasReceberController.listarFaturas(sql);
        if ((listaFatura!=null) && (listaFatura.size()>0)){
            listaContas = new ArrayList<Contasreceber>();
            sql= "select c from Contasreceber c where c.numeroFaturaGerada='" + listaFatura.get(0).getNumeroFatura()+ "' and c.tipo='C' order by c.numeroDocumento";
            listaContas = contasReceberController.listarContas(sql);
        }
        
        
       
        
        if (listaContas==null){
            listaContas = new ArrayList<Contasreceber>();
        }
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelContas = new ConsultaContasReceberTableModel(listaContas);
        contasjTable.setModel(modelContas);
        contasjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        contasjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        contasjTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        contasjTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        contasjTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        contasjTable.repaint();
    }
    

}
