/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasReceber;

import Regras.ContasReceberController;
import Regras.Formatacao;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Contasreceber;
import model.Contasreceberforma;
import model.Contasreceberpagamento;

/**
 *
 * @author Wolverine
 */
public class FrmConsultarContasRecebidas extends javax.swing.JFrame {

    
    Config config;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    
    private ConsultaContasReceberTableModel modelContas;
    private PagamentoTableModel modelPagamento;
    private FormaPagamentoTableModel modelForma;
    
    private List<Contasreceber> listaContas;
    private List<Contasreceberforma> listaForma;
    private List<Contasreceberpagamento> listaPagamento;
    
    /**
     * Creates new form FrmConsultarContasRecebidas
     */
    public FrmConsultarContasRecebidas(Config config) {
        this.config = config;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        initComponents();
        dataInicialjDateChooser.setDate(new Date());
        dataFinaljDateChooser.setDate(new Date());
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        razaosocialjTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        buscaBancojButton1 = new javax.swing.JButton();
        dataInicialjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel2 = new javax.swing.JLabel();
    dataFinaljDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel3 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();
jPanel2 = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
pagamentojTable = new javax.swing.JTable();
jPanel3 = new javax.swing.JPanel();
vencidasjScrollPane = new javax.swing.JScrollPane();
contasjTable = new javax.swing.JTable();
jPanel4 = new javax.swing.JPanel();
jScrollPane2 = new javax.swing.JScrollPane();
formajTable = new javax.swing.JTable();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Consulta Contas Recebidas");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Nome do Cliente");

razaosocialjTextField.setEditable(false);

jButton2.setText("Limpar");
jButton2.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
    }
    });

    buscaBancojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    buscaBancojButton1.setToolTipText("Pesquisa Fornecedor");
    buscaBancojButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscaBancojButton1ActionPerformed(evt);
        }
    });

    dataInicialjDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataInicialjDateChooserFocusGained(evt);
        }
    });

    jLabel2.setText("Data Inicial");

    dataFinaljDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataFinaljDateChooserFocusGained(evt);
        }
    });

    jLabel3.setText("Data Final");

    jButton1.setText("Pesquisar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
    jButton3.setText("Sair");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(razaosocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(buscaBancojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jButton2)))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addGap(10, 10, 10)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton3))
                .addComponent(jLabel3))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(razaosocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscaBancojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    pagamentojTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Data Pagamento", "Valor Juros", "Valor Descontos", "Valor Recebido"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, true
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    pagamentojTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            pagamentojTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(pagamentojTable);
    if (pagamentojTable.getColumnModel().getColumnCount() > 0) {
        pagamentojTable.getColumnModel().getColumn(0).setResizable(false);
        pagamentojTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(1).setResizable(false);
        pagamentojTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(2).setResizable(false);
        pagamentojTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(2).setHeaderValue("Valor Descontos");
        pagamentojTable.getColumnModel().getColumn(3).setResizable(false);
        pagamentojTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(3).setHeaderValue("Valor Recebido");
    }

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    contasjTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Conta", "Data Conta", "Cedente", "Data Vencimento", "Valor Conta"
        }
    ));
    contasjTable.getTableHeader().setReorderingAllowed(false);
    contasjTable.getColumnModel().getColumn(0).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(1).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(2).setPreferredWidth(300);
    contasjTable.getColumnModel().getColumn(3).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(4).setPreferredWidth(30);
    contasjTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            contasjTableMouseClicked(evt);
        }
    });
    vencidasjScrollPane.setViewportView(contasjTable);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencidasjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencidasjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(19, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    formajTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null},
            {null, null},
            {null, null},
            {null, null}
        },
        new String [] {
            "Forma Pagto", "Valor R$"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane2.setViewportView(formajTable);
    if (formajTable.getColumnModel().getColumnCount() > 0) {
        formajTable.getColumnModel().getColumn(0).setResizable(false);
        formajTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        formajTable.getColumnModel().getColumn(1).setResizable(false);
        formajTable.getColumnModel().getColumn(1).setPreferredWidth(40);
    }

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscaBancojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBancojButton1ActionPerformed
       
    }//GEN-LAST:event_buscaBancojButton1ActionPerformed

    private void dataInicialjDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataInicialjDateChooserFocusGained

   }//GEN-LAST:event_dataInicialjDateChooserFocusGained

    private void dataFinaljDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFinaljDateChooserFocusGained

   }//GEN-LAST:event_dataFinaljDateChooserFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((dataInicialjDateChooser.getDate()!=null) && (dataFinaljDateChooser.getDate()!=null)){
            String dataInicial = Formatacao.ConvercaoDataSql(dataInicialjDateChooser.getDate());
            String dataFinal = Formatacao.ConvercaoDataSql(dataFinaljDateChooser.getDate());
            carregarModelPagamento(dataInicial, dataFinal);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagamentojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagamentojTableMouseClicked
        int linha = pagamentojTable.getSelectedRow();
        if (linha >=0){
            carregarModelContas(listaPagamento.get(linha).getIdcontasReceberPagamento());
            carregarModelForma(listaPagamento.get(linha).getIdcontasReceberPagamento());
        }
    }//GEN-LAST:event_pagamentojTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void contasjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasjTableMouseClicked
        int linha = contasjTable.getSelectedRow();
        if (linha>=0){
            if (listaContas.get(linha).getTipo().equalsIgnoreCase("P")){
                new FrmConusltaContasFatura(listaContas.get(linha).getNumeroFaturaGerada());
            }else JOptionPane.showMessageDialog(rootPane, "Conta a receber não é parela de Fatura");
        }
    }//GEN-LAST:event_contasjTableMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaBancojButton1;
    private javax.swing.JTable contasjTable;
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataInicialjDateChooser;
    private javax.swing.JTable formajTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pagamentojTable;
    private javax.swing.JTextField razaosocialjTextField;
    private javax.swing.JScrollPane vencidasjScrollPane;
    // End of variables declaration//GEN-END:variables

    private void carregarModelPagamento(String dataInicial, String dataFinal){
        ContasReceberController contasReceberController = new ContasReceberController();
        listaPagamento = contasReceberController.listarPagamento(dataInicial, dataFinal);
        if (listaPagamento==null){
            listaPagamento = new ArrayList<Contasreceberpagamento>();
        }
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelPagamento = new PagamentoTableModel(listaPagamento);
        pagamentojTable.setModel(modelPagamento);
        pagamentojTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        pagamentojTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(2).setCellRenderer(renderer);
        pagamentojTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        pagamentojTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        pagamentojTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        pagamentojTable.repaint(); 
    }
    
    private void carregarModelForma(int idPagamento){
        ContasReceberController contasReceberController = new ContasReceberController();
        listaForma = contasReceberController.listarFormaPagamento(idPagamento);
        if (listaForma==null){
            listaForma = new ArrayList<Contasreceberforma>();
        }
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelForma = new FormaPagamentoTableModel(listaForma);
        formajTable.setModel(modelForma);
        formajTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        formajTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        formajTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        formajTable.repaint(); 
    }
    
    private void carregarModelContas(int idPagamento){
        listaContas = new ArrayList<Contasreceber>();
        String sql= "select c from Contasreceber c where c.contasreceberpagamento=" + idPagamento;
        ContasReceberController contasReceberController = new ContasReceberController();
        listaContas = contasReceberController.listarContas(sql);
        
       
        
        if (listaContas==null){
            listaContas = new ArrayList<Contasreceber>();
        }
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelContas = new ConsultaContasReceberTableModel(listaContas);
        contasjTable.setModel(modelContas);
        contasjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        contasjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        contasjTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        contasjTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        contasjTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        contasjTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        contasjTable.repaint();
    }
    


}
