/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasReceber;

import Regras.BancoController;
import Regras.ContasReceberController;
import Regras.CreditoReceberController;
import Regras.Formatacao;
import Regras.ParametroLocalController;
import Regras.VendedorController;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import controler.relatoriosJasper;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.*;

/**
 *
 * @author Wolverine
 */
public class FrmGerarFatura extends javax.swing.JFrame implements IGerarFatura{

    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private GerarFaturaBean fatura;
    private Config config;
    private List<CreditoBean> listaCreditos;
    private double valorCreditos;
    private double valorFatura;
    private DefaultTableCellRenderer rendererCor;
    
    private ConsultaGerarFaturaTableModel modelContas;

    /**
     * Creates new form FrmGerarFatura
     */
    public FrmGerarFatura(GerarFaturaBean fatura, Config config, int tipo) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.fatura = fatura;
        this.valorFatura =0;
        this.valorCreditos =0;
        this.config = config;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        
        this.rendererCor = new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {
                    Component comp = super.getTableCellRendererComponent(table, value,
                            isSelected, hasFocus, row, column);
                    if (value.equals("SIM")){
                        comp.setBackground(Color.red);
                    }else {
                        comp.setBackground(Color.white);
                    }
                    return comp;
                }
        };
        carregarDadosdaFatura();
        carregarBancos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroFaturajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeClientejTextField = new javax.swing.JTextField();
        diaPagamentojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        formaPagamentojTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataFaturajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel5 = new javax.swing.JLabel();
    notaFiscaljTextField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    dataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel7 = new javax.swing.JLabel();
valorDescontojTextField = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
dataDescontojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel9 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    dataParcela01jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel10 = new javax.swing.JLabel();
valorParcela01jTextField = new javax.swing.JTextField();
jLabel11 = new javax.swing.JLabel();
dataParcela02jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    valorParcela02jTextField = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    dataParcela03jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
valorParcela03jTextField = new javax.swing.JTextField();
jLabel15 = new javax.swing.JLabel();
dataParcela04jDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel16 = new javax.swing.JLabel();
    valorParcela04jTextField = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    informacoesjTextField = new javax.swing.JTextField();
    valorCreditojTextField = new javax.swing.JTextField();
    valorFaturajTextField = new javax.swing.JTextField();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    bancojComboBox = new javax.swing.JComboBox();
    jPanel3 = new javax.swing.JPanel();
    marcarContajButton = new javax.swing.JButton();
    creditosjButton = new javax.swing.JButton();
    desmarcarContajButton = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    gerarFaturajButton = new javax.swing.JButton();
    alterarFaturajButton = new javax.swing.JButton();
    fecharjButton = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    vencidasjScrollPane = new javax.swing.JScrollPane();
    contasjTable = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Gerar Faturas");

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Nº Fatura");

    jLabel2.setText("Cliente");

    nomeClientejTextField.setEditable(false);

    diaPagamentojTextField.setEditable(false);

    jLabel3.setText("Dia Pagto");

    formaPagamentojTextField.setEditable(false);

    jLabel4.setText("Forma Pagto");

    jLabel5.setText("Data Fatura");

    jLabel6.setText("Nº Nota Fiscal");

    jLabel7.setText("Data Vencimento");

    valorDescontojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorDescontojTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            valorDescontojTextFieldActionPerformed(evt);
        }
    });
    valorDescontojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldKeyReleased(evt);
        }
    });

    jLabel8.setText("Valor Desconto");

    jLabel9.setText("Data Desconto");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(numeroFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(diaPagamentojTextField)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(formaPagamentojTextField)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataFaturajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(notaFiscaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(valorDescontojTextField))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataDescontojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGap(0, 4, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(numeroFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomeClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(diaPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(formaPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(3, 3, 3)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataFaturajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(notaFiscaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorDescontojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataDescontojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel10.setText("Data Parcela 01");

    valorParcela01jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela01jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela01jTextFieldKeyReleased(evt);
        }
    });

    jLabel11.setText("Valor Parcela 01");

    valorParcela02jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela02jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela02jTextFieldKeyReleased(evt);
        }
    });

    jLabel12.setText("Valor Parcela 02");

    jLabel13.setText("Data Parcela 02");

    jLabel14.setText("Data Parcela 03");

    valorParcela03jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela03jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela03jTextFieldKeyReleased(evt);
        }
    });

    jLabel15.setText("Valor Parcela 03");

    jLabel16.setText("Data Parcela 04");

    valorParcela04jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorParcela04jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorParcela04jTextFieldKeyReleased(evt);
        }
    });

    jLabel17.setText("Valor Parcela 04");

    jLabel18.setText("Informações de Cobrança e Pagamento");

    valorCreditojTextField.setEditable(false);
    valorCreditojTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    valorCreditojTextField.setForeground(new java.awt.Color(255, 0, 0));
    valorCreditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    valorFaturajTextField.setEditable(false);
    valorFaturajTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    valorFaturajTextField.setForeground(new java.awt.Color(0, 0, 255));
    valorFaturajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel19.setText("Valor Creditos");

    jLabel20.setText("Valor da Fatura");

    jLabel21.setText("Banco para Pagamento");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela01jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(valorParcela01jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela02jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(valorParcela02jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela03jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(valorParcela03jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataParcela04jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(valorParcela04jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(informacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(0, 34, Short.MAX_VALUE))
                        .addComponent(valorFaturajTextField)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(bancojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela02jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela02jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela01jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela01jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela04jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela04jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorParcela03jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataParcela03jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(jLabel19)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(informacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorCreditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorFaturajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel21)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bancojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    marcarContajButton.setText("Marcar Conta");
    marcarContajButton.setToolTipText("Marca conta para gerar Fatura");
    marcarContajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            marcarContajButtonActionPerformed(evt);
        }
    });

    creditosjButton.setText("Creditos");
    creditosjButton.setToolTipText("Seleciona Creditos do Cliente");
    creditosjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            creditosjButtonActionPerformed(evt);
        }
    });

    desmarcarContajButton.setText("Desmarcar Contas");
    desmarcarContajButton.setToolTipText("Desmarcar Contas ");
    desmarcarContajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            desmarcarContajButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(67, Short.MAX_VALUE)
            .addComponent(marcarContajButton)
            .addGap(36, 36, 36)
            .addComponent(creditosjButton)
            .addGap(32, 32, 32)
            .addComponent(desmarcarContajButton)
            .addGap(89, 89, 89))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(marcarContajButton)
                .addComponent(creditosjButton)
                .addComponent(desmarcarContajButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    gerarFaturajButton.setText("Gerar Fatura");
    gerarFaturajButton.setToolTipText("Gera Fatura");
    gerarFaturajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            gerarFaturajButtonActionPerformed(evt);
        }
    });

    alterarFaturajButton.setText("Alterar Fatura");
    alterarFaturajButton.setToolTipText("Altera Fatura ");
    alterarFaturajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            alterarFaturajButtonActionPerformed(evt);
        }
    });

    fecharjButton.setText("Fechar");
    fecharjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            fecharjButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(79, 79, 79)
            .addComponent(gerarFaturajButton)
            .addGap(44, 44, 44)
            .addComponent(alterarFaturajButton)
            .addGap(39, 39, 39)
            .addComponent(fecharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(gerarFaturajButton)
                .addComponent(alterarFaturajButton)
                .addComponent(fecharjButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    contasjTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Conta", "Data Conta", "Cedente", "Data Vencimento", "Valor Conta"
        }
    ));
    contasjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    contasjTable.getTableHeader().setReorderingAllowed(false);
    contasjTable.getColumnModel().getColumn(0).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(1).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(2).setPreferredWidth(300);
    contasjTable.getColumnModel().getColumn(3).setPreferredWidth(30);
    contasjTable.getColumnModel().getColumn(4).setPreferredWidth(30);
    contasjTable.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            contasjTableKeyPressed(evt);
        }
    });
    vencidasjScrollPane.setViewportView(contasjTable);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencidasjScrollPane)
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencidasjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcarContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarContajButtonActionPerformed
        int linha = contasjTable.getSelectedRow();
        if (linha>=0){
            fatura.getListaContas().get(linha).setPagamento("SIM");
            valorFatura = (valorFatura + fatura.getListaContas().get(linha).getValorConta()) - valorCreditos;
            valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
        }
    }//GEN-LAST:event_marcarContajButtonActionPerformed

    private void desmarcarContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desmarcarContajButtonActionPerformed
        int linha = contasjTable.getSelectedRow();
        if (linha>=0){
            fatura.getListaContas().get(linha).setPagamento("NAO");
            valorFatura = (valorFatura - fatura.getListaContas().get(linha).getValorConta()) - valorCreditos;
            valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
        }
    }//GEN-LAST:event_desmarcarContajButtonActionPerformed

    private void contasjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contasjTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int linha = contasjTable.getSelectedRow();
            if (linha>=0){
                if (fatura.getListaContas().get(linha).getPagamento().equalsIgnoreCase("NAO")){
                    fatura.getListaContas().get(linha).setPagamento("SIM");
                    valorFatura = (valorFatura + fatura.getListaContas().get(linha).getValorConta());
                    valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
                }else {
                    fatura.getListaContas().get(linha).setPagamento("NAO");
                    valorFatura = (valorFatura - fatura.getListaContas().get(linha).getValorConta());
                    valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
                }
            }
        }
    }//GEN-LAST:event_contasjTableKeyPressed

    private void creditosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosjButtonActionPerformed
        gerarCreditos();
    }//GEN-LAST:event_creditosjButtonActionPerformed

    private void fecharjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharjButtonActionPerformed

    private void gerarFaturajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarFaturajButtonActionPerformed
        if (valorFatura>0){
            if (dataParcela01jDateChooser.getDate()==null){
                dataParcela01jDateChooser.setDate(dataVencimentojDateChooser.getDate());
                valorParcela01jTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
            }
            int idFatura = gerarFatura();
            gerarRelatorio(idFatura, Formatacao.valorPorExtenso(valorFatura));
            JOptionPane.showMessageDialog(rootPane, "Fatura Gerada com Sucesso");
            this.dispose();
        }
    }//GEN-LAST:event_gerarFaturajButtonActionPerformed

    private void valorDescontojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDescontojTextFieldActionPerformed

    private void valorDescontojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (valorDescontojTextField.getText().length()>0){
                double valorDesconto = Formatacao.ConvercaoMonetariaDouble(valorDescontojTextField.getText());
                valorFatura = valorFatura - valorDesconto;
                valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
            }
        }
    }//GEN-LAST:event_valorDescontojTextFieldKeyPressed

    private void valorDescontojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldKeyReleased
        valorDescontojTextField.setText(Formatacao.decinalValorMonetario(valorDescontojTextField.getText()));
    }//GEN-LAST:event_valorDescontojTextFieldKeyReleased

    private void valorParcela01jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela01jTextFieldKeyReleased
        valorParcela01jTextField.setText(Formatacao.decinalValorMonetario(valorParcela01jTextField.getText()));
    }//GEN-LAST:event_valorParcela01jTextFieldKeyReleased

    private void valorParcela02jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela02jTextFieldKeyReleased
        valorParcela02jTextField.setText(Formatacao.decinalValorMonetario(valorParcela02jTextField.getText()));
    }//GEN-LAST:event_valorParcela02jTextFieldKeyReleased

    private void valorParcela03jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela03jTextFieldKeyReleased
        valorParcela03jTextField.setText(Formatacao.decinalValorMonetario(valorParcela03jTextField.getText()));
    }//GEN-LAST:event_valorParcela03jTextFieldKeyReleased

    private void valorParcela04jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorParcela04jTextFieldKeyReleased
        valorParcela04jTextField.setText(Formatacao.decinalValorMonetario(valorParcela04jTextField.getText()));
    }//GEN-LAST:event_valorParcela04jTextFieldKeyReleased

    private void alterarFaturajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFaturajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarFaturajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarFaturajButton;
    private javax.swing.JComboBox bancojComboBox;
    private javax.swing.JTable contasjTable;
    private javax.swing.JButton creditosjButton;
    private com.toedter.calendar.JDateChooser dataDescontojDateChooser;
    private com.toedter.calendar.JDateChooser dataFaturajDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela01jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela02jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela03jDateChooser;
    private com.toedter.calendar.JDateChooser dataParcela04jDateChooser;
    private com.toedter.calendar.JDateChooser dataVencimentojDateChooser;
    private javax.swing.JButton desmarcarContajButton;
    private javax.swing.JTextField diaPagamentojTextField;
    private javax.swing.JButton fecharjButton;
    private javax.swing.JTextField formaPagamentojTextField;
    private javax.swing.JButton gerarFaturajButton;
    private javax.swing.JTextField informacoesjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton marcarContajButton;
    private javax.swing.JTextField nomeClientejTextField;
    private javax.swing.JTextField notaFiscaljTextField;
    private javax.swing.JTextField numeroFaturajTextField;
    private javax.swing.JTextField valorCreditojTextField;
    private javax.swing.JTextField valorDescontojTextField;
    private javax.swing.JTextField valorFaturajTextField;
    private javax.swing.JTextField valorParcela01jTextField;
    private javax.swing.JTextField valorParcela02jTextField;
    private javax.swing.JTextField valorParcela03jTextField;
    private javax.swing.JTextField valorParcela04jTextField;
    private javax.swing.JScrollPane vencidasjScrollPane;
    // End of variables declaration//GEN-END:variables

    public void carregarDadosdaFatura(){
        nomeClientejTextField.setText(fatura.getCliente().getNome());
        diaPagamentojTextField.setText(String.valueOf(fatura.getClienteFechamento().getDiaPagamento()));
        formaPagamentojTextField.setText(fatura.getClienteFechamento().getFormaPagamento());
        dataFaturajDateChooser.setDate(new Date());
        ParametroLocalController parametroLocalController = new ParametroLocalController();
        int numeroFatura = 0;
        numeroFatura = parametroLocalController.localizarEmpresa(this.config.getEmpresa().getIdempresa()).getNumeroFatura() + 1;
        numeroFaturajTextField.setText(String.valueOf(numeroFatura));
        this.fatura.getFatura().setNumeroFatura(numeroFaturajTextField.getText());
        carregarModel();
    }
    
    public void salvarNumeroFatura(){
        ParametroLocalController parametroLocalController = new ParametroLocalController();
        ParametrosLocal parametro =  parametroLocalController.localizarEmpresa(this.config.getEmpresa().getIdempresa());
        parametro.setNumeroFatura(parametro.getNumeroFatura() + 1);
        parametroLocalController.salvar(parametro);
    }
    
   
    
    public void alterarCreditos(){
        if (listaCreditos != null) {
            if (listaCreditos.size() > 0) {
                CreditoReceberController creditoReceberController = new CreditoReceberController();
                for (int i = 0; i < listaCreditos.size(); i++) {
                    Creditosreceber credito = listaCreditos.get(i).getCredito();
                    credito.setContasreceberpagamento(2);
                    credito.setNumerofatura(fatura.getFatura().getNumeroFatura());
                    credito.setUtilizado("SIM");
                    creditoReceberController.salvar(credito);
                }
            }
        }
    }
    
    
    public void carregarModel(){
        modelContas = new ConsultaGerarFaturaTableModel(fatura.getListaContas());

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        
        contasjTable.setModel(modelContas);
        contasjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        contasjTable.getColumnModel().getColumn(1).setPreferredWidth(80);
        contasjTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        contasjTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        contasjTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        contasjTable.getColumnModel().getColumn(4).setCellRenderer(rendererCor);
        contasjTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        contasjTable.repaint();
    }
    
    public void gerarCreditos(){
        String sqlCreditos = "select c from Creditosreceber c where c.contasreceberpagamento=1 and c.cliente=" + this.fatura.getCliente().getIdcliente() + " and c.empresa=" +
                this.config.getEmpresa().getIdempresa() + " order by c.dataLancamento";
        CreditoReceberController creditoReceberController = new CreditoReceberController();
        List<Creditosreceber> listaCreditos = creditoReceberController.listarCreditos(sqlCreditos);
        List<CreditoBean> listaCreditoBean = new ArrayList<CreditoBean>();
        if (listaCreditos!=null){
            for(int i=0;i<listaCreditos.size();i++){
                CreditoBean creditoBean = new CreditoBean(listaCreditos.get(i));
                listaCreditoBean.add(creditoBean);
            }
        }
        if (listaCreditoBean.size()>0){
            new FrmConsultaCreditosReceber(listaCreditoBean,2, this);
        }else JOptionPane.showMessageDialog(rootPane, "Cliente não possui Creditos");
        
    }

    public void utilizarCreditos(List<CreditoBean> listaCreditos) {
        this.listaCreditos = new ArrayList<CreditoBean>();
        valorCreditos = 0;
        for (int i=0; i<listaCreditos.size();i++){
            if (listaCreditos.get(i).getMarcado().equalsIgnoreCase("SIM")){
                CreditoBean creditoBean = listaCreditos.get(i);
                this.listaCreditos.add(creditoBean);
                valorCreditos = valorCreditos + creditoBean.getCredito().getValorCredito();
            }
        }
        valorCreditojTextField.setText(Formatacao.foramtarDoubleString(valorCreditos));
        valorFatura = valorFatura - valorCreditos;
        valorFaturajTextField.setText(Formatacao.foramtarDoubleString(valorFatura));
    }
    
    public int gerarFatura(){
        fatura.getFatura().setCliente(fatura.getCliente().getIdcliente());
        fatura.getFatura().setContasreceberpagamento(1);
        fatura.getFatura().setDataLancamento(dataFaturajDateChooser.getDate());
        fatura.getFatura().setDataVencimento(dataVencimentojDateChooser.getDate());
        fatura.getFatura().setEmpresa(this.config.getEmpresa().getIdempresa());
        fatura.getFatura().setInstrucoes(informacoesjTextField.getText());
        fatura.getFatura().setNumeroFatura(numeroFaturajTextField.getText());
        fatura.getFatura().setNumeroNotaFiscal(notaFiscaljTextField.getText());
        fatura.getFatura().setNumeroParcelas(verifcarNumeroParcelas());
        fatura.getFatura().setValorFatura(valorFatura);
        if (dataDescontojDateChooser.getDate()!=null){
            fatura.getFatura().setDataDesconto(dataDescontojDateChooser.getDate());
        }
        if (valorDescontojTextField.getText().length()>0){
            fatura.getFatura().setValorDesconto(Formatacao.formatarStringDouble(valorDescontojTextField.getText()));
        }
        if (dataParcela01jDateChooser.getDate()!=null){
            fatura.getFatura().setDataParcela01(dataParcela01jDateChooser.getDate());
        }
        if (valorParcela01jTextField.getText().length()>0){
            fatura.getFatura().setValorParcela01(Formatacao.formatarStringDouble(valorParcela01jTextField.getText()));
        }
        if (dataParcela02jDateChooser.getDate()!=null){
            fatura.getFatura().setDataParcela02(dataParcela02jDateChooser.getDate());
        }
        if (valorParcela02jTextField.getText().length()>0){
            fatura.getFatura().setValorParcela02(Formatacao.formatarStringDouble(valorParcela02jTextField.getText()));
        }
        if (dataParcela03jDateChooser.getDate()!=null){
            fatura.getFatura().setDataParcela03(dataParcela03jDateChooser.getDate());
        }
        if (valorParcela03jTextField.getText().length()>0){
            fatura.getFatura().setValorParcela03(Formatacao.formatarStringDouble(valorParcela03jTextField.getText()));
        }
        if (dataParcela04jDateChooser.getDate()!=null){
            fatura.getFatura().setDataParcela04(dataParcela04jDateChooser.getDate());
        }
        if (valorParcela04jTextField.getText().length()>0){
            fatura.getFatura().setValorParcela04(Formatacao.formatarStringDouble(valorParcela04jTextField.getText()));
        }
        
        
        ContasReceberController contasReceberController = new ContasReceberController();
        fatura.setFatura(contasReceberController.salvarFatura(fatura.getFatura()));
        verifcarParcelasSalvar();
        registarContasReceberFaturas();
        alterarCreditos();
        salvarNumeroFatura();

        
       return fatura.getFatura().getIdFaturasReceber(); 
    }
    
    public void registarContasReceberFaturas(){
        ContasReceberController contasReceberController = new ContasReceberController();
        Contasreceberpagamento contasreceberpagamento = contasReceberController.consultarContaReceberPagamento(2);
        for (int i=0;i<fatura.getListaContas().size();i++){
            if (fatura.getListaContas().get(i).getPagamento().equalsIgnoreCase("SIM")){
                Contasreceber contaReceber = fatura.getListaContas().get(i);
                if (contaReceber!=null){
                    contaReceber.setNumeroFaturaGerada(fatura.getFatura().getNumeroFatura());
                    contaReceber.setNumeroFatura(0);
                    contaReceber.setContasreceberpagamento(contasreceberpagamento);
                    contasReceberController.salvarContasReceber(contaReceber);
                }
            }
        }
    }
    
    public void salvarParcelas(int numeroFatura, Date dataVencimento, double valorParcela, String numeroDocumento, int numeroParcela) {
        ContasReceberController contasReceberController = new ContasReceberController();
        Contasreceberpagamento contasreceberpagamento = contasReceberController.consultarContaReceberPagamento(1);
        VendedorController vendedorController = new VendedorController();
        Vendedor vendedor = vendedorController.consultarVendedorId(1);
        Contasreceber parcela = new Contasreceber();
        parcela.setCliente(fatura.getCliente());
        parcela.setContasreceberpagamento(contasreceberpagamento);
        parcela.setDataLancamento(fatura.getFatura().getDataLancamento());
        parcela.setNumeroFatura(fatura.getFatura().getIdFaturasReceber());
        parcela.setNumeroFaturaGerada("0");
        parcela.setDataVencimento(dataVencimento);
        parcela.setNumeroDocumento(numeroDocumento);
        parcela.setNumeroParcelas(numeroParcela);
        parcela.setValorConta(valorParcela);
        parcela.setEmpresa(this.config.getEmpresa());
        Banco banco = (Banco) bancojComboBox.getSelectedItem();
        parcela.setBancoPagamento(banco.getIdbanco());
        parcela.setVendedor(vendedor);
        parcela.setPagamento("NAO");
        parcela.setTipo("P");
        contasReceberController.salvarContasReceber(parcela);
    }    
    
    public void verifcarParcelasSalvar(){
        String numeroFatura = fatura.getFatura().getNumeroFatura();
        if (dataParcela01jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getFatura().getIdFaturasReceber(), dataParcela01jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela01jTextField.getText()), 
                    numeroFatura+"01", 01);
        }
        if (dataParcela02jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getFatura().getIdFaturasReceber(), dataParcela02jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela02jTextField.getText()), 
                    numeroFatura+"02", 02);
        }
        if (dataParcela03jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getFatura().getIdFaturasReceber(), dataParcela03jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela03jTextField.getText()), 
                    numeroFatura+"03", 03);
        }
        if (dataParcela04jDateChooser.getDate()!=null){
            salvarParcelas(fatura.getFatura().getIdFaturasReceber(), dataParcela04jDateChooser.getDate(),Formatacao.ConvercaoMonetariaDouble(valorParcela04jTextField.getText()), 
                    numeroFatura+"04", 04);
        }
    }
    
    
    public int verifcarNumeroParcelas(){
        int numeroParcelas = 0;
        if (dataParcela01jDateChooser.getDate()!=null){
            numeroParcelas = 1;
        }else return numeroParcelas;
        if (dataParcela02jDateChooser.getDate()!=null){
            numeroParcelas = 2;
        }else return numeroParcelas;
        if (dataParcela03jDateChooser.getDate()!=null){
            numeroParcelas = 3;
        }else return numeroParcelas;
        if (dataParcela04jDateChooser.getDate()!=null){
            numeroParcelas = 4;
        }else return numeroParcelas;
        return numeroParcelas;
    }
    
    public void gerarRelatorio(int idFatura, String valorExtenso){
        String url = ("telas/ContasReceber/Relatorios/faturaReceber.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("idFatura", idFatura);
            parameters.put("valorExtenso", valorExtenso);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }
    
    public void carregarBancos(){
        BancoController bancoController = new BancoController();
        List<Banco> listaBanco= bancoController.listar();
        bancojComboBox.removeAllItems();
        if (listaBanco!=null){
            for(int i=0;i<listaBanco.size();i++){
                bancojComboBox.addItem(listaBanco.get(i));
            }
        }
    }

}