/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Encerramento;

import Regras.ContasPagarController;
import Regras.ContasReceberController;
import Regras.CreditoReceberController;
import Regras.EncerramentoController;
import Regras.EstoqueController;
import Regras.Formatacao;
import Regras.ProdutoController;
import controler.Config;
import controler.UsuarioLogado;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Contaspagar;
import model.Contasreceber;
import model.Creditosreceber;
import model.Encerramento;
import model.Inventario;
import telas.ContasReceber.FrmConsultaContasReceber;
import view.Viewconsultaprodutoestoque;

/**
 *
 * @author Wolverine
 */
public class FrmEncerramento extends javax.swing.JFrame {
    
    private Encerramento encerramento;
    private List<Inventario> listaProduto;
    private ConsultaProdutoInventarioTableModel model;
    private IInventario telaInventario;

    /**
     * Creates new form FrmEncerramento
     */
    public FrmEncerramento(Config config, UsuarioLogado usuarioLogado, Encerramento encerramento, IInventario telaInventario) {
        this.encerramento = encerramento;
        this.telaInventario = telaInventario;
        if (encerramento==null){
            this.encerramento = new Encerramento();
            this.encerramento.setUsuario(usuarioLogado.getUsuario().getNome());
            this.encerramento.setEmpresa(config.getEmpresa());
        }else {
            popuplarInvetario();
        }
        initComponents();
         URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        anojTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tipojComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpvencidasjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpvencendojTextField = new javax.swing.JTextField();
        cpvencerjLabel = new javax.swing.JLabel();
        cpvencerjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cptotaljTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        crvencidasjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        crvencendojTextField = new javax.swing.JTextField();
        cpvencerjLabel1 = new javax.swing.JLabel();
        crvencerjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        crtotaljTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cr180jTextField = new javax.swing.JTextField();
        creditojTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        caixajTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bbjTextField = new javax.swing.JTextField();
        cpvencerjLabel2 = new javax.swing.JLabel();
        cefjTextField = new javax.swing.JTextField();
        cpvencerjLabel3 = new javax.swing.JLabel();
        totalEstoquejTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProdutosjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Encerramento");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Período");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.setToolTipText("Iniciar encerramento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.setToolTipText("Salvar Encerramento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        jButton3.setText("Fechar");
        jButton3.setToolTipText("Sair do Encerramento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tipojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensal", "Anual" }));

        jLabel12.setText("Tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(tipojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas a Pagar"));

        jLabel2.setText("Vencidas");

        cpvencidasjTextField.setEditable(false);
        cpvencidasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Vencendo");

        cpvencendojTextField.setEditable(false);
        cpvencendojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cpvencerjLabel.setText("Vencer");

        cpvencerjTextField.setEditable(false);
        cpvencerjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Total");

        cptotaljTextField.setEditable(false);
        cptotaljTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cpvencidasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpvencendojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpvencerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpvencerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cptotaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cpvencerjLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpvencendojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpvencerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cpvencidasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cptotaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas a Receber"));

        jLabel4.setText("Vencidas");

        crvencidasjTextField.setEditable(false);
        crvencidasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("Vencendo");

        crvencendojTextField.setEditable(false);
        crvencendojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cpvencerjLabel1.setText("Vencer");

        crvencerjTextField.setEditable(false);
        crvencerjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Total");

        crtotaljTextField.setEditable(false);
        crtotaljTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("180 dias");

        cr180jTextField.setEditable(false);
        cr180jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        creditojTextField.setEditable(false);
        creditojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Créditos");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(crvencidasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crvencendojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crvencerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpvencerjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cr180jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crtotaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(cpvencerjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crvencerjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crvencendojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crvencidasjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cr180jTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crtotaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa / Banco"));

        jLabel10.setText("Saldo Caixa");

        caixajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        caixajTextField.setText("0,00");

        jLabel11.setText("Banco Brasil");

        bbjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bbjTextField.setText("0,00");

        cpvencerjLabel2.setText("CEF");

        cefjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cefjTextField.setText("0,00");

        cpvencerjLabel3.setText("Total Estoque");

        totalEstoquejTextField.setEditable(false);
        totalEstoquejTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(caixajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpvencerjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cefjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpvencerjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalEstoquejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(totalEstoquejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cefjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caixajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpvencerjLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpvencerjLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Valores", jPanel2);

        ProdutosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Unidade", "Quantidade", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(ProdutosjTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventário", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        encerramentoContasPagar();
        encerramentoContasReceber();
        if (encerramento.getIdencerramento()==null){
            encerramentoInventario();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EncerramentoController encerramentoController = new EncerramentoController();
        encerramento.setData(new Date());
        encerramento.setHora(Formatacao.foramtarHoraString());
        encerramento.setContaspagarvencendo(Formatacao.formatarStringfloat(cpvencendojTextField.getText()));
        encerramento.setContaspagarvencer(Formatacao.formatarStringfloat(cpvencerjTextField.getText()));
        encerramento.setContaspagarvencidas(Formatacao.formatarStringfloat(cpvencidasjTextField.getText()));
        encerramento.setContasreceber180(Formatacao.formatarStringfloat(cr180jTextField.getText()));
        encerramento.setContasreceberavencer(Formatacao.formatarStringfloat(crvencerjTextField.getText()));
        encerramento.setContasrecebervencendo(Formatacao.formatarStringfloat(crvencendojTextField.getText()));
        encerramento.setContasrecebervencidas(Formatacao.formatarStringfloat(crvencidasjTextField.getText()));
        encerramento.setCreditos(Formatacao.formatarStringfloat(creditojTextField.getText()));
        encerramento.setBb(Formatacao.formatarStringfloat(bbjTextField.getText()));
        encerramento.setCef(Formatacao.formatarStringfloat(cefjTextField.getText()));
        encerramento.setSaldocaixa(Formatacao.formatarStringfloat(caixajTextField.getText()));
        encerramento.setPeriodo(anojTextField.getText());
        encerramento.setTipo(tipojComboBox.getSelectedItem().toString());
        encerramento.setTotalestoque(Formatacao.formatarStringfloat(totalEstoquejTextField.getText()));
        encerramento = encerramentoController.salvar(encerramento);
        if (listaProduto != null) {   
            for (int i = 0; i < listaProduto.size(); i++) {
                listaProduto.get(i).setEncerramento(encerramento);
                encerramentoController.salvar(listaProduto.get(i));       
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Inventário Salvo com Sucesso");
        telaInventario.setModel();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProdutosjTable;
    private javax.swing.JTextField anojTextField;
    private javax.swing.JTextField bbjTextField;
    private javax.swing.JTextField caixajTextField;
    private javax.swing.JTextField cefjTextField;
    private javax.swing.JTextField cptotaljTextField;
    private javax.swing.JTextField cpvencendojTextField;
    private javax.swing.JLabel cpvencerjLabel;
    private javax.swing.JLabel cpvencerjLabel1;
    private javax.swing.JLabel cpvencerjLabel2;
    private javax.swing.JLabel cpvencerjLabel3;
    private javax.swing.JTextField cpvencerjTextField;
    private javax.swing.JTextField cpvencidasjTextField;
    private javax.swing.JTextField cr180jTextField;
    private javax.swing.JTextField creditojTextField;
    private javax.swing.JTextField crtotaljTextField;
    private javax.swing.JTextField crvencendojTextField;
    private javax.swing.JTextField crvencerjTextField;
    private javax.swing.JTextField crvencidasjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox tipojComboBox;
    private javax.swing.JTextField totalEstoquejTextField;
    // End of variables declaration//GEN-END:variables

    public void encerramentoContasPagar() {
        List<Contaspagar> listaVencidas;
        List<Contaspagar> listaVencer;
        List<Contaspagar> listaVencendo;
        String dataAtual = Formatacao.ConvercaoDataSql(new Date());
        ContasPagarController contasPagarController = new ContasPagarController();
        String sqlVencendo = null;
        sqlVencendo = "select c from Contaspagar c where c.pagamentocontaspagar=1  and c.dataReal='" + dataAtual + "' and c.empresa =" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento, numeroDocumento";
        listaVencendo = contasPagarController.listarContas(sqlVencendo);
        if (listaVencendo==null){
            listaVencendo = new ArrayList<Contaspagar>();
        }
        String sqlVencer = null;
        sqlVencer = "select c from Contaspagar c where c.pagamentocontaspagar=1  and c.dataReal>'" + dataAtual + "' and c.empresa =" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento, numeroDocumento";
        listaVencer = contasPagarController.listarContas(sqlVencer);
        if (listaVencer==null){
            listaVencer = new ArrayList<Contaspagar>();
        }
        String sqlVencidas = null;
        sqlVencidas = "select c from Contaspagar c where c.pagamentocontaspagar=1  and c.dataReal<'" + dataAtual + "' and c.empresa =" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento, c.numeroDocumento";
        listaVencidas = contasPagarController.listarContas(sqlVencidas);
        if (listaVencidas==null){
            listaVencidas = new ArrayList<Contaspagar>();
        }
        double valorVencer = 0;
        double valorVencida = 0;
        double valorVencendo =0;
        double soma = 0; 
        
        for(int i=0;i<listaVencendo.size();i++){
            valorVencendo = valorVencendo + listaVencendo.get(i).getValorConta();
        }
        cpvencendojTextField.setText(Formatacao.foramtarDoubleString(valorVencendo));
        soma = soma + valorVencendo;
        
        for(int i=0;i<listaVencer.size();i++){
            valorVencer = valorVencer + listaVencer.get(i).getValorConta();
        }
        cpvencerjTextField.setText(Formatacao.foramtarDoubleString(valorVencer));
        soma = soma + valorVencer;
        
        for(int i=0;i<listaVencidas.size();i++){
            valorVencida = valorVencida + listaVencidas.get(i).getValorConta();
        }
        cpvencidasjTextField.setText(Formatacao.foramtarDoubleString(valorVencida));
        soma = valorVencida + soma;
        cptotaljTextField.setText(Formatacao.foramtarDoubleString(soma));
    }
    
    public void encerramentoContasReceber() {
        List<Contasreceber> listaVencidas;
        List<Contasreceber> listaVencer;
        List<Contasreceber> listaVencendo;
        List<Contasreceber> lista180dias;
        List<Creditosreceber> listaCreditos;

        String dataAtual = Formatacao.ConvercaoDataSql(new Date());
        String data180 = null;
        try {
            data180 = Formatacao.SubtarirDatas(new Date(), 180, "yyyy/MM/dd");
        } catch (Exception ex) {
            Logger.getLogger(FrmConsultaContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sqlContaVencendo = null;
        String sqlContaVencer = null;
        String sqlContaVencidas = null;
        String sqlConta180dias = null;

        String sqlCredito = null;
        sqlContaVencendo = "select c from Contasreceber c where c.contasreceberpagamento=1  and c.dataVencimento='" + dataAtual + "' and c.empresa.idempresa=" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento";
        sqlContaVencendo = "select c from Contasreceber c where c.contasreceberpagamento=1  and c.dataVencimento='" + dataAtual + "' and c.empresa.idempresa=" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento";
        sqlContaVencer = "select c from Contasreceber c where c.contasreceberpagamento=1  and c.dataVencimento>'" + dataAtual + "' and c.empresa.idempresa=" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento";
        sqlContaVencidas = "select c from Contasreceber c where c.contasreceberpagamento=1  and c.dataVencimento>'" + data180 + "' and c.dataVencimento<'" + dataAtual + "' and c.empresa.idempresa=" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento";
        sqlConta180dias = "select c from Contasreceber c where c.contasreceberpagamento=1  and c.dataVencimento<'" + data180 + "' and c.empresa.idempresa=" + encerramento.getEmpresa().getIdempresa() + " order by c.dataVencimento";
        sqlCredito = " select c from Creditosreceber c where c.contasreceberpagamento=1 and c.empresa=" + encerramento.getEmpresa().getIdempresa();
        lista180dias = new ArrayList<Contasreceber>();
        ContasReceberController contasReceberController = new ContasReceberController();
        listaVencendo = contasReceberController.listarContas(sqlContaVencendo);
        listaVencer = contasReceberController.listarContas(sqlContaVencer);
        listaVencidas = contasReceberController.listarContas(sqlContaVencidas);
        lista180dias = contasReceberController.listarContas(sqlConta180dias);
        CreditoReceberController creditoReceberController = new CreditoReceberController();
        listaCreditos = creditoReceberController.listarCreditos(sqlCredito);
        if (listaCreditos==null){
            listaCreditos = new ArrayList<Creditosreceber>();
        }
        double valorVencer = 0;
        double valorVencida = 0;
        double valorVencendo = 0;
        double valor180dias = 0;
        double valorCreditos = 0;
        double soma = 0;
        
        if (lista180dias==null){
            lista180dias = new ArrayList<Contasreceber>();
        }
        for (int i = 0; i < lista180dias.size(); i++) {
            valor180dias = valor180dias + lista180dias.get(i).getValorConta();
        }
        cr180jTextField.setText(Formatacao.foramtarDoubleString(valor180dias));
        for (int i = 0; i < listaCreditos.size(); i++) {
            valorCreditos = valorCreditos + listaCreditos.get(i).getValorCredito();
        }
        creditojTextField.setText(Formatacao.foramtarDoubleString(valorCreditos));
        soma -= valorCreditos;
        if (listaVencendo==null){
            listaVencendo = new ArrayList<Contasreceber>();
        }
        for (int i = 0; i < listaVencendo.size(); i++) {
            valorVencendo = valorVencendo + listaVencendo.get(i).getValorConta();
        }
        crvencendojTextField.setText(Formatacao.foramtarDoubleString(valorVencendo));
        soma = soma + valorVencendo;
        if (listaVencer==null){
            listaVencer = new ArrayList<Contasreceber>();
        }
        for (int i = 0; i < listaVencer.size(); i++) {
            valorVencer = valorVencer + listaVencer.get(i).getValorConta();
        }
        crvencerjTextField.setText(Formatacao.foramtarDoubleString(valorVencer));
        soma = soma + valorVencer;
        if (listaVencidas==null){
            listaVencidas = new ArrayList<Contasreceber>();
        }
        for (int i = 0; i < listaVencidas.size(); i++) {
            valorVencida = valorVencida + listaVencidas.get(i).getValorConta();
        }
        crvencidasjTextField.setText(Formatacao.foramtarDoubleString(valorVencida));
        soma = valorVencida + soma;

        crtotaljTextField.setText(Formatacao.foramtarDoubleString(soma));

    }
    
    public void encerramentoInventario(){
        float total = 0.0f;
        EstoqueController estoqueController = new EstoqueController();
        List<Viewconsultaprodutoestoque>listaEstoque = estoqueController.listarEstoqueZero(encerramento.getEmpresa().getIdempresa());
        listaProduto = new ArrayList<Inventario>();
        if (listaEstoque!=null){
            ProdutoController produtoController = new ProdutoController();
            for(int i=0;i<listaEstoque.size();i++){
                Inventario inventario = new Inventario();
                inventario.setQuantidadeestoque(Formatacao.foramtarQuantidade(listaEstoque.get(i).getQuantidadeEstoque()));
                
                float valorUnitario = listaEstoque.get(i).getValorCompra().floatValue();
                if (valorUnitario<=0){
                    valorUnitario = listaEstoque.get(i).getValorVenda().floatValue() * 0.7f;
                }
                inventario.setValorunitario(Formatacao.foramtarFloatString(valorUnitario));
                inventario.setValortotal(Formatacao.foramtarFloatString(valorUnitario * listaEstoque.get(i).getQuantidadeEstoque().floatValue()));
                inventario.setValorvenda(Formatacao.foramtarFloatString(listaEstoque.get(i).getValorVenda()));
                inventario.setProduto(produtoController.consultarProdutoid(listaEstoque.get(i).getIdProduto()));
                listaProduto.add(inventario);
                total = total + (valorUnitario * listaEstoque.get(i).getQuantidadeEstoque().floatValue());
            }
        }
        totalEstoquejTextField.setText(Formatacao.foramtarFloatString(total));
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);      
        model = new ConsultaProdutoInventarioTableModel(listaProduto);
        ProdutosjTable.setModel(model);
        ProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        ProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        ProdutosjTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        ProdutosjTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        ProdutosjTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        ProdutosjTable.getColumnModel().getColumn(4).setCellRenderer(renderer);
        ProdutosjTable.getColumnModel().getColumn(4).setPreferredWidth(80);
        ProdutosjTable.repaint();
    }
    
    public void popuplarInvetario(){
        tipojComboBox.setSelectedItem(encerramento.getTipo());
        anojTextField.setText(encerramento.getPeriodo());
        listaProduto = encerramento.getInventarioList();
        cpvencendojTextField.setText(Formatacao.foramtarFloatString(encerramento.getContaspagarvencendo()));
        cpvencerjTextField.setText(Formatacao.foramtarFloatString(encerramento.getContaspagarvencer()));
        cpvencidasjTextField.setText(Formatacao.foramtarFloatString(encerramento.getContaspagarvencidas()));
        cptotaljTextField.setText(Formatacao.foramtarFloatString(encerramento.getContaspagarvencidas() + encerramento.getContaspagarvencendo() + encerramento.getContaspagarvencer()));
        
        cr180jTextField.setText(Formatacao.foramtarFloatString(encerramento.getContasreceber180()));
        crvencendojTextField.setText(Formatacao.foramtarFloatString(encerramento.getContasrecebervencendo()));
        crvencerjTextField.setText(Formatacao.foramtarFloatString(encerramento.getContasreceberavencer()));
        crvencidasjTextField.setText(Formatacao.foramtarFloatString(encerramento.getContasrecebervencidas()));
        creditojTextField.setText(Formatacao.foramtarFloatString(encerramento.getCreditos()));
        crtotaljTextField.setText(Formatacao.foramtarFloatString(encerramento.getContaspagarvencidas()+ encerramento.getContasrecebervencendo() + encerramento.getContasreceberavencer() + encerramento.getContasreceber180() - encerramento.getCreditos()));
        
        caixajTextField.setText(Formatacao.foramtarFloatString(encerramento.getSaldocaixa()));
        bbjTextField.setText(Formatacao.foramtarFloatString(encerramento.getBb()));
        cefjTextField.setText(Formatacao.foramtarFloatString(encerramento.getCef()));
        totalEstoquejTextField.setText(Formatacao.foramtarFloatString(encerramento.getTotalestoque()));
        
    }
}
