/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Entrada.nova;

import Interfaces.ItelaConsulta;
import Regras.EntradaProdutoController;
import Regras.Formatacao;
import Regras.FornecedorController;
import Regras.ParametroLocalController;
import beanController.ILerNFe;
import beanController.LerXml200;
import beanController.LerXml310;
import beanController.NfDuplicatas;
import beanController.NfProdutos;
import beanController.NotaEletronica;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import model.Banco;
import model.Docentrada;
import model.Estoque;
import model.Fornecedor;
import model.Nfentrada;
import model.ParametrosLocal;
import model.Produto;
import org.xml.sax.SAXException;
import telas.Entrada.FrmLocalizarArquivo;
import telas.Fornecedor.FrmCadastrarFornecedor;
import telas.Fornecedor.FrmConsultaFornecedor;

/**
 *
 * @author Wolverine
 */
public class FrmDocEntrada extends javax.swing.JFrame implements ItelaConsulta{
    
    private Docentrada docEntrada;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Config config;
    private Fornecedor fornecedor;
    private Nfentrada notaFiscal;
    private byte[] xmlNfe;
    private ILerNFe nfe;
    private List<NfDuplicatas> listaDuplicata;
    private List<NfProdutos> listaProdutos;
    private NotaEletronica nota;

    /**
     * Creates new form FrmDocEntrada
     */
    public FrmDocEntrada(Config config, Docentrada docentrada) {
        this.docEntrada= docentrada;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.config =config;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        if (this.docEntrada!=null){
            carregarDadosDocEntrada();
        }else {
            this.docEntrada = new Docentrada();
            dataEntradajDateChooser.setDate(new Date());
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dadosRegistrojPanel = new javax.swing.JPanel();
        fornecedorjTextField = new javax.swing.JTextField();
        dataEntradajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    tipoDocumentojComboBox = new javax.swing.JComboBox();
    condicaoPagamentojComboBox = new javax.swing.JComboBox();
    valorEncargosjTextField = new javax.swing.JTextField();
    valorDescontojTextField = new javax.swing.JTextField();
    valorProdutosjTextField = new javax.swing.JTextField();
    situacaojComboBox = new javax.swing.JComboBox();
    valorTotaljTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    controlejButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    buscaBancojButton3 = new javax.swing.JButton();
    dadosNotafiscaljPanel = new javax.swing.JPanel();
    numerojTextField = new javax.swing.JTextField();
    dataEmissaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
dataSaidajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    especiejComboBox = new javax.swing.JComboBox();
    seriejTextField = new javax.swing.JTextField();
    subSeriejTextField = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    gerarRecibojButton = new javax.swing.JButton();
    xmljPanel = new javax.swing.JPanel();
    jLabel17 = new javax.swing.JLabel();
    caminhojTextField = new javax.swing.JTextField();
    limparjButton = new javax.swing.JButton();
    localizarjButton = new javax.swing.JButton();
    carregarjButton = new javax.swing.JButton();
    jLabel16 = new javax.swing.JLabel();
    versaoNFejComboBox = new javax.swing.JComboBox();
    jPanel5 = new javax.swing.JPanel();
    jPanel15 = new javax.swing.JPanel();
    confirmajButton = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    produtosjButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Entrada de Produtos");

    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    dadosRegistrojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento Registro de Compra"));
    dadosRegistrojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    fornecedorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            fornecedorjTextFieldKeyPressed(evt);
        }
    });
    dadosRegistrojPanel.add(fornecedorjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, -1));

    dataEntradajDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataEntradajDateChooserFocusGained(evt);
        }
    });
    dadosRegistrojPanel.add(dataEntradajDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, -1));

    tipoDocumentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nota Fiscal", "Pedido", "Recibo" }));
    tipoDocumentojComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            tipoDocumentojComboBoxFocusLost(evt);
        }
    });
    dadosRegistrojPanel.add(tipoDocumentojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 220, -1));

    condicaoPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a Prazo", "a Vista" }));
    dadosRegistrojPanel.add(condicaoPagamentojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 100, -1));

    valorEncargosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorEncargosjTextField.setText("0,00");
    valorEncargosjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            valorEncargosjTextFieldFocusGained(evt);
        }
    });
    valorEncargosjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorEncargosjTextFieldKeyReleased(evt);
        }
    });
    dadosRegistrojPanel.add(valorEncargosjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

    valorDescontojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorDescontojTextField.setText("0,00");
    valorDescontojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            valorDescontojTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorDescontojTextFieldFocusLost(evt);
        }
    });
    valorDescontojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldKeyReleased(evt);
        }
    });
    dadosRegistrojPanel.add(valorDescontojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 90, -1));

    valorProdutosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorProdutosjTextField.setText("0,00");
    valorProdutosjTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            valorProdutosjTextFieldActionPerformed(evt);
        }
    });
    valorProdutosjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            valorProdutosjTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorProdutosjTextFieldFocusLost(evt);
        }
    });
    valorProdutosjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorProdutosjTextFieldKeyReleased(evt);
        }
    });
    dadosRegistrojPanel.add(valorProdutosjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 100, -1));

    situacaojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Movimento", "Finalizada", "Reposição" }));
    situacaojComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            situacaojComboBoxFocusLost(evt);
        }
    });
    dadosRegistrojPanel.add(situacaojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 330, -1));

    valorTotaljTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorTotaljTextField.setText("0,00");
    valorTotaljTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            valorTotaljTextFieldActionPerformed(evt);
        }
    });
    valorTotaljTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            valorTotaljTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorTotaljTextFieldFocusLost(evt);
        }
    });
    valorTotaljTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorTotaljTextFieldKeyReleased(evt);
        }
    });
    dadosRegistrojPanel.add(valorTotaljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 100, -1));

    jLabel1.setText("Fornecedor");
    dadosRegistrojPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

    controlejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note.png"))); // NOI18N
    controlejButton.setText("Controle");
    controlejButton.setToolTipText("Situação do Registro de Compras");
    controlejButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            controlejButtonActionPerformed(evt);
        }
    });
    dadosRegistrojPanel.add(controlejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 75, 100, -1));

    jLabel2.setText("Condição de Pagamento");
    dadosRegistrojPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 25, -1, -1));

    jLabel3.setText("Data da Entrada");
    dadosRegistrojPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 25, -1, -1));

    jLabel4.setText("Tipo de Documento");
    dadosRegistrojPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 25, -1, -1));

    jLabel5.setText("Valor Encargos ");
    dadosRegistrojPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

    jLabel6.setText("Valor do Desconto");
    dadosRegistrojPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, -1, -1));

    jLabel7.setText("Valor dos Produtos");
    dadosRegistrojPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 65, -1, -1));

    jLabel8.setText("Situação da Entrada");
    dadosRegistrojPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 65, -1, -1));

    jLabel15.setText("Valor Total ");
    dadosRegistrojPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 65, -1, -1));

    buscaBancojButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    buscaBancojButton3.setToolTipText("Consultar Fornecedor");
    buscaBancojButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscaBancojButton3ActionPerformed(evt);
        }
    });
    dadosRegistrojPanel.add(buscaBancojButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 20, 20));

    jPanel2.add(dadosRegistrojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 960, 140));

    dadosNotafiscaljPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Nota Fiscal"));
    dadosNotafiscaljPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    numerojTextField.setEnabled(false);
    numerojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            numerojTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            numerojTextFieldFocusLost(evt);
        }
    });
    dadosNotafiscaljPanel.add(numerojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 90, -1));

    dataEmissaojDateChooser.setEnabled(false);
    dataEmissaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataEmissaojDateChooserFocusGained(evt);
        }
    });
    dadosNotafiscaljPanel.add(dataEmissaojDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 35, 100, -1));

    dataSaidajDateChooser.setEnabled(false);
    dataSaidajDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataSaidajDateChooserFocusGained(evt);
        }
    });
    dadosNotafiscaljPanel.add(dataSaidajDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 35, 100, -1));

    especiejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NF-e", "NFF", "NF" }));
    especiejComboBox.setEnabled(false);
    dadosNotafiscaljPanel.add(especiejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 35, 90, -1));

    seriejTextField.setEnabled(false);
    seriejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            seriejTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            seriejTextFieldFocusLost(evt);
        }
    });
    dadosNotafiscaljPanel.add(seriejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 35, 100, -1));

    subSeriejTextField.setEnabled(false);
    subSeriejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            subSeriejTextFieldFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            subSeriejTextFieldFocusLost(evt);
        }
    });
    dadosNotafiscaljPanel.add(subSeriejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 35, 80, -1));

    jLabel9.setText("Número");
    dadosNotafiscaljPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    jLabel10.setText("Data Emissão");
    dadosNotafiscaljPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

    jLabel11.setText("Data Saída");
    dadosNotafiscaljPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

    jLabel12.setText("Especie");
    dadosNotafiscaljPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

    jLabel13.setText("Série");
    dadosNotafiscaljPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

    jLabel14.setText("Sub-Serie");
    dadosNotafiscaljPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

    gerarRecibojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    gerarRecibojButton.setToolTipText("Gerar Numero Pedido ou Recibo");
    gerarRecibojButton.setEnabled(false);
    gerarRecibojButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            gerarRecibojButtonActionPerformed(evt);
        }
    });
    dadosNotafiscaljPanel.add(gerarRecibojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 35, 20, 20));

    jPanel2.add(dadosNotafiscaljPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 960, 70));

    xmljPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Carregar XML NF-e"));
    xmljPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel17.setText("Local de Armazenamento do Arquivo");
    xmljPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 31, -1, -1));

    caminhojTextField.setEditable(false);
    xmljPanel.add(caminhojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, -1));

    limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    limparjButton.setText("Limpar");
    limparjButton.setToolTipText("Limpar dados do Arquivo NF-e");
    limparjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            limparjButtonActionPerformed(evt);
        }
    });
    xmljPanel.add(limparjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

    localizarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    localizarjButton.setText("Localizar");
    localizarjButton.setToolTipText("Localizar Arquivo NF-e");
    localizarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            localizarjButtonActionPerformed(evt);
        }
    });
    xmljPanel.add(localizarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

    carregarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    carregarjButton.setText("Carregar");
    carregarjButton.setToolTipText("Carregar dados da NF-e");
    carregarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            carregarjButtonActionPerformed(evt);
        }
    });
    xmljPanel.add(carregarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

    jLabel16.setText("Versão NF-e");
    xmljPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

    versaoNFejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3.10", "2.00" }));
    xmljPanel.add(versaoNFejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 100, -1));

    jPanel2.add(xmljPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 960, 130));

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento de Entrada"));
    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1065, -1));

    jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    confirmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    confirmajButton.setText("Confirma Compras");
    confirmajButton.setToolTipText("Confirma Registro de Compras");
    confirmajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmajButtonActionPerformed(evt);
        }
    });

    jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton11.setText("Fechar");
    jButton11.setToolTipText("Cancela Registro de Compras");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
        }
    });

    produtosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    produtosjButton.setText("Produtos");
    produtosjButton.setToolTipText("Confirma Registro de Compras");
    produtosjButton.setEnabled(false);
    produtosjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            produtosjButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
    jPanel15.setLayout(jPanel15Layout);
    jPanel15Layout.setHorizontalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel15Layout.createSequentialGroup()
            .addContainerGap(102, Short.MAX_VALUE)
            .addComponent(confirmajButton)
            .addGap(84, 84, 84)
            .addComponent(produtosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(71, 71, 71)
            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(90, 90, 90))
    );
    jPanel15Layout.setVerticalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel15Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(confirmajButton)
                .addComponent(jButton11)
                .addComponent(produtosjButton))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(131, 131, 131)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(91, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(387, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fornecedorjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fornecedorjTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new FrmConsultaFornecedor(this);
        }
    }//GEN-LAST:event_fornecedorjTextFieldKeyPressed

    private void dataEntradajDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataEntradajDateChooserFocusGained

    }//GEN-LAST:event_dataEntradajDateChooserFocusGained

    private void tipoDocumentojComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoDocumentojComboBoxFocusLost
        if (tipoDocumentojComboBox.getSelectedItem().equals("Nota Fiscal")){
            numerojTextField.setEnabled(true);
            dataEmissaojDateChooser.setEnabled(true);
            dataSaidajDateChooser.setEnabled(true);
            especiejComboBox.setEnabled(true);
            seriejTextField.setEnabled(true);
            subSeriejTextField.setEnabled(true);
            gerarRecibojButton.setEnabled(false);
        }else {
            numerojTextField.setEnabled(true);
            dataEmissaojDateChooser.setEnabled(true);
            dataSaidajDateChooser.setEnabled(false);
            especiejComboBox.setEnabled(false);
            seriejTextField.setEnabled(false);
            subSeriejTextField.setEnabled(false);
            gerarRecibojButton.setEnabled(true);
        }
    }//GEN-LAST:event_tipoDocumentojComboBoxFocusLost

    private void valorEncargosjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorEncargosjTextFieldFocusGained
        valorEncargosjTextField.selectAll();
    }//GEN-LAST:event_valorEncargosjTextFieldFocusGained

    private void valorEncargosjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorEncargosjTextFieldKeyReleased
        valorEncargosjTextField.setText(Formatacao.decinalValorMonetario(valorEncargosjTextField.getText()));
    }//GEN-LAST:event_valorEncargosjTextFieldKeyReleased

    private void valorDescontojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldFocusGained
        valorDescontojTextField.selectAll();
    }//GEN-LAST:event_valorDescontojTextFieldFocusGained

    private void valorDescontojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldFocusLost

    }//GEN-LAST:event_valorDescontojTextFieldFocusLost

    private void valorDescontojTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldKeyReleased
        valorDescontojTextField.setText(Formatacao.decinalValorMonetario(valorDescontojTextField.getText()));
    }//GEN-LAST:event_valorDescontojTextFieldKeyReleased

    private void valorProdutosjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProdutosjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProdutosjTextFieldActionPerformed

    private void valorProdutosjTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProdutosjTextFieldFocusGained
        valorProdutosjTextField.selectAll();
    }//GEN-LAST:event_valorProdutosjTextFieldFocusGained

    private void valorProdutosjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProdutosjTextFieldFocusLost

    }//GEN-LAST:event_valorProdutosjTextFieldFocusLost

    private void valorProdutosjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorProdutosjTextFieldKeyReleased
        valorProdutosjTextField.setText(Formatacao.decinalValorMonetario(valorProdutosjTextField.getText()));
    }//GEN-LAST:event_valorProdutosjTextFieldKeyReleased

    private void situacaojComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_situacaojComboBoxFocusLost
        numerojTextField.requestFocus();
    }//GEN-LAST:event_situacaojComboBoxFocusLost

    private void valorTotaljTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotaljTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTotaljTextFieldActionPerformed

    private void valorTotaljTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorTotaljTextFieldFocusGained
        valorTotaljTextField.selectAll();
    }//GEN-LAST:event_valorTotaljTextFieldFocusGained

    private void valorTotaljTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorTotaljTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTotaljTextFieldFocusLost

    private void valorTotaljTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorTotaljTextFieldKeyReleased
        valorTotaljTextField.setText(Formatacao.decinalValorMonetario(valorTotaljTextField.getText()));
    }//GEN-LAST:event_valorTotaljTextFieldKeyReleased

    private void controlejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlejButtonActionPerformed

    }//GEN-LAST:event_controlejButtonActionPerformed

    private void buscaBancojButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBancojButton3ActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_buscaBancojButton3ActionPerformed

    private void numerojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numerojTextFieldFocusGained
        numerojTextField.selectAll();
    }//GEN-LAST:event_numerojTextFieldFocusGained

    private void numerojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numerojTextFieldFocusLost

    }//GEN-LAST:event_numerojTextFieldFocusLost

    private void dataEmissaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataEmissaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEmissaojDateChooserFocusGained

    private void dataSaidajDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataSaidajDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSaidajDateChooserFocusGained

    private void seriejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seriejTextFieldFocusGained
        seriejTextField.selectAll();
    }//GEN-LAST:event_seriejTextFieldFocusGained

    private void seriejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seriejTextFieldFocusLost

    }//GEN-LAST:event_seriejTextFieldFocusLost

    private void subSeriejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subSeriejTextFieldFocusGained
        subSeriejTextField.selectAll();
    }//GEN-LAST:event_subSeriejTextFieldFocusGained

    private void subSeriejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subSeriejTextFieldFocusLost

    }//GEN-LAST:event_subSeriejTextFieldFocusLost

    private void gerarRecibojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRecibojButtonActionPerformed
        ParametroLocalController parametroLocalController = new ParametroLocalController();
        ParametrosLocal parametros = new ParametrosLocal();
        parametros.setIdparametros(1);
        parametros = parametroLocalController.localizarEmpresa(config.getEmpresa().getIdparametros());
        int codigo=0;
        if (parametros!=null){
            codigo = parametros.getNumeroReciboEntrada();
            codigo = codigo + 1;
            numerojTextField.setText(String.valueOf(codigo));
            parametros.setNumeroReciboEntrada(codigo);
            parametroLocalController.salvar(parametros);
        }
    }//GEN-LAST:event_gerarRecibojButtonActionPerformed

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        caminhojTextField.setText("");
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void localizarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarjButtonActionPerformed
        new FrmLocalizarArquivo(this);
    }//GEN-LAST:event_localizarjButtonActionPerformed

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        if (docEntrada.getIdDocEntrada()==null){
            docEntrada.setDataEntrada(dataEntradajDateChooser.getDate());
        }
        docEntrada.setCondicaoPagamento(condicaoPagamentojComboBox.getSelectedItem().toString());
        docEntrada.setEmpresa(config.getEmpresa().getIdempresa());
        docEntrada.setFornecedor(fornecedor.getIdfornecedor());
        docEntrada.setSituacao(situacaojComboBox.getSelectedItem().toString());
        docEntrada.setTipoDocumento(tipoDocumentojComboBox.getSelectedItem().toString());
        if (valorDescontojTextField.getText().length()>0){
            docEntrada.setValorDesconto(Formatacao.formatarStringfloat(valorDescontojTextField.getText()));
        }else docEntrada.setValorDesconto(0.0f);
        if (valorEncargosjTextField.getText().length()>0){
            docEntrada.setValorEncargos(Formatacao.formatarStringfloat(valorEncargosjTextField.getText()));
        }else docEntrada.setValorEncargos(0.0f);
        if (valorTotaljTextField.getText().length()>0){
            docEntrada.setValorTotal(Formatacao.formatarStringfloat(valorTotaljTextField.getText()));
        }else docEntrada.setValorTotal(0.0f);
        EntradaProdutoController entradaProdutoController = new EntradaProdutoController();
        docEntrada = entradaProdutoController.salvarDocEntrada(docEntrada);
        if (notaFiscal == null) {
            notaFiscal = new Nfentrada();
            if (docEntrada.getTipoDocumento().equalsIgnoreCase("Nota Fiscal")) {
                notaFiscal.setArquivonfe(xmlNfe);
                notaFiscal.setDataEmissao(dataEmissaojDateChooser.getDate());
                notaFiscal.setDataSaida(dataSaidajDateChooser.getDate());
                notaFiscal.setEspecie(especiejComboBox.getSelectedItem().toString());
                notaFiscal.setNumero(numerojTextField.getText());
                notaFiscal.setSerie(seriejTextField.getText());
                notaFiscal.setSubSerie(subSeriejTextField.getText());
            }
            notaFiscal.setTipoDocumento(tipoDocumentojComboBox.getSelectedItem().toString());
            if (valorProdutosjTextField.getText().length() > 0) {
                notaFiscal.setValorProdutos(Formatacao.formatarStringfloat(valorProdutosjTextField.getText()));
            } else {
                notaFiscal.setValorProdutos(0.0f);
            }
            notaFiscal.setValorTotal(docEntrada.getValorTotal());
            notaFiscal.setDocentrada(docEntrada.getIdDocEntrada());
            notaFiscal = entradaProdutoController.salvarEntradaNF(notaFiscal);
        }
        produtosjButton.setEnabled(true);
        confirmajButton.setEnabled(false);
        new FrmNovaEntrada(config, docEntrada, notaFiscal, listaDuplicata, listaProdutos, nota);
        
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void produtosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosjButtonActionPerformed
        new FrmNovaEntrada(config, docEntrada, notaFiscal, listaDuplicata, listaProdutos, nota);
    }//GEN-LAST:event_produtosjButtonActionPerformed

    private void carregarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarjButtonActionPerformed
        if (caminhojTextField.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Selecione o arquivo.");
        } else {
            try {
                if (versaoNFejComboBox.getSelectedItem().toString().equalsIgnoreCase("2.00")){
                    this.nfe = new LerXml200(caminhojTextField.getText(), this);
                }else {
                    this.nfe = new LerXml310(caminhojTextField.getText(), this);
                }
                
                try {
                    this.nfe.lerNotaFiscal();
                } catch (ParseException ex) {
                    Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    this.nfe.lerFornecedor();
                } catch (Exception ex) {
                    Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.nfe.lerProdutos();
                try {
                    this.nfe.lerDuplicatas();
                } catch (ParseException ex) {
                    Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SAXException ex) {
                Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_carregarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaBancojButton3;
    private javax.swing.JTextField caminhojTextField;
    private javax.swing.JButton carregarjButton;
    private javax.swing.JComboBox condicaoPagamentojComboBox;
    private javax.swing.JButton confirmajButton;
    private javax.swing.JButton controlejButton;
    private javax.swing.JPanel dadosNotafiscaljPanel;
    private javax.swing.JPanel dadosRegistrojPanel;
    private com.toedter.calendar.JDateChooser dataEmissaojDateChooser;
    private com.toedter.calendar.JDateChooser dataEntradajDateChooser;
    private com.toedter.calendar.JDateChooser dataSaidajDateChooser;
    private javax.swing.JComboBox especiejComboBox;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JButton gerarRecibojButton;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton limparjButton;
    private javax.swing.JButton localizarjButton;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JButton produtosjButton;
    private javax.swing.JTextField seriejTextField;
    private javax.swing.JComboBox situacaojComboBox;
    private javax.swing.JTextField subSeriejTextField;
    private javax.swing.JComboBox tipoDocumentojComboBox;
    private javax.swing.JTextField valorDescontojTextField;
    private javax.swing.JTextField valorEncargosjTextField;
    private javax.swing.JTextField valorProdutosjTextField;
    private javax.swing.JTextField valorTotaljTextField;
    private javax.swing.JComboBox versaoNFejComboBox;
    private javax.swing.JPanel xmljPanel;
    // End of variables declaration//GEN-END:variables

    public void setData(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setBanco(Banco banco) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setModelProduto(Produto produto, Estoque estoque) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setNFe(List<NfProdutos> listaProdutos, List<NfDuplicatas> listaDuplicatas, NotaEletronica nota, Fornecedor fornecedor) {
        this.nota = nota;
        this.listaDuplicata = listaDuplicatas;
        this.listaProdutos = listaProdutos;
        this.fornecedor= fornecedor;
        setCamposNFe();
    }

    public void setAlterarValorVenda(Estoque estoque) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setFornecedor(Object objeto) {
        this.fornecedor = (Fornecedor) objeto;
        fornecedorjTextField.setText(fornecedor.getRazaoSocial());
    }

    public void setForPedido(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setPlanoContas(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setCliente(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setProdutoXML(Produto produto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setArquivo(File arquivo) {
        if (arquivo!=null){
            caminhojTextField.setText(arquivo.getPath());
            try {
                gerarArquivoBanco(arquivo);
            } catch (IOException ex) {
                Logger.getLogger(FrmNovaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void gerarArquivoBanco(File arquivo) throws IOException {
        File file = arquivo;
        InputStream is = new FileInputStream(file);
        xmlNfe = new byte[(int) file.length()];
        int offset = 0;
        int numRead = 0;
        while (offset < xmlNfe.length
                && (numRead = is.read(xmlNfe, offset, xmlNfe.length - offset)) >= 0) {
            offset += numRead;
        }
    }
    
    public void carregarDadosDocEntrada(){
        FornecedorController fornecedorController = new FornecedorController();
        fornecedor = fornecedorController.consultarFornecedor(docEntrada.getFornecedor());
        fornecedorjTextField.setText(fornecedor.getRazaoSocial());
        dataEntradajDateChooser.setDate(docEntrada.getDataEntrada());
        tipoDocumentojComboBox.setSelectedItem(docEntrada.getTipoDocumento());
        condicaoPagamentojComboBox.setSelectedItem(docEntrada.getCondicaoPagamento());
        valorEncargosjTextField.setText(Formatacao.foramtarFloatString(docEntrada.getValorEncargos()));
        valorDescontojTextField.setText(Formatacao.foramtarFloatString(docEntrada.getValorDesconto()));
        valorProdutosjTextField.setText(Formatacao.foramtarFloatString(docEntrada.getValorTotal()));
        situacaojComboBox.setSelectedItem(docEntrada.getSituacao());
        EntradaProdutoController entradaProdutoController = new EntradaProdutoController();
        notaFiscal = entradaProdutoController.consultarNotaFiscalEntrada(docEntrada.getIdDocEntrada());
        //Preencher Dados Nota Fiscal
        if (notaFiscal != null) {
            numerojTextField.setText(notaFiscal.getNumero());
            dataEmissaojDateChooser.setDate(notaFiscal.getDataEmissao());
            dataSaidajDateChooser.setDate(notaFiscal.getDataSaida());
            especiejComboBox.setSelectedItem(notaFiscal.getEspecie());
            seriejTextField.setText(notaFiscal.getSerie());
            subSeriejTextField.setText(notaFiscal.getSubSerie());
            valorProdutosjTextField.setText(Formatacao.foramtarFloatString(notaFiscal.getValorProdutos()));
            valorTotaljTextField.setText(Formatacao.foramtarFloatString(notaFiscal.getValorTotal()));
            xmlNfe = notaFiscal.getArquivonfe();
        }
    }
    
    public void setCamposNFe() {

        //Preenche os dados da Entrada


        docEntrada.setFornecedor(fornecedor.getIdfornecedor());
        docEntrada.setCondicaoPagamento(nota.getFormaPagamento());
        docEntrada.setDataEntrada(new Date());
        docEntrada.setTipoDocumento("Nota Fiscal");
        docEntrada.setValorDesconto(nota.getValorDesconto());
        docEntrada.setValorEncargos(nota.getValorOutrasDespesass());
        docEntrada.setEmpresa(config.getEmpresa().getIdempresa());
        fornecedorjTextField.setText(fornecedor.getRazaoSocial());
        tipoDocumentojComboBox.setSelectedItem("Nota Fiscal");
        condicaoPagamentojComboBox.setSelectedItem(this.nota.getFormaPagamento());
        valorEncargosjTextField.setText(Formatacao.foramtarFloatString(this.nota.getValorOutrasDespesass() + this.nota.getValorFrete()));
        valorDescontojTextField.setText(Formatacao.foramtarFloatString(this.nota.getValorDesconto()));
        valorProdutosjTextField.setText(Formatacao.foramtarFloatString(this.nota.getValorProdutos()));
        valorTotaljTextField.setText(Formatacao.foramtarFloatString(this.nota.getValorTotal()));

        //Preenche os dados da Nota Fiscal

        numerojTextField.setText(this.nota.getNumero());
        dataEmissaojDateChooser.setDate(this.nota.getDataEmissao());
        if (this.nota.getDataSaida()==null){
            dataSaidajDateChooser.setDate(this.nota.getDataEmissao());
        }else dataSaidajDateChooser.setDate(this.nota.getDataSaida());
        especiejComboBox.setSelectedItem("NF-e");
        seriejTextField.setText(this.nota.getSerie());
        subSeriejTextField.setText(this.nota.getSubSerie());
        if (this.docEntrada.getFornecedor()==0){
            new FrmCadastrarFornecedor(fornecedor, this);
        }


    }


}
