/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConfiguracao.java
 *
 * Created on 21/11/2009, 15:28:46
 */

package telas;

import Regras.CestController;
import Regras.ProdutoController;
import controler.ConfiguracaoSistema;
import controler.Sigap;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cest;
import model.Produto;

/**
 *
 * @author Acer
 */
public class FrmConfiguracao extends javax.swing.JFrame {

    /** Creates new form FrmConfiguracao */
        private ConfiguracaoSistema configura = new ConfiguracaoSistema();

    public FrmConfiguracao() {
        initComponents();
        poputalTela();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    public void poputalTela(){
        Sigap utilitario = new Sigap();
        configura = (ConfiguracaoSistema) utilitario.deserializarConfiguracao();
        if (configura!=null){


        emailSenhajPasswordField.setText(configura.getEmailSenha());
        emailjTextField.setText(configura.getEmailOrigem());
        smtpjTextField.setText(configura.getEmailSmtp());
        dbLocaljTextField1.setText(configura.getBdlocal());
        dbPortajTextField.setText(configura.getBdporta());
        dbSenhaSenhajPasswordField1.setText(configura.getBdSenha());
        dbUsuariojTextField.setText(configura.getBdusuario());
        dbNomejTextField.setText(configura.getBdNome());
        
        //conexão Remota
        
        remotaLocaljTextField.setText(configura.getRemotolocal());
        remotaNomejTextField.setText(configura.getRemotoNome());
        remotaPortajTextField.setText(configura.getRemotoporta());
        remotaSenhajPasswordField.setText(configura.getRemotoSenha());
        remotaUsuariojTextField.setText(configura.getRemotousuario());
        
        //tipoCodigojTextField.setText(configura.getTipoCodigo());
        
        
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        emailSenhajPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        smtpjTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        dbUsuariojTextField = new javax.swing.JTextField();
        dbSenhaSenhajPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dbLocaljTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dbPortajTextField = new javax.swing.JTextField();
        dbNomejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        remotaUsuariojTextField = new javax.swing.JTextField();
        remotaSenhajPasswordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        remotaLocaljTextField = new javax.swing.JTextField();
        remotaNomejTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        remotaPortajTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tipoCodigojTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        SalvarjButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Email Cliente");

        jLabel2.setText("Senha SMTP");

        jLabel3.setText("SMTP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailSenhajPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3)
                    .addComponent(smtpjTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailSenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smtpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Email", jPanel2);

        jLabel4.setText("Senha Banco");

        jLabel5.setText("Local");

        jLabel6.setText("Usuario");

        jLabel7.setText("Porta");

        jLabel8.setText("Nome Banco");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dbUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbSenhaSenhajPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dbLocaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dbPortajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbSenhaSenhajPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbLocaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbPortajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Banco de Dados", jPanel3);

        jLabel9.setText("Usuario");

        jLabel10.setText("Senha Banco");

        jLabel11.setText("Local");

        jLabel12.setText("Nome Banco");

        jLabel13.setText("Porta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(remotaUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remotaSenhajPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(remotaLocaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remotaNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(remotaPortajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remotaUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remotaSenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remotaLocaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remotaPortajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remotaNomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Conexão Remota", jPanel5);

        jLabel14.setText("Tipo Código");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoCodigojTextField))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoCodigojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Parametros", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        SalvarjButton.setText("Salvar");
        SalvarjButton.setToolTipText("Salvar Arquivo");
        SalvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SalvarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jButton4.setText("Fechar");
        jButton4.setToolTipText("Fechar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4fecharMovimentoCaixa(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButtonActionPerformed
        configura.setEmailOrigem(emailjTextField.getText());
        configura.setEmailSmtp(smtpjTextField.getText());
        String senha="";
        char[] email = emailSenhajPasswordField.getPassword();
        for (int i=0;i<email.length;i++){
            senha+=email[i];
        }
        configura.setEmailSenha(senha);
        configura.setBdlocal(dbLocaljTextField1.getText());
        configura.setBdporta(dbPortajTextField.getText());
        configura.setBdNome(dbNomejTextField.getText());
        configura.setBdusuario(dbUsuariojTextField.getText());
        senha="";
        char[] db = dbSenhaSenhajPasswordField1.getPassword();
        for (int i=0;i<db.length;i++){
            senha+=db[i];
        }
        configura.setBdSenha(senha);
        
        //Conexão remota
        
        configura.setRemotoNome(remotaNomejTextField.getText());
        configura.setRemotolocal(remotaLocaljTextField.getText());
        configura.setRemotoporta(remotaPortajTextField.getText());
        configura.setRemotousuario(remotaUsuariojTextField.getText());
        senha="";
        db = remotaSenhajPasswordField.getPassword();
        for (int i=0;i<db.length;i++){
            senha+=db[i];
        }
        configura.setRemotoSenha(senha);
        
        
        
        Sigap utilitario = new Sigap();
        try{
            utilitario.serelizarConfiguracao(configura);
            JOptionPane.showMessageDialog(null,"Arquivo Gravado com Sucesso");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao Gravar\n" + ex);

        }
        this.dispose();

}//GEN-LAST:event_SalvarjButtonActionPerformed

    private void jButton4fecharMovimentoCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4fecharMovimentoCaixa
        this.dispose();
//        VendaController vendaController = new VendaController();
//        List<Venda> listaVendas = vendaController.listarVendaPeriodo("2016-12-23", "2017-01-01");
//        for (int i=0;i<listaVendas.size();i++){
//            List<Saida> listaSaida = vendaController.listarSaidaVenda(listaVendas.get(i).getIdvenda());
//            if (listaSaida!=null){
//                for (int j=0;j<listaSaida.size();j++){
//                    EstoqueController estoqueController = new EstoqueController();
//                    Estoque estoque = estoqueController.consultarEstoque(listaSaida.get(j).getProduto(), 2);
//                    if (estoque!=null){
//                        estoque.setQuantidadeEstoque(estoque.getQuantidadeEstoque() - listaSaida.get(j).getQuantidade());
//                        estoqueController.salvarEstoque(estoque);
//                    }
//                            
//                }
//            }
//        }
//        DevolucaoController devolucaoController = new DevolucaoController();
//        List<Viewrelatoriodevolucao> listaDevolucao = devolucaoController.relatorioDevolucao("2016-12-23", "2017-01-01", 0, "");
//        for (int i = 0; i < listaDevolucao.size(); i++) {
//            EstoqueController estoqueController = new EstoqueController();
//            Estoque estoque = estoqueController.consultarEstoque(listaDevolucao.get(i).getProdutoIdproduto(), 2);
//            if (estoque != null) {
//                estoque.setQuantidadeEstoque(estoque.getQuantidadeEstoque() + listaDevolucao.get(i).getQuantidadeDevolucao());
//                estoqueController.salvarEstoque(estoque);
//            }
//        }
        
          //this.dispose();
//        EntradaProdutoController entradaProdutoController = new EntradaProdutoController();
//        List<Docentrada> listaVendas = entradaProdutoController.pesquisarEntradaPeriodo("2016-12-23", "2017-01-01",2);
//        for (int i=0;i<listaVendas.size();i++){
//            List<Entradaproduto> listaSaida = entradaProdutoController.listarEntradaProduto(listaVendas.get(i));
//            if (listaSaida!=null){
//                for (int j=0;j<listaSaida.size();j++){
//                    EstoqueController estoqueController = new EstoqueController();
//                    Estoque estoque = estoqueController.consultarEstoque(listaSaida.get(j).getProduto(), 2);
//                    if (estoque!=null){
//                        estoque.setQuantidadeEstoque(estoque.getQuantidadeEstoque() + listaSaida.get(j).getQuantidade());
//                        estoqueController.salvarEstoque(estoque);
//                    }
//                            
//                }
//            }
//        }
//        JOptionPane.showMessageDialog(rootPane, "Terminou");
}//GEN-LAST:event_jButton4fecharMovimentoCaixa

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfiguracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarjButton;
    private javax.swing.JTextField dbLocaljTextField1;
    private javax.swing.JTextField dbNomejTextField;
    private javax.swing.JTextField dbPortajTextField;
    private javax.swing.JPasswordField dbSenhaSenhajPasswordField1;
    private javax.swing.JTextField dbUsuariojTextField;
    private javax.swing.JPasswordField emailSenhajPasswordField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField remotaLocaljTextField;
    private javax.swing.JTextField remotaNomejTextField;
    private javax.swing.JTextField remotaPortajTextField;
    private javax.swing.JPasswordField remotaSenhajPasswordField;
    private javax.swing.JTextField remotaUsuariojTextField;
    private javax.swing.JTextField smtpjTextField;
    private javax.swing.JTextField tipoCodigojTextField;
    // End of variables declaration//GEN-END:variables

    public void corrigirCest(){
        List<Cest> lista = new ArrayList<Cest>();
        CestController cestController = new CestController();
        lista = cestController.listar("");
        if (lista!=null){
            for(int i=0;i<lista.size();i++){
               gravarNCM(lista.get(i));
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Terminou");
    }
    
    public void gravarNCM(Cest cest){
        String novoNCM="";
        for(int i=0;i<cest.getNcm().length();i++){
            if (cest.getNcm().charAt(i)!='.'){
                novoNCM = novoNCM + cest.getNcm().charAt(i);
            }
        }
        if (cest.getId()>800){
            System.out.println(cest.getNcm());
        }
        CestController cestController = new CestController();
        cest.setNcm(novoNCM);
        cestController.salvar(cest);
    }
    
    public void atualizarCEST(){
        ProdutoController produtoController = new ProdutoController();
        List<Produto> lista =produtoController.consultarProduto();
        CestController cestController = new CestController();
        for (int i=0;i<lista.size();i++){
            Cest cest = cestController.cunsultarCest(lista.get(i).getNcm());
            if (cest!=null){
                lista.get(i).setCest(cest.getCest());
                produtoController.salvarProduto(lista.get(i));
            }
        }
        JOptionPane.showMessageDialog(rootPane,"Terminou");
    }
    
    public void atualizarCESTGrupo(){
        ProdutoController produtoController = new ProdutoController();
        List<Produto> lista =produtoController.consultarProdutoSemCEST();
        CestController cestController = new CestController();
        for (int i=0;i<lista.size();i++){
            String ncm = lista.get(i).getNcm();
            if (ncm.length()>4){
                ncm = ncm.substring(0, 4);
            }
            Cest cest = cestController.cunsultarCest(ncm);
            if (cest!=null){
                lista.get(i).setCest(cest.getCest());
                produtoController.salvarProduto(lista.get(i));
            }
        }
        JOptionPane.showMessageDialog(rootPane,"Terminou");
    }


}
