/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on 23/09/2009, 20:11:05
 */

package telas;


import Regras.AcessoController;
import Regras.EstoqueController;
import Regras.ParametroLocalController;
import Regras.ProdutoController;
import Singleton.ConexaoSingleton;
import controler.Config;
import controler.UsuarioLogado;
import controler.relatoriosJasper;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Estoque;
import model.ParametrosLocal;
import model.Produto;
import model.Usuarios;
import telas.Cliente.FrmConsultaClientes;
import telas.ConfiguracaoECF.FrmConfigEcf;
import telas.ContasPagar.FrmConsultaContasPagar;
import telas.ContasReceber.FrmConsultaContasReceber;
import telas.ControleCheques.FrmControleCheques;
import telas.Devolucao.Defeito.FrmConsultaDevolucaoDefeito;
import telas.Devolucao.FrmRelatorioDevolucao;
import telas.Encerramento.FrmConsultarEncerramento;
import telas.Entrada.FrmConsultaEntrada;
import telas.Entrada.FrmConsultarSituacaoEntrada;
import telas.Estoque.FrmRelatorioEstoque;
import telas.Fechamento.FrmFechamento;
import telas.ForPedido.FrmConsultaForPedido;
import telas.FormasPagamento.FrmConsultaFormaPagamento;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.GrupoProduto.FrmGrupoProduto;
import telas.NotaSaida.FrmConsultaNotaSaida;
import telas.PlanoContas.FrmConsultaPlanoContas;
import telas.PrevisaoFinanceira.FrmPosicaoFinanceira;
import telas.Produtos.FrmConsultaProdutos;
import telas.RelatorioVendas.FrmRelatorioGiro;
import telas.RelatorioVendas.FrmRelatorioVenda;
import telas.RelatorioVendas.FrmRelatorioVendedor;
import telas.RelatoriosGerenciais.FrmMovimentoFinanceiro;
import telas.RelatoriosGerenciais.FrmRelatorioData;
import telas.Transferencia.FrmConsultaTransferencia;
import telas.TransferenciaSaida.FrmConsultaTransferenciaSaida;
import telas.VendasPrazo.FrmConsultarVendasPrazo;
import telas.Vendedor.FrmConsultaVendedor;
import telas.movimentoBanco.FrmConsultaBanco;
import telas.movimentoCaixa.FrmConsultaCaixa;


/**
 *
 * @author Gabi
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /** Creates new form FrmPrincipal */
    
    private Config config = new Config();
    private UsuarioLogado usuarioLogado;
   

  
    public FrmPrincipal(Usuarios usuario) {
        this.usuarioLogado = new UsuarioLogado();
        this.usuarioLogado.setUsuario(usuario);
        carregarAcessoUsuario();
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
        }
        config.carregarConfiguracao();
        this.setTitle("      jGDynamic - " + config.getEmpresa().getNomeFantasia());
        usuariologadojLabel.setText("Usuário Logado : " + this.usuarioLogado.getUsuario().getNome());
        nomeFantasiajLabel.setText(config.getEmpresa().getNomeFantasia());
        razaoSocialjLabel.setText(config.getEmpresa().getRazaoSocial());
        this.setVisible(true);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        cadastrojPanel = new javax.swing.JPanel();
        adicionarPlanoContasjButton4 = new javax.swing.JButton();
        consutlaClientejButton = new javax.swing.JButton();
        excluirPlanoContasjButton1 = new javax.swing.JButton();
        imprimirjButton1 = new javax.swing.JButton();
        imprimirjButton3 = new javax.swing.JButton();
        imprimirjButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        imprimirjButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        adicionarPlanoContasjButton = new javax.swing.JButton();
        registrarTransferenciajButton = new javax.swing.JButton();
        imprimirjButton = new javax.swing.JButton();
        registrarTransferenciajButton1 = new javax.swing.JButton();
        adicionarPlanoContasjButton3 = new javax.swing.JButton();
        devolucaoDefeitojButton = new javax.swing.JButton();
        consultaEntradajButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        adicionarPlanoContasjButton2 = new javax.swing.JButton();
        consultaBancojButton = new javax.swing.JButton();
        excluirPlanoContasjButton2 = new javax.swing.JButton();
        imprimirjButton2 = new javax.swing.JButton();
        excluirPlanoContasjButton3 = new javax.swing.JButton();
        imprimirjButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        adicionarPlanoContasjButton1 = new javax.swing.JButton();
        registrarTransferenciajButton2 = new javax.swing.JButton();
        imprimirjButton6 = new javax.swing.JButton();
        registrarTransferenciajButton3 = new javax.swing.JButton();
        adicionarPlanoContasjButton5 = new javax.swing.JButton();
        consultaEntradajButton1 = new javax.swing.JButton();
        usuariologadojLabel = new javax.swing.JLabel();
        nomeFantasiajLabel = new javax.swing.JLabel();
        razaoSocialjLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sairSistemajMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        usuariosjMenuItem = new javax.swing.JMenuItem();
        nivelAcessojMenuItem = new javax.swing.JMenuItem();
        parametrosjMenuItem = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGAP - Sistema de Gestão Integrada para Associações de Aposentados");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(860, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adicionarPlanoContasjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/cadprodutos.png"))); // NOI18N
        adicionarPlanoContasjButton4.setText("Produtos");
        adicionarPlanoContasjButton4.setToolTipText("Cadastro de Produtos");
        adicionarPlanoContasjButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton4.setName(""); // NOI18N
        adicionarPlanoContasjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButton4ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(adicionarPlanoContasjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 60));

        consutlaClientejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/cadclientes.png"))); // NOI18N
        consutlaClientejButton.setText("Clientes");
        consutlaClientejButton.setToolTipText("Cadastro de Clientes");
        consutlaClientejButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consutlaClientejButton.setMaximumSize(new java.awt.Dimension(80, 90));
        consutlaClientejButton.setMinimumSize(new java.awt.Dimension(80, 90));
        consutlaClientejButton.setPreferredSize(new java.awt.Dimension(80, 90));
        consutlaClientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consutlaClientejButtonActionPerformed(evt);
            }
        });
        cadastrojPanel.add(consutlaClientejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 60));

        excluirPlanoContasjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/cadfornecedores.png"))); // NOI18N
        excluirPlanoContasjButton1.setText("Fornecedores");
        excluirPlanoContasjButton1.setToolTipText("Cadastro de Fornecedores");
        excluirPlanoContasjButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        excluirPlanoContasjButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPlanoContasjButton1ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(excluirPlanoContasjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 60));

        imprimirjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/cadplanocontas.png"))); // NOI18N
        imprimirjButton1.setText("Plano Contas");
        imprimirjButton1.setToolTipText("Cadastro de Contas");
        imprimirjButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton1ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(imprimirjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 60));

        imprimirjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/cadvendedores.png"))); // NOI18N
        imprimirjButton3.setText("Vendedores");
        imprimirjButton3.setToolTipText("Cadastro de Vendedores");
        imprimirjButton3.setFocusable(false);
        imprimirjButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton3ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(imprimirjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 60));

        imprimirjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/finbanco.png"))); // NOI18N
        imprimirjButton4.setText("Grupo de Produto");
        imprimirjButton4.setToolTipText("Cadastro de Forma de Pagamento");
        imprimirjButton4.setFocusable(false);
        imprimirjButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton4ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(imprimirjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, 60));
        cadastrojPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, -1, -1));

        imprimirjButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cashier.png"))); // NOI18N
        imprimirjButton7.setText("Formas Pagto");
        imprimirjButton7.setToolTipText("Cadastro de Forma de Pagamento");
        imprimirjButton7.setFocusable(false);
        imprimirjButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton7.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton7.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton7.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton7ActionPerformed(evt);
            }
        });
        cadastrojPanel.add(imprimirjButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 60));

        jTabbedPane1.addTab("Cadastro", cadastrojPanel);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adicionarPlanoContasjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        adicionarPlanoContasjButton.setText("Compras");
        adicionarPlanoContasjButton.setToolTipText("Registro de Compras");
        adicionarPlanoContasjButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton.setName(""); // NOI18N
        adicionarPlanoContasjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButtonActionPerformed(evt);
            }
        });
        jPanel4.add(adicionarPlanoContasjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 60));

        registrarTransferenciajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        registrarTransferenciajButton.setText("Transferências");
        registrarTransferenciajButton.setToolTipText("Receber Transferência ");
        registrarTransferenciajButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarTransferenciajButton.setMaximumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton.setMinimumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton.setPreferredSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTransferenciajButtonActionPerformed(evt);
            }
        });
        jPanel4.add(registrarTransferenciajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 60));

        imprimirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estacertos.png"))); // NOI18N
        imprimirjButton.setText("Acertos");
        imprimirjButton.setToolTipText("Acerto de Estoque");
        imprimirjButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButtonActionPerformed(evt);
            }
        });
        jPanel4.add(imprimirjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 60));

        registrarTransferenciajButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/esttransferencias.png"))); // NOI18N
        registrarTransferenciajButton1.setText("Transferências");
        registrarTransferenciajButton1.setToolTipText("Transferência entre Lojas Emitidas");
        registrarTransferenciajButton1.setFocusable(false);
        registrarTransferenciajButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarTransferenciajButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTransferenciajButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(registrarTransferenciajButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 60));

        adicionarPlanoContasjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        adicionarPlanoContasjButton3.setText("Situação Entrada     ");
        adicionarPlanoContasjButton3.setToolTipText("Situação Entrada");
        adicionarPlanoContasjButton3.setFocusable(false);
        adicionarPlanoContasjButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton3.setName(""); // NOI18N
        adicionarPlanoContasjButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(adicionarPlanoContasjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 60));

        devolucaoDefeitojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estpedidos.png"))); // NOI18N
        devolucaoDefeitojButton.setText("Devolução Defeito");
        devolucaoDefeitojButton.setToolTipText("Pedidos de Compras");
        devolucaoDefeitojButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        devolucaoDefeitojButton.setMaximumSize(new java.awt.Dimension(80, 90));
        devolucaoDefeitojButton.setMinimumSize(new java.awt.Dimension(80, 90));
        devolucaoDefeitojButton.setPreferredSize(new java.awt.Dimension(80, 90));
        devolucaoDefeitojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucaoDefeitojButtonActionPerformed(evt);
            }
        });
        jPanel4.add(devolucaoDefeitojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, 60));

        consultaEntradajButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estpedidos.png"))); // NOI18N
        consultaEntradajButton2.setText("Pedidos");
        consultaEntradajButton2.setToolTipText("Pedidos de Compras");
        consultaEntradajButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultaEntradajButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEntradajButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(consultaEntradajButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 60));

        jTabbedPane1.addTab("Estoque", jPanel4);

        jPanel5.setLayout(null);

        adicionarPlanoContasjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/fincaixa.png"))); // NOI18N
        adicionarPlanoContasjButton2.setText("Caixa");
        adicionarPlanoContasjButton2.setToolTipText("Movimento de Caixa");
        adicionarPlanoContasjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton2.setName(""); // NOI18N
        adicionarPlanoContasjButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(adicionarPlanoContasjButton2);
        adicionarPlanoContasjButton2.setBounds(20, 30, 200, 60);

        consultaBancojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/finbanco.png"))); // NOI18N
        consultaBancojButton.setText("Banco");
        consultaBancojButton.setToolTipText("Movimento de Banco");
        consultaBancojButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultaBancojButton.setMaximumSize(new java.awt.Dimension(80, 90));
        consultaBancojButton.setMinimumSize(new java.awt.Dimension(80, 90));
        consultaBancojButton.setPreferredSize(new java.awt.Dimension(80, 90));
        consultaBancojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBancojButtonActionPerformed(evt);
            }
        });
        jPanel5.add(consultaBancojButton);
        consultaBancojButton.setBounds(20, 100, 200, 60);

        excluirPlanoContasjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/fincontrolecheque.png"))); // NOI18N
        excluirPlanoContasjButton2.setText("Fechamento");
        excluirPlanoContasjButton2.setToolTipText("Controle de Cheques Recebidos");
        excluirPlanoContasjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        excluirPlanoContasjButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPlanoContasjButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(excluirPlanoContasjButton2);
        excluirPlanoContasjButton2.setBounds(20, 170, 200, 60);

        imprimirjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/finreceber.png"))); // NOI18N
        imprimirjButton2.setText("Receber");
        imprimirjButton2.setToolTipText("Contras a Receber");
        imprimirjButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(imprimirjButton2);
        imprimirjButton2.setBounds(20, 240, 200, 60);

        excluirPlanoContasjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/fincontrolecheque.png"))); // NOI18N
        excluirPlanoContasjButton3.setText("Cheques");
        excluirPlanoContasjButton3.setToolTipText("Controle de Cheques Recebidos");
        excluirPlanoContasjButton3.setFocusable(false);
        excluirPlanoContasjButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        excluirPlanoContasjButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        excluirPlanoContasjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPlanoContasjButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(excluirPlanoContasjButton3);
        excluirPlanoContasjButton3.setBounds(20, 380, 200, 60);

        imprimirjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/finpagar.png"))); // NOI18N
        imprimirjButton5.setText("Pagar");
        imprimirjButton5.setToolTipText("Contras a Pagar");
        imprimirjButton5.setFocusable(false);
        imprimirjButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton5.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton5.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton5.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(imprimirjButton5);
        imprimirjButton5.setBounds(20, 310, 200, 60);

        jTabbedPane1.addTab("Financeiro", jPanel5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adicionarPlanoContasjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        adicionarPlanoContasjButton1.setText("NF-e Saida");
        adicionarPlanoContasjButton1.setToolTipText("Registro de Compras");
        adicionarPlanoContasjButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton1.setName(""); // NOI18N
        adicionarPlanoContasjButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(adicionarPlanoContasjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 60));

        registrarTransferenciajButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        registrarTransferenciajButton2.setText("NF-e Entrada");
        registrarTransferenciajButton2.setToolTipText("Receber Transferência ");
        registrarTransferenciajButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarTransferenciajButton2.setMaximumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton2.setMinimumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton2.setPreferredSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTransferenciajButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(registrarTransferenciajButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 60));

        imprimirjButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estacertos.png"))); // NOI18N
        imprimirjButton6.setToolTipText("Acerto de Estoque");
        imprimirjButton6.setEnabled(false);
        imprimirjButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imprimirjButton6.setMaximumSize(new java.awt.Dimension(80, 90));
        imprimirjButton6.setMinimumSize(new java.awt.Dimension(80, 90));
        imprimirjButton6.setPreferredSize(new java.awt.Dimension(80, 90));
        imprimirjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirjButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(imprimirjButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 60));

        registrarTransferenciajButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/esttransferencias.png"))); // NOI18N
        registrarTransferenciajButton3.setToolTipText("Transferência entre Lojas Emitidas");
        registrarTransferenciajButton3.setEnabled(false);
        registrarTransferenciajButton3.setFocusable(false);
        registrarTransferenciajButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registrarTransferenciajButton3.setMaximumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton3.setMinimumSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton3.setPreferredSize(new java.awt.Dimension(80, 90));
        registrarTransferenciajButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTransferenciajButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(registrarTransferenciajButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 60));

        adicionarPlanoContasjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estentradas.png"))); // NOI18N
        adicionarPlanoContasjButton5.setToolTipText("Situação Entrada");
        adicionarPlanoContasjButton5.setEnabled(false);
        adicionarPlanoContasjButton5.setFocusable(false);
        adicionarPlanoContasjButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adicionarPlanoContasjButton5.setMaximumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton5.setMinimumSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton5.setName(""); // NOI18N
        adicionarPlanoContasjButton5.setPreferredSize(new java.awt.Dimension(80, 90));
        adicionarPlanoContasjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPlanoContasjButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(adicionarPlanoContasjButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 60));

        consultaEntradajButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes02/estpedidos.png"))); // NOI18N
        consultaEntradajButton1.setToolTipText("Pedidos de Compras");
        consultaEntradajButton1.setEnabled(false);
        consultaEntradajButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consultaEntradajButton1.setMaximumSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton1.setMinimumSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton1.setPreferredSize(new java.awt.Dimension(80, 90));
        consultaEntradajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEntradajButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(consultaEntradajButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 60));

        jTabbedPane1.addTab("Gerencial", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 550));

        usuariologadojLabel.setForeground(new java.awt.Color(0, 0, 153));
        usuariologadojLabel.setText("Nome do Usuario");
        getContentPane().add(usuariologadojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        nomeFantasiajLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        nomeFantasiajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeFantasiajLabel.setText("Lojão do Alemão - CANASVIEIRAS");
        getContentPane().add(nomeFantasiajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 860, 50));

        razaoSocialjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        razaoSocialjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        razaoSocialjLabel.setText("Lenz Comércio de Materiais de Contrução Ltda ERIELI");
        getContentPane().add(razaoSocialjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 860, 50));

        jMenu1.setText("Arquivo");

        sairSistemajMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door.png"))); // NOI18N
        sairSistemajMenuItem.setText("Sair");
        sairSistemajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairSistemajMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairSistemajMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Gerencial");

        jMenuItem1.setText("Movimento Financeiro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem18.setText("Posição Financeira");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("Nota Fiscal Eletrônica");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem24.setText("Consultar Vendas Prazo");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuItem28.setText("Encerramento Anual");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem28);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuItem2.setText("Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu5.setText("Estoque");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Relação de Estoque Geral");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem20.setText("Relação de Estqoue Positivo");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);

        jMenuItem21.setText("Relação de Estqoue Zerado");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Relação de Estqoue Negativo");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem22);

        jMenuItem13.setText("Relação de Estoque Fornecedor");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setText("Relação de Estoque Grupo");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem27.setText("Relação Acerto");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem27);

        jMenuItem8.setText("Entrada e Saída");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenu4.add(jMenu5);

        jMenu8.setText("Vendas");

        jMenuItem9.setText("Saídas Produtos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Saída Período");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuItem11.setText("Saída Grupo Produtos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Saída Fornecedor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuItem16.setText("Vendas ST");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem16);

        jMenuItem17.setText("Giro de Produtos");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem23.setText("Vendedor");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenu4.add(jMenu8);

        jMenu6.setText("Devolução");

        jMenuItem6.setText("Produto");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jCheckBoxMenuItem1.setText("Período");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jCheckBoxMenuItem1);

        jMenu7.setText("Condição");

        jMenuItem5.setText("A Vista");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem7.setText("A Prazo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenu6.add(jMenu7);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Configuração");

        usuariosjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        usuariosjMenuItem.setText("Usuários");
        usuariosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(usuariosjMenuItem);

        nivelAcessojMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chart_organisation.png"))); // NOI18N
        nivelAcessojMenuItem.setText("Níveis de Acesso");
        nivelAcessojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelAcessojMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(nivelAcessojMenuItem);

        parametrosjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bricks.png"))); // NOI18N
        parametrosjMenuItem.setText("Parâmetros Sistema");
        parametrosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametrosjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(parametrosjMenuItem);

        jMenuItem15.setText("Funcoes");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem4.setText("Parametros Gerenciais");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem25.setText("Emissor ECF");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);

        jMenuItem26.setText("Verificar Estque");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem26);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairSistemajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairSistemajMenuItemActionPerformed
       System.exit(0);
    }//GEN-LAST:event_sairSistemajMenuItemActionPerformed

    private void nivelAcessojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelAcessojMenuItemActionPerformed
        //new FrmFuncoes(config);
    }//GEN-LAST:event_nivelAcessojMenuItemActionPerformed

    private void usuariosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosjMenuItemActionPerformed
       
    }//GEN-LAST:event_usuariosjMenuItemActionPerformed

    private void parametrosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametrosjMenuItemActionPerformed
        new FrmConfiguracao();
    }//GEN-LAST:event_parametrosjMenuItemActionPerformed

    private void adicionarPlanoContasjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButtonActionPerformed
        new FrmConsultaEntrada(config);
}//GEN-LAST:event_adicionarPlanoContasjButtonActionPerformed

    private void registrarTransferenciajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTransferenciajButtonActionPerformed
         new FrmConsultaTransferencia(config);
        
}//GEN-LAST:event_registrarTransferenciajButtonActionPerformed

    private void imprimirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButtonActionPerformed
        new FrmAcerto(config);
    }//GEN-LAST:event_imprimirjButtonActionPerformed

    private void consutlaClientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consutlaClientejButtonActionPerformed
        if (this.usuarioLogado.getAcesso().getCliente()==1){
            new FrmConsultaClientes(config, this.usuarioLogado);
        }else JOptionPane.showMessageDialog(cadastrojPanel, "Acesso Negado");
    }//GEN-LAST:event_consutlaClientejButtonActionPerformed

    private void excluirPlanoContasjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPlanoContasjButton1ActionPerformed
        new FrmConsultaFornecedor();
    }//GEN-LAST:event_excluirPlanoContasjButton1ActionPerformed

    private void imprimirjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton1ActionPerformed
        new FrmConsultaPlanoContas();
    }//GEN-LAST:event_imprimirjButton1ActionPerformed

    private void adicionarPlanoContasjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton2ActionPerformed
        new FrmConsultaCaixa(this.config);
    }//GEN-LAST:event_adicionarPlanoContasjButton2ActionPerformed

    private void consultaBancojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBancojButtonActionPerformed
        try {
            new FrmConsultaBanco(this.config);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultaBancojButtonActionPerformed

    private void excluirPlanoContasjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPlanoContasjButton2ActionPerformed
        new FrmFechamento(config, usuarioLogado);
    }//GEN-LAST:event_excluirPlanoContasjButton2ActionPerformed

    private void imprimirjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton2ActionPerformed
        new FrmConsultaContasReceber(config, usuarioLogado);
    }//GEN-LAST:event_imprimirjButton2ActionPerformed

    private void imprimirjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton3ActionPerformed
        if (usuarioLogado.getAcesso().getCadvendedor()==1){
            new FrmConsultaVendedor(config);
        }else JOptionPane.showMessageDialog(cadastrojPanel, "Acesso Negado");
        
    }//GEN-LAST:event_imprimirjButton3ActionPerformed

    private void imprimirjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton5ActionPerformed
        if (this.usuarioLogado.getAcesso().getContasPagar()==1){
            new FrmConsultaContasPagar(config, this.usuarioLogado, null);
        }else JOptionPane.showMessageDialog(null, "Acesso Negado");
        
    }//GEN-LAST:event_imprimirjButton5ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmMovimentoFinanceiro(config);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    ConexaoSingleton.fecharConexao();
    System.exit(0);
}//GEN-LAST:event_formWindowClosed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String url = ("telas/Estoque/reportRelacaoEstoque.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("idempresa", this.config.getEmpresa().getIdempresa());
            EstoqueController estoqueController = new EstoqueController();
            parameters = estoqueController.calcularTotaisEstoque(parameters, this.config.getEmpresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       ParametroLocalController parametroLocalController = new ParametroLocalController();
       ParametrosLocal  parametros = new ParametrosLocal();
       parametros.setIdparametros(1);
       int dias = Integer.parseInt(JOptionPane.showInputDialog("Informe Numero de Dias para Giro"));
       parametros = parametroLocalController.localizarEmpresa(config.getEmpresa().getIdparametros());
       parametros.setNumeroDias(dias);
       parametroLocalController.salvar(parametros);

}//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new FrmRelatorioDevolucao("periodo", config);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FrmRelatorioDevolucao("A VISTA", config);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new FrmRelatorioDevolucao("A PRAZO", config);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new FrmRelatorioDevolucao("produto", config);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new FrmRelatorioData(1, this.config);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new FrmRelatorioVenda(1, config);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new FrmRelatorioVenda(2, config);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new FrmRelatorioVenda(3, config);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        new FrmRelatorioVenda(4, config);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        new FrmRelatorioEstoque(1, config);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        new FrmRelatorioEstoque(3, config);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       // new FrmFuncoes(config);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void adicionarPlanoContasjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton3ActionPerformed

        new FrmConsultarSituacaoEntrada(config);     }//GEN-LAST:event_adicionarPlanoContasjButton3ActionPerformed

    private void registrarTransferenciajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTransferenciajButton1ActionPerformed
        new FrmConsultaTransferenciaSaida(config);
    }//GEN-LAST:event_registrarTransferenciajButton1ActionPerformed

    private void excluirPlanoContasjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPlanoContasjButton3ActionPerformed
        new FrmControleCheques(config, usuarioLogado, null);
    }//GEN-LAST:event_excluirPlanoContasjButton3ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new FrmRelatorioVenda(5, config);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void imprimirjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton4ActionPerformed
        new FrmGrupoProduto();
    }//GEN-LAST:event_imprimirjButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void adicionarPlanoContasjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton4ActionPerformed
        new FrmConsultaProdutos(config);
    }//GEN-LAST:event_adicionarPlanoContasjButton4ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new FrmRelatorioGiro(config);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new FrmPosicaoFinanceira();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void adicionarPlanoContasjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton1ActionPerformed
        new FrmConsultaNotaSaida(config, usuarioLogado);
    }//GEN-LAST:event_adicionarPlanoContasjButton1ActionPerformed

    private void registrarTransferenciajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTransferenciajButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarTransferenciajButton2ActionPerformed

    private void registrarTransferenciajButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTransferenciajButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarTransferenciajButton3ActionPerformed

    private void adicionarPlanoContasjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton5ActionPerformed

    private void consultaEntradajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEntradajButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaEntradajButton1ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new FrmConsultaNotaSaida(config, usuarioLogado);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        String url = ("telas/Estoque/reportRelacaoEstoquePositivo.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("idempresa", this.config.getEmpresa().getIdempresa());
            EstoqueController estoqueController = new EstoqueController();
            parameters = estoqueController.calcularTotaisEstoque(parameters, this.config.getEmpresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        String url = ("telas/Estoque/reportRelacaoEstoqueZerado.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("idempresa", this.config.getEmpresa().getIdempresa());
            EstoqueController estoqueController = new EstoqueController();
            parameters = estoqueController.calcularTotaisEstoque(parameters, this.config.getEmpresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        String url = ("telas/Estoque/reportRelacaoEstoqueNegativo.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("idempresa", this.config.getEmpresa().getIdempresa());
            EstoqueController estoqueController = new EstoqueController();
            parameters = estoqueController.calcularTotaisEstoque(parameters, this.config.getEmpresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        new FrmRelatorioVendedor(this.config);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void imprimirjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton7ActionPerformed
        new FrmConsultaFormaPagamento(config);
    }//GEN-LAST:event_imprimirjButton7ActionPerformed

    private void consultaEntradajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEntradajButton2ActionPerformed
        new FrmConsultaForPedido(config, null, null);
    }//GEN-LAST:event_consultaEntradajButton2ActionPerformed

    private void devolucaoDefeitojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucaoDefeitojButtonActionPerformed
        new FrmConsultaDevolucaoDefeito(config, usuarioLogado);
    }//GEN-LAST:event_devolucaoDefeitojButtonActionPerformed

    private void imprimirjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirjButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirjButton6ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        new FrmConsultarVendasPrazo(config);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        new FrmConfigEcf(config);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        verificarEstoqueDuplicado();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        new FrmRelatorioData(3, config);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        new FrmConsultarEncerramento(config, usuarioLogado);
    }//GEN-LAST:event_jMenuItem28ActionPerformed


    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarPlanoContasjButton;
    private javax.swing.JButton adicionarPlanoContasjButton1;
    private javax.swing.JButton adicionarPlanoContasjButton2;
    private javax.swing.JButton adicionarPlanoContasjButton3;
    private javax.swing.JButton adicionarPlanoContasjButton4;
    private javax.swing.JButton adicionarPlanoContasjButton5;
    private javax.swing.JPanel cadastrojPanel;
    private javax.swing.JButton consultaBancojButton;
    private javax.swing.JButton consultaEntradajButton1;
    private javax.swing.JButton consultaEntradajButton2;
    private javax.swing.JButton consutlaClientejButton;
    private javax.swing.JButton devolucaoDefeitojButton;
    private javax.swing.JButton excluirPlanoContasjButton1;
    private javax.swing.JButton excluirPlanoContasjButton2;
    private javax.swing.JButton excluirPlanoContasjButton3;
    private javax.swing.JButton imprimirjButton;
    private javax.swing.JButton imprimirjButton1;
    private javax.swing.JButton imprimirjButton2;
    private javax.swing.JButton imprimirjButton3;
    private javax.swing.JButton imprimirjButton4;
    private javax.swing.JButton imprimirjButton5;
    private javax.swing.JButton imprimirjButton6;
    private javax.swing.JButton imprimirjButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem nivelAcessojMenuItem;
    private javax.swing.JLabel nomeFantasiajLabel;
    private javax.swing.JMenuItem parametrosjMenuItem;
    private javax.swing.JLabel razaoSocialjLabel;
    private javax.swing.JButton registrarTransferenciajButton;
    private javax.swing.JButton registrarTransferenciajButton1;
    private javax.swing.JButton registrarTransferenciajButton2;
    private javax.swing.JButton registrarTransferenciajButton3;
    private javax.swing.JMenuItem sairSistemajMenuItem;
    private javax.swing.JLabel usuariologadojLabel;
    private javax.swing.JMenuItem usuariosjMenuItem;
    // End of variables declaration//GEN-END:variables
    public void carregarAcessoUsuario(){
        AcessoController acessoController = new AcessoController();
        this.usuarioLogado.setAcesso(acessoController.getAcessoUsuario(this.usuarioLogado.getUsuario().getIdusuarios()));
    }
    
    
    public void verificarEstoqueDuplicado(){
        List<Produto> listaProduto = new ArrayList<Produto>();
        List<Produto> listaDuplicados = new ArrayList<Produto>();
        ProdutoController produtoController = new ProdutoController();
        listaProduto = produtoController.consultarProduto();
        if (listaProduto!=null){
            EstoqueController estoqueController = new EstoqueController();
            for(int i=0;i<listaProduto.size();i++){
                List<Estoque> listaEstoque = estoqueController.consultaEstoqueProduto(listaProduto.get(i).getIdProduto(), config.getEmpresa().getIdempresa());
                if (listaEstoque!=null){
                    if (listaEstoque.size()>1){
                        listaDuplicados.add(listaProduto.get(i));
                    }
                }
            }
        }
        if (listaDuplicados!=null){
            for(int i=0;i<listaDuplicados.size();i++){
                System.out.println(listaDuplicados.get(i).getIdProduto());
            }
        }        JOptionPane.showMessageDialog(cadastrojPanel, "Terminou");
        
    }
}
