/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Vendedor.Relatorios;

import Interfaces.ItelaConsulta;
import Regras.Formatacao;
import beanController.NfDuplicatas;
import beanController.NfProdutos;
import beanController.NotaEletronica;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.Config;
import controler.relatoriosJasper;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Banco;
import model.Estoque;
import model.Fornecedor;
import model.Produto;
import model.Vendedor;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.Produtos.FrmConsultaProdutos;

/**
 *
 * @author Wolverine
 */
public class FrmRelatorioComissao extends javax.swing.JFrame implements ItelaConsulta{
    
    private Vendedor vendedor;
    private Fornecedor fornecedor;
    private Produto produto;
    private Config config;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;

    /**
     * Creates new form FrmRelatorioComissao
     */
    public FrmRelatorioComissao(Config config, Vendedor vendedor) {
        this.vendedor = vendedor;
        this.config = config;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        nomeVendedorjTextField.setText(vendedor.getNomeCompleto());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeVendedorjTextField = new javax.swing.JTextField();
        fornecedorjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        produtojTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dataInicialjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    dataFinaljDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel4 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
jButton3 = new javax.swing.JButton();
jButton4 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Relatório de Comissão");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Nome Vendedor");

nomeVendedorjTextField.setEditable(false);

fornecedorjTextField.setEditable(false);

jLabel2.setText("Fornecedor");

jLabel3.setText("Produto");

produtojTextField.setEditable(false);

jButton1.setText("Pesquisar");
jButton1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
    }
    });

    jButton2.setText("Pesquisar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    dataInicialjDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataInicialjDateChooserFocusGained(evt);
        }
    });

    dataFinaljDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataFinaljDateChooserFocusGained(evt);
        }
    });

    jLabel4.setText("Data Inicial");

    jLabel5.setText("Data Final");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(fornecedorjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(produtojTextField))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeVendedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(19, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nomeVendedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(produtojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    jButton3.setText("Confirmar");
    jButton3.setToolTipText("Confirmar Relatório");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 10, -1, -1));

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton4.setText("Fechar");
    jButton4.setToolTipText("Fechar Janela");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 110, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(57, 57, 57))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataInicialjDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataInicialjDateChooserFocusGained

    }//GEN-LAST:event_dataInicialjDateChooserFocusGained

    private void dataFinaljDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFinaljDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFinaljDateChooserFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String codigo = "V";
        String sql = null;
        if (produto!=null){
            codigo=codigo+"P";
        }
        if (fornecedor!=null){
            codigo=codigo+"F";
        }
        if (codigo.equalsIgnoreCase("V")){
            sql = gerarSqlVendedor();
        }else if (codigo.equalsIgnoreCase("VP")){
            sql = gerarSqlVendedorProduto();
        }else if (codigo.equalsIgnoreCase("VF")){
            sql = gerarSqlVendedorFornecedor();
        }else if (codigo.equalsIgnoreCase("VPF")){
            sql = gerarSqlVendedorFornecedorProduto();
        }
        gerarRelatorio(sql);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FrmConsultaProdutos(this, config, false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataInicialjDateChooser;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomeVendedorjTextField;
    private javax.swing.JTextField produtojTextField;
    // End of variables declaration//GEN-END:variables

    public String gerarSqlVendedor(){
        String sql = "Select venda.idvenda, vendedor.nomeCompleto, vendedor.situacao,"+
        "venda.dataVenda, saida.quantidade, saida.valorVenda, produto.referencia, produto.unidade,"+
        "produto.descricao from " ;
	sql = sql + " vendedor join venda on vendedor.idvendedor = venda.vendedor_idvendedor"+
            " join saida on venda.idvenda = saida.venda_idvenda" +
            " join produto on saida.produto_idProduto = produto.idProduto";
    
        sql = sql + " where  vendedor.idvendedor=" + vendedor.getIdvendedor() +
                    " and venda.dataVenda>='" + Formatacao.ConvercaoDataSql(dataInicialjDateChooser.getDate()) +
                    "' and venda.dataVenda<='" + Formatacao.ConvercaoDataSql(dataFinaljDateChooser.getDate())+
                    "' and venda.empresa_idempresa=" + config.getEmpresa().getIdempresa();
        sql = sql + " order by venda.dataVenda, produto.descricao";
        return sql;
    }
    
    public String gerarSqlVendedorProduto(){
        String sql = "Select venda.idvenda, vendedor.nomeCompleto, vendedor.situacao,"+
        "venda.dataVenda, saida.quantidade, saida.valorVenda, produto.referencia, produto.unidade,"+
        "produto.descricao from " ;
	sql = sql + " vendedor join venda on vendedor.idvendedor = venda.vendedor_idvendedor"+
            " join saida on venda.idvenda = saida.venda_idvenda" +
            " join produto on saida.produto_idProduto = produto.idProduto";
    
        sql = sql + " where  vendedor.idvendedor=" + vendedor.getIdvendedor() +  
                " and venda.dataVenda>='" + Formatacao.ConvercaoDataSql(dataInicialjDateChooser.getDate()) +
                    "' and venda.dataVenda<='" + Formatacao.ConvercaoDataSql(dataFinaljDateChooser.getDate())+
                "' and saida.produto_idproduto=" + produto.getIdProduto()+
                " and venda.empresa_idempresa=" + config.getEmpresa().getIdempresa();
        sql = sql + " order by venda.dataVenda, produto.descricao";
        return sql;
    }
    
    public String gerarSqlVendedorFornecedor(){
        String sql = "Select venda.idvenda, vendedor.nomeCompleto, vendedor.situacao,"+
        "venda.dataVenda, saida.quantidade, saida.valorVenda, produto.referencia, produto.unidade,"+
        "produto.descricao from " ;
	sql = sql + " vendedor join venda on vendedor.idvendedor = venda.vendedor_idvendedor"+
            " join saida on venda.idvenda = saida.venda_idvenda" +
            " join produto on saida.produto_idProduto = produto.idProduto" +
            " join vinculo on produto.idProduto = vinculo.produto_idProduto" +
            " join fornecedor on vinculo.fornecedor_idfornecedor = fornecedor.idfornecedor";
    
        sql = sql + " where  vendedor.idvendedor=" + vendedor.getIdvendedor() +  
                " and venda.dataVenda>='" + Formatacao.ConvercaoDataSql(dataInicialjDateChooser.getDate()) +
                    "' and venda.dataVenda<='" + Formatacao.ConvercaoDataSql(dataFinaljDateChooser.getDate())+
                "' and fornecedor.idfornecedor=" + fornecedor.getIdfornecedor() +
                " and venda.empresa_idempresa=" + config.getEmpresa().getIdempresa();
        sql = sql + " order by venda.dataVenda, produto.descricao";
        return sql;
    }
    
    public String gerarSqlVendedorFornecedorProduto(){
        String sql = "Select venda.idvenda, vendedor.nomeCompleto, vendedor.situacao,"+
        "venda.dataVenda, saida.quantidade, saida.valorVenda, produto.referencia, produto.unidade,"+
        "produto.descricao from " ;
	sql = sql + " vendedor join venda on vendedor.idvendedor = venda.vendedor_idvendedor"+
            " join saida on venda.idvenda = saida.venda_idvenda" +
            " join produto on saida.produto_idProduto = produto.idProduto" +
            " join vinculo on produto.idProduto = vinculo.produto_idProduto" +
            " join fornecedor on vinculo.fornecedor_idfornecedor = fornecedor.idfornecedor";
    
        sql = sql + " where  vendedor.idvendedor=" + vendedor.getIdvendedor() +  
                " and venda.dataVenda>='" + Formatacao.ConvercaoDataSql(dataInicialjDateChooser.getDate()) +
                    "' and venda.dataVenda<='" + Formatacao.ConvercaoDataSql(dataFinaljDateChooser.getDate())+
                "' and saida.produto_idproduto=" + produto.getIdProduto() + 
                " and fornecedor.idfornecedor=" + fornecedor.getIdfornecedor() +
                " and venda.empresa_idempresa=" + config.getEmpresa().getIdempresa();
        sql = sql + " order by venda.dataVenda, produto.descricao";
        return sql;
    }
    
    public void gerarRelatorio(String sql){
        String url = ("telas/Vendedor/Relatorios/reportComissao.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("dataInicial", dataInicialjDateChooser.getDate());
            parameters.put("dataFinal", dataFinaljDateChooser.getDate());
            parameters.put("sql", sql);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);
    }

    public void setData(Object objeto) {
        produto = (Produto) objeto;
        produtojTextField.setText(produto.getDescricao());
    }

    public void setBanco(Banco banco) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setModelProduto(Produto produto, Estoque estoque) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setNFe(List<NfProdutos> listaProdutos, List<NfDuplicatas> listaDuplicatas, NotaEletronica nota, Fornecedor fornecedor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setAlterarValorVenda(Estoque estoque) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setFornecedor(Object objeto) {
        this.fornecedor = (Fornecedor) objeto;
        fornecedorjTextField.setText(fornecedor.getNomeFantasia());
    }

    public void setForPedido(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setPlanoContas(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setCliente(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setProdutoXML(Produto produto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setArquivo(File arquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    


}
