package telas.planoContas;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastraPlanoContas.java
 *
 * Created on 23/09/2009, 12:43:23
 */


import Interfaces.ItelaModel;
import facade.GrupoContaFacade;
import facade.SubGrupoContaFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Grupoconta;
import model.Subgrupo;

/**
 *
 * @author Wolverine
 */
public class FrmCadastraSubGrupoContas extends javax.swing.JFrame{

    /** Creates new form FrmCadastraPlanoContas */
    public FrmCadastraSubGrupoContas(Subgrupo subGrupoContas) throws Exception{
        initComponents();
        preencherjComboBox();
        this.setLocationRelativeTo(null);
        setVisible(true);
        this.subGrupoContas = subGrupoContas;
        if (subGrupoContas != null) {
            populaTela();
        }
    }

    private void preencherjComboBox() throws Exception{
        GrupoContaFacade facade = new GrupoContaFacade();
        List<Grupoconta> listaGrupoConta = new ArrayList<Grupoconta>();
        listaGrupoConta = facade.consultarGrupoconta();
        for(int i=0;i<listaGrupoConta.size();i++){
            grupojComboBox.addItem(listaGrupoConta.get(i));
        }
    }

    private void populaTela() {
        descricaojTextField.setText(subGrupoContas.getDescricao());
    }
        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastraPlanojPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        descricaojTextField = new javax.swing.JTextField();
        descricaojLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        grupojComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        numeroSubGrupojTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        salvarTelajButton = new javax.swing.JButton();
        fecharTelajButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de plano de Contas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastraPlanojPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cadastraPlanojPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
            e.printStackTrace();
        }
        cadastraPlanojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(descricaojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 370, -1));

        descricaojLabel.setText("Descrição");
        jPanel1.add(descricaojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel1.setText("Grupo de Contas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        grupojComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupojComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(grupojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, -1));

        jLabel2.setText("Nº SubGrupo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(numeroSubGrupojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        cadastraPlanojPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarTelajButton.setIcon(new javax.swing.ImageIcon("C:\\Programas\\GDynamic Java\\jGDynamic\\jGDynamic\\src\\imagens\\tick.png")); // NOI18N
        salvarTelajButton.setText("Salvar");
        salvarTelajButton.setToolTipText("Salvar Lançamento");
        salvarTelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarTelajButtonActionPerformed(evt);
            }
        });
        jPanel3.add(salvarTelajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        fecharTelajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        fecharTelajButton.setText("Fechar");
        fecharTelajButton.setToolTipText("Fechar");
        fecharTelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharTelajButtonActionPerformed(evt);
            }
        });
        jPanel3.add(fecharTelajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 8, -1, -1));

        cadastraPlanojPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 370, 40));

        getContentPane().add(cadastraPlanojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fecharTelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharTelajButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharTelajButtonActionPerformed
    private void salvarTelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarTelajButtonActionPerformed
        this.subGrupoContas.setDescricao(descricaojTextField.getText());
        Grupoconta grupoconta = new Grupoconta();
        grupoconta = (Grupoconta) grupojComboBox.getSelectedItem();
        this.subGrupoContas.setGrupoconta(grupoconta.getIdgrupoConta());
        this.subGrupoContas.setSequenciaConta(0);
        int numeroSubGrupo = grupoconta.getNumeroSubGrupo() + 1;
        this.subGrupoContas.setNumeroConta(numeroSubGrupojTextField.getText());
        try {
            GrupoContaFacade grupoContaFacade = new GrupoContaFacade();
            grupoconta.setNumeroSubGrupo(numeroSubGrupo);
            grupoContaFacade.salvarGrupoconta(grupoconta);
            SubGrupoContaFacade facade = new SubGrupoContaFacade();
            facade.salvarSubGrupoconta(subGrupoContas);
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Dados não foram salvos" + ex.getMessage());
        }
    }//GEN-LAST:event_salvarTelajButtonActionPerformed

    private void grupojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupojComboBoxItemStateChanged
        Grupoconta grupoConta = (Grupoconta) grupojComboBox.getSelectedItem();
        numeroSubGrupojTextField.setText(grupoConta.getNumeroConta() + "." + String.valueOf(grupoConta.getNumeroSubGrupo()+1));
        numeroSubGrupojTextField.requestFocus();
    }//GEN-LAST:event_grupojComboBoxItemStateChanged
    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastraPlanojPanel;
    private javax.swing.JLabel descricaojLabel;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JButton fecharTelajButton;
    private javax.swing.JComboBox grupojComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numeroSubGrupojTextField;
    private javax.swing.JButton salvarTelajButton;
    // End of variables declaration//GEN-END:variables
    private Subgrupo subGrupoContas;
}
