package telas.planoContas;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastraPlanoContas.java
 *
 * Created on 23/09/2009, 12:43:23
 */


import Interfaces.ItelaModel;
import facade.PlanoContaFacade;
import facade.SubGrupoContaFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Planoconta;
import model.Subgrupo;

/**
 *
 * @author Wolverine
 */
public class FrmCadastraPlanoContas extends javax.swing.JFrame{

      private ItelaModel telaModel;
    /** Creates new form FrmCadastraPlanoContas */
    public FrmCadastraPlanoContas(Planoconta planoContas, ItelaModel telaModel) throws Exception{
        this.telaModel = telaModel;
        initComponents();
        preencherjComboBox();
        this.setLocationRelativeTo(null);
        this.planoContas = planoContas;
        if (planoContas != null) {
            populaTela();
        }
        setVisible(true);
    }

    public void preencherjComboBox() throws Exception{
        SubGrupoContaFacade facade = new SubGrupoContaFacade();
        List<Subgrupo> listaSubGrupoConta = new ArrayList<Subgrupo>();
        listaSubGrupoConta = facade.consultarSubGrupoconta();
        for(int i=0;i<listaSubGrupoConta.size();i++){
            subGrupojComboBox.addItem(listaSubGrupoConta.get(i));
        }
    }

    private void populaTela() {
        descricaojTextField.setText(planoContas.getDescricao());
    }
        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastraPlanojPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        descricaojTextField = new javax.swing.JTextField();
        descricaojLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subGrupojComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        numeroContajTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        salvarTelajButton = new javax.swing.JButton();
        fecharTelajButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de plano de Contas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastraPlanojPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cadastraPlanojPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
            e.printStackTrace();
        }
        cadastraPlanojPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(descricaojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 370, -1));

        descricaojLabel.setText("Descrição");
        jPanel1.add(descricaojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel1.setText("SubGrupo Contas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        subGrupojComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subGrupojComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(subGrupojComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, -1));

        jLabel2.setText("Nº Conta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(numeroContajTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        cadastraPlanojPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salvarTelajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        salvarTelajButton.setText("Salvar");
        salvarTelajButton.setToolTipText("Salvar Conta");
        salvarTelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarTelajButtonActionPerformed(evt);
            }
        });
        jPanel3.add(salvarTelajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 8, 90, -1));

        fecharTelajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        fecharTelajButton.setText("Fechar");
        fecharTelajButton.setToolTipText("Fechar");
        fecharTelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharTelajButtonActionPerformed(evt);
            }
        });
        jPanel3.add(fecharTelajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 8, -1, -1));

        cadastraPlanojPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 370, 40));

        getContentPane().add(cadastraPlanojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fecharTelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharTelajButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharTelajButtonActionPerformed
    private void salvarTelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarTelajButtonActionPerformed
        this.planoContas.setDescricao(descricaojTextField.getText());
        Subgrupo subgrupo = new Subgrupo();
        subgrupo = ((Subgrupo) subGrupojComboBox.getSelectedItem());
        this.planoContas.setSubgrupo(subgrupo.getIdsubGrupo());
        Subgrupo subGrupo = (Subgrupo) subGrupojComboBox.getSelectedItem();
        int numeroSequencia = subGrupo.getSequenciaConta() + 1;
        this.planoContas.setNumeroConta(numeroContajTextField.getText());
        try {
            SubGrupoContaFacade subGrupoContaFacade = new SubGrupoContaFacade();
            subGrupo.setSequenciaConta(numeroSequencia);
            subGrupoContaFacade.salvarSubGrupoconta(subGrupo);
            PlanoContaFacade facade = new PlanoContaFacade();
            facade.salvarPlanoconta(planoContas);
            telaModel.setModel(facade.consultarPlanoconta());
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Dados não foram salvos" + ex.getMessage());
        }
    }//GEN-LAST:event_salvarTelajButtonActionPerformed

    private void subGrupojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subGrupojComboBoxItemStateChanged
        Subgrupo subGrupo = (Subgrupo) subGrupojComboBox.getSelectedItem();
        numeroContajTextField.setText(subGrupo.getNumeroConta() + "." + String.valueOf(subGrupo.getSequenciaConta()+1));
        numeroContajTextField.requestFocus();
    }//GEN-LAST:event_subGrupojComboBoxItemStateChanged
    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastraPlanojPanel;
    private javax.swing.JLabel descricaojLabel;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JButton fecharTelajButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numeroContajTextField;
    private javax.swing.JButton salvarTelajButton;
    private javax.swing.JComboBox subGrupojComboBox;
    // End of variables declaration//GEN-END:variables
    private Planoconta planoContas;
}
