/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Devolucao.Defeito;

import Regras.DevolucaoController;
import Regras.Formatacao;
import controler.Config;
import controler.UsuarioLogado;
import controler.relatoriosJasper;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Enviodevolucaodefeito;
import model.Enviodevolucaodefeitoproduto;
import model.Fornecedor;
import telas.Fornecedor.FrmConsultaFornecedor;
import view.Viewdevolucaodefeitoenviadas;
import view.Viewdevolucaodefeitoproduto;

/**
 *
 * @author Wolverine
 */
public class FrmConsultaDevolucaoDefeito extends javax.swing.JFrame implements IDevolucaoDefeito {

    private DevolucaoDefeitoTableModel modelDevolucao;
    private EnvioDevolucaoDefeitoTableModel modelEnvio;
    private List<Viewdevolucaodefeitoproduto> listaDevolucao;
    private List<Viewdevolucaodefeitoproduto> listaDevolucaoEnvidasProduto;
    private Fornecedor fornecedor;
    private Config config;
    private List<EnvioDevolucaoDefeitoBean> listaEnvio;
    private UsuarioLogado usuarioLogado;
    private EnviadasDevolucaoDefeitoTableModel modelDevolucaoDefeitoEnvidasProdutos;
    private EnvioDevolucaoDefeitoEnviadasTableModel modelDevolucaoEnvidas;
    private List<Viewdevolucaodefeitoenviadas> listaDevolucaoEnviadas;
    
    /**
     * Creates new form FrmConsultaDevolucaoDefeito
     */
    public FrmConsultaDevolucaoDefeito(Config config, UsuarioLogado usuarioLogado) {
        this.config = config;
        this.usuarioLogado = usuarioLogado;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarModelDevolucao();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        devolucaojTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fornecedorjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        totalDevolucaojLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FornecedorEnviojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vendedorjTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        totalEnviojLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        enviojTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        enviadasFornecedorjTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        envidasProdutosjTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução com Defeito");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        devolucaojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Devolução", "Cod Produto", "Descrição", "Data Devolução", "Valor R$", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(devolucaojTable);
        if (devolucaojTable.getColumnModel().getColumnCount() > 0) {
            devolucaojTable.getColumnModel().getColumn(0).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            devolucaojTable.getColumnModel().getColumn(1).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            devolucaojTable.getColumnModel().getColumn(2).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            devolucaojTable.getColumnModel().getColumn(3).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(3).setPreferredWidth(30);
            devolucaojTable.getColumnModel().getColumn(3).setHeaderValue("Data Devolução");
            devolucaojTable.getColumnModel().getColumn(4).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            devolucaojTable.getColumnModel().getColumn(5).setResizable(false);
            devolucaojTable.getColumnModel().getColumn(5).setPreferredWidth(50);
            devolucaojTable.getColumnModel().getColumn(5).setHeaderValue("Vendedor");
        }

        jLabel1.setText("Fornecedor");

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton2.setText("Incliuir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chart_organisation.png"))); // NOI18N
        jButton4.setText("Todos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        totalDevolucaojLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalDevolucaojLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDevolucaojLabel.setText("0,00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Total R$ :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(totalDevolucaojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDevolucaojLabel)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addGap(149, 149, 149)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanel3);

        jLabel2.setText("Forneceodor");

        jLabel3.setText("Vendedor");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        totalEnviojLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalEnviojLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalEnviojLabel.setText("0,00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Valor Total R$ :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(totalEnviojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalEnviojLabel)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        enviojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Devolução", "Cod Produto", "Descrição", "Valor R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(enviojTable);
        if (enviojTable.getColumnModel().getColumnCount() > 0) {
            enviojTable.getColumnModel().getColumn(0).setResizable(false);
            enviojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            enviojTable.getColumnModel().getColumn(1).setResizable(false);
            enviojTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            enviojTable.getColumnModel().getColumn(2).setResizable(false);
            enviojTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            enviojTable.getColumnModel().getColumn(3).setResizable(false);
            enviojTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton5.setText("Confirma");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        jButton6.setText("Cancela");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(103, 103, 103))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(FornecedorEnviojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FornecedorEnviojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devolução Geradas", jPanel4);

        enviadasFornecedorjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome Fantasia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enviadasFornecedorjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviadasFornecedorjTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(enviadasFornecedorjTable);
        if (enviadasFornecedorjTable.getColumnModel().getColumnCount() > 0) {
            enviadasFornecedorjTable.getColumnModel().getColumn(0).setResizable(false);
            enviadasFornecedorjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            enviadasFornecedorjTable.getColumnModel().getColumn(1).setResizable(false);
            enviadasFornecedorjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        envidasProdutosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod Devolução", "Cod Produto", "Descrição", "Valor R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(envidasProdutosjTable);
        if (envidasProdutosjTable.getColumnModel().getColumnCount() > 0) {
            envidasProdutosjTable.getColumnModel().getColumn(0).setResizable(false);
            envidasProdutosjTable.getColumnModel().getColumn(1).setResizable(false);
            envidasProdutosjTable.getColumnModel().getColumn(2).setResizable(false);
            envidasProdutosjTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/printer.png"))); // NOI18N
        jButton7.setText("Imprimir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note.png"))); // NOI18N
        jButton8.setText("Receber");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        jButton9.setText("Fechar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(68, 68, 68)
                .addComponent(jButton9)
                .addGap(55, 55, 55))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relação de Enviados", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linha = devolucaojTable.getSelectedRow();
        if (linha >= 0) {
            if (listaEnvio == null) {
                listaEnvio = new ArrayList<EnvioDevolucaoDefeitoBean>();
            }
            incluirProdutoparaEnvio(linha);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (listaDevolucao != null) {
            if (listaEnvio == null) {
                listaEnvio = new ArrayList<EnvioDevolucaoDefeitoBean>();
            }
            for (int i = 0; i < listaDevolucao.size(); i++) {
                incluirProdutoparaEnvio(i);
            }
            JOptionPane.showMessageDialog(rootPane, "Prdutos incluido na lista de envio");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        listaEnvio = new ArrayList<EnvioDevolucaoDefeitoBean>();
        carregarModelEnvio();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (listaEnvio != null) {
            salvarDevolucaoDefeitoEnvio();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex()==2){
            carregarModelDevolucaoEnviadas();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void enviadasFornecedorjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviadasFornecedorjTableMouseClicked
        int linha = enviadasFornecedorjTable.getSelectedRow();
        if (linha>=0){
            carregarModelDevolucaoDefeitoEnviadasProdutos(listaDevolucaoEnviadas.get(linha).getIdenvioDevolucaoDefeito(), listaDevolucaoEnviadas.get(linha).getIdfornecedor());
        }
    }//GEN-LAST:event_enviadasFornecedorjTableMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int linha = enviadasFornecedorjTable.getSelectedRow();
        if (linha>=0){
            gerarRelatorioDevolucaoDefeito(listaDevolucaoEnviadas.get(linha).getIdenvioDevolucaoDefeito());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int linha = enviadasFornecedorjTable.getSelectedRow();
        if (linha>=0){
            int idDEvolucaoEnviada = listaDevolucaoEnviadas.get(linha).getIdenvioDevolucaoDefeito();
            DevolucaoController devolucaoController = new DevolucaoController();
            Enviodevolucaodefeito enviodevolucaodefeito= devolucaoController.consultarEnvioDevolucaoDefeito(idDEvolucaoEnviada);
            if (enviodevolucaodefeito!=null){
                enviodevolucaodefeito.setRecebida("Sim");
                devolucaoController.salvarEnvioDevolucao(enviodevolucaodefeito);
                JOptionPane.showMessageDialog(rootPane, "Devolução Recebida com Sucesso");
                carregarModelDevolucaoEnviadas();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FornecedorEnviojTextField;
    private javax.swing.JTable devolucaojTable;
    private javax.swing.JTable enviadasFornecedorjTable;
    private javax.swing.JTable envidasProdutosjTable;
    private javax.swing.JTable enviojTable;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel totalDevolucaojLabel;
    private javax.swing.JLabel totalEnviojLabel;
    private javax.swing.JTextField vendedorjTextField;
    // End of variables declaration//GEN-END:variables

    public void consultarFornecedor(Fornecedor fornecedor) {
        if (fornecedor != null) {
            this.fornecedor = fornecedor;
            fornecedorjTextField.setText(fornecedor.getNomeFantasia());
            FornecedorEnviojTextField.setText(fornecedor.getNomeFantasia());
            carregarModelDevolucao();
        }
    }

    public void carregarModelDevolucao() {
        if (this.fornecedor != null) {
            DevolucaoController devolucaoController = new DevolucaoController();
            String sql = "Select d FROM Viewdevolucaodefeitoproduto d where d.empresaIdempresa=" + config.getEmpresa().getIdempresa()
                    + " and d.fornecedorIdfornecedor=" + fornecedor.getIdfornecedor() + " and d.numeroEnvio=0";

            listaDevolucao = devolucaoController.listarDevolucaoDefeitoProduto(sql);
            if (listaDevolucao == null) {
                listaDevolucao = new ArrayList<Viewdevolucaodefeitoproduto>();
            }
        } else {
            listaDevolucao = new ArrayList<Viewdevolucaodefeitoproduto>();
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelDevolucao = new DevolucaoDefeitoTableModel(listaDevolucao);
        devolucaojTable.setModel(modelDevolucao);
        devolucaojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        devolucaojTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        devolucaojTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        devolucaojTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        devolucaojTable.getColumnModel().getColumn(4).setCellRenderer(renderer);
        devolucaojTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        devolucaojTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        devolucaojTable.repaint();
        calcularValorTotalDevolucao();
    }

    public void carregarModelEnvio() {
        if (listaEnvio == null) {
            listaEnvio = new ArrayList<EnvioDevolucaoDefeitoBean>();
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelEnvio = new EnvioDevolucaoDefeitoTableModel(listaEnvio);
        enviojTable.setModel(modelEnvio);
        enviojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        enviojTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        enviojTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        enviojTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        enviojTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        enviojTable.repaint();
        calcularValorTotalEnvio();
    }

    public void calcularValorTotalDevolucao() {
        if (listaDevolucao == null) {
            totalDevolucaojLabel.setText("0,00");
        } else {
            float valor = 0;
            for (int i = 0; i < listaDevolucao.size(); i++) {
                valor = valor + listaDevolucao.get(i).getValorProduto();
            }
            totalDevolucaojLabel.setText(Formatacao.foramtarFloatString(valor));
        }
    }

    public void calcularValorTotalEnvio() {
        if (listaEnvio == null) {
            totalEnviojLabel.setText("0,00");
        } else {
            float valor = 0;
            for (int i = 0; i < listaEnvio.size(); i++) {
                valor = valor + listaEnvio.get(i).getValor();
            }
            totalEnviojLabel.setText(Formatacao.foramtarFloatString(valor));
        }
    }

    public void incluirProdutoparaEnvio(int linha) {
        EnvioDevolucaoDefeitoBean envio = new EnvioDevolucaoDefeitoBean();
        envio.setDescricao(listaDevolucao.get(linha).getDescricao());
        envio.setFornecedor(fornecedor);
        envio.setIdDevolucaoDefeito(listaDevolucao.get(linha).getIddevolucaodefeito());
        envio.setIdProduto(listaDevolucao.get(linha).getProdutoIdproduto());
        envio.setReferencia(listaDevolucao.get(linha).getReferencia());
        envio.setValor(listaDevolucao.get(linha).getValorProduto());
        listaEnvio.add(envio);
        carregarModelEnvio();
    }

    public void excluirProdutoEnvio(int linha) {
        if (listaEnvio != null) {
            int idDevolucao = listaDevolucao.get(linha).getIddevolucaodefeito();
            for (int i = 0; i < listaEnvio.size(); i++) {
                int idEnvio = listaEnvio.get(i).getIdDevolucaoDefeito();
                if (idDevolucao == idEnvio) {
                    listaEnvio.remove(i);
                    JOptionPane.showMessageDialog(rootPane, "Produto Removido do Envio");
                }
            }
        }
    }

    public void salvarDevolucaoDefeitoEnvio() {
        DevolucaoController devolucaoController = new DevolucaoController();
        Enviodevolucaodefeito envio = new Enviodevolucaodefeito();
        if (listaDevolucao.size() > 0) {
            envio.setData(new Date());
            envio.setFornecedor(fornecedor.getIdfornecedor());
            envio.setUsuarios(usuarioLogado.getUsuario().getIdusuarios());
            envio.setVededor(vendedorjTextField.getText());
            envio.setEmpresa(this.config.getEmpresa().getIdempresa());
            envio.setRecebida("Não");
            envio = devolucaoController.salvarEnvioDevolucao(envio);
        }
        for (int i = 0; i < listaEnvio.size(); i++) {
            Enviodevolucaodefeitoproduto envioProduto = new Enviodevolucaodefeitoproduto();
            envioProduto.setDevolucaoDefeito(listaDevolucao.get(i).getIddevolucaodefeito());
            envioProduto.setEnvioDevolucaoDefeito(envio.getIdenvioDevolucaoDefeito());
            envioProduto.setEmpresa(this.config.getEmpresa().getIdempresa());
            devolucaoController.salvarDevolucaoDefeitoProduto(envioProduto);
            if (envio != null) {
                devolucaoController.salvarDevolucaoDefetio(listaDevolucao.get(i).getIddevolucaodefeito(), envio.getIdenvioDevolucaoDefeito());
            }
        }
        listaEnvio = new ArrayList<EnvioDevolucaoDefeitoBean>();
        carregarModelDevolucao();
        carregarModelEnvio();
    }

    public void carregarModelDevolucaoEnviadas() {
        DevolucaoController devolucaoController = new DevolucaoController();
        listaDevolucaoEnviadas = devolucaoController.listarDevolucaoDefeitoEnviadas();
        if (listaDevolucaoEnviadas== null) {
            listaDevolucaoEnviadas = new ArrayList<Viewdevolucaodefeitoenviadas>();
        }
        modelDevolucaoEnvidas = new EnvioDevolucaoDefeitoEnviadasTableModel(listaDevolucaoEnviadas);
        enviadasFornecedorjTable.setModel(modelDevolucaoEnvidas);
        enviadasFornecedorjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        enviadasFornecedorjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        enviadasFornecedorjTable.repaint();
    }

    public void carregarModelDevolucaoDefeitoEnviadasProdutos(int idEnvio, int idFornecedor) {
        DevolucaoController devolucaoController = new DevolucaoController();
        String sql = "Select d FROM Viewdevolucaodefeitoproduto d where d.empresaIdempresa=" + config.getEmpresa().getIdempresa()
                + " and d.fornecedorIdfornecedor=" + idFornecedor + " and d.numeroEnvio=" + idEnvio;

        listaDevolucaoEnvidasProduto = devolucaoController.listarDevolucaoDefeitoProduto(sql);
        if (listaDevolucaoEnvidasProduto == null) {
            listaDevolucaoEnvidasProduto = new ArrayList<Viewdevolucaodefeitoproduto>();
        }
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        modelDevolucaoDefeitoEnvidasProdutos = new EnviadasDevolucaoDefeitoTableModel(listaDevolucaoEnvidasProduto);
        envidasProdutosjTable.setModel(modelDevolucaoDefeitoEnvidasProdutos);
        envidasProdutosjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        envidasProdutosjTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        envidasProdutosjTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        envidasProdutosjTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        envidasProdutosjTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        envidasProdutosjTable.repaint();
    }
    
    public void gerarRelatorioDevolucaoDefeito(int numeroenvio){
        String url = ("telas/Devolucao/Defeito/reportDevolucaoDefeitoEnvio.jasper");
        Map parameters = new HashMap();
        try {
            parameters.put("nomeFantasia", this.config.getEmpresa().getNomeFantasia());
            parameters.put("RazaoSocial", this.config.getEmpresa().getRazaoSocial());
            parameters.put("numeroEnvio", numeroenvio);
            parameters.put("idempresa", this.config.getEmpresa().getIdempresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível gerar o relatório " + ex);
            ex.printStackTrace();
        }
        new relatoriosJasper(url, parameters);

    }
    
   
}
