/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.ContasPagar;

import Regras.ContasPagarController;
import Regras.Formatacao;
import com.toedter.calendar.JTextFieldDateEditor;
import controler.ConfiguracaoSistema;
import controler.Sigap;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import model.Fornecedor;
import model.Planoconta;
import telas.Fornecedor.FrmConsultaFornecedor;
import telas.PlanoContas.FrmConsultaPlanoContas;


/**
 *
 * @author Wolverine
 */
public class FrmcpData extends javax.swing.JFrame  implements IrContasPagar{

    /**
     * Creates new form FrmcpData
     */
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private IContasPagar telaContas;
    private int tipo;
    
    private Fornecedor fornecedor;
    private Planoconta planoContas;
    
    public FrmcpData(IContasPagar telaContas, int tipo) {
        this.telaContas = telaContas;
        this.tipo = tipo;
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        initComponents();
        ativarCampos();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dataIniciojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    dataFinaljDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel2 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
jButton1 = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();
codigoFornecedorjTextField = new javax.swing.JTextField();
consultaFornecedorjButton = new javax.swing.JButton();
razaoSocialjTextField = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
codigoContajTextField = new javax.swing.JTextField();
consultaPlanoContasjButton = new javax.swing.JButton();
descricaojTextField = new javax.swing.JTextField();
jLabel4 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Período");

jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Data Inicial");

jLabel2.setText("Data Final");

jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
jButton1.setText("Confirmar");
jButton1.setToolTipText("Confirmar Relatório");
jButton1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
    }
    });
    jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton3.setText("Fechar");
    jButton3.setToolTipText("Fechar Janela");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 90, -1));

    consultaFornecedorjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    consultaFornecedorjButton.setToolTipText("Consultar Fornecedor");
    consultaFornecedorjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            consultaFornecedorjButtonActionPerformed(evt);
        }
    });

    razaoSocialjTextField.setEditable(false);

    jLabel3.setText("Fornecedor");

    consultaPlanoContasjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    consultaPlanoContasjButton.setToolTipText("Consultar Plano de Contas");
    consultaPlanoContasjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            consultaPlanoContasjButtonActionPerformed(evt);
        }
    });

    descricaojTextField.setEditable(false);

    jLabel4.setText("Palno de Contas");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codigoFornecedorjTextField)
                                .addComponent(codigoContajTextField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(consultaFornecedorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(consultaPlanoContasjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descricaojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(razaoSocialjTextField))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                    .addComponent(dataIniciojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(74, 74, 74))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataIniciojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoFornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(razaoSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(codigoContajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(consultaFornecedorjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(consultaPlanoContasjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 9, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tipo==3){
            telaContas.setRelContasPagarPeriodo(dataIniciojDateChooser.getDate(), dataFinaljDateChooser.getDate());
        }else if (tipo==2){
            telaContas.setRelContasPagarFornecedor(this.fornecedor.getIdfornecedor(), this.fornecedor.getRazaoSocial());
        }else if (tipo==5){
            telaContas.setRelContasVencidasFornecedor(dataIniciojDateChooser.getDate(), dataFinaljDateChooser.getDate(), 
                    this.fornecedor.getIdfornecedor(), this.fornecedor.getRazaoSocial());
        }else if (tipo==6){
            telaContas.setRelContasPagasPeriodo(dataIniciojDateChooser.getDate(), dataFinaljDateChooser.getDate());
        }else if (tipo==7){
            telaContas.setRelContasPagasFornecedor(this.fornecedor.getIdfornecedor(), this.fornecedor.getRazaoSocial(), 
                    dataIniciojDateChooser.getDate(), dataFinaljDateChooser.getDate());
        }else if (tipo==8){
            telaContas.setRelContasPagasPlanoContas(this.planoContas.getIdplanoconta(), this.planoContas.getDescricao(), 
                    dataIniciojDateChooser.getDate(), dataFinaljDateChooser.getDate());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultaFornecedorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFornecedorjButtonActionPerformed
        new FrmConsultaFornecedor(this);
    }//GEN-LAST:event_consultaFornecedorjButtonActionPerformed

    private void consultaPlanoContasjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPlanoContasjButtonActionPerformed
        new FrmConsultaPlanoContas(this);
    }//GEN-LAST:event_consultaPlanoContasjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoContajTextField;
    private javax.swing.JTextField codigoFornecedorjTextField;
    private javax.swing.JButton consultaFornecedorjButton;
    private javax.swing.JButton consultaPlanoContasjButton;
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataIniciojDateChooser;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField razaoSocialjTextField;
    // End of variables declaration//GEN-END:variables

    public void consultarFornecedor(Fornecedor fornecedor){
        this.fornecedor = fornecedor;
        codigoFornecedorjTextField.setText(String.valueOf(this.fornecedor.getIdfornecedor()));
        razaoSocialjTextField.setText(this.fornecedor.getRazaoSocial());
    }
    
    public void cosultarPlanoContas(Planoconta planoContas){
        this.planoContas = planoContas;
        codigoContajTextField.setText(this.planoContas.getNumeroConta());
        descricaojTextField.setText(planoContas.getDescricao());
    }
    
    public void ativarCampos(){
        if (tipo==2){
            dataFinaljDateChooser.setEnabled(false);
            dataIniciojDateChooser.setEnabled(false);
            codigoContajTextField.setEnabled(false);
            consultaPlanoContasjButton.setEnabled(false);
        }else if (tipo==3){
            codigoContajTextField.setEditable(false);
            consultaPlanoContasjButton.setEnabled(false);
            codigoFornecedorjTextField.setEditable(false);
            razaoSocialjTextField.setEditable(false);
        }else if (tipo==5){
            dataFinaljDateChooser.setEnabled(false);
            dataIniciojDateChooser.setEnabled(false);
            codigoContajTextField.setEditable(false);
            consultaPlanoContasjButton.setEnabled(false);
        }else if (tipo==6){
            codigoFornecedorjTextField.setEditable(false);
            razaoSocialjTextField.setEditable(false);
            codigoContajTextField.setEditable(false);
            consultaPlanoContasjButton.setEnabled(false);
        }else if (tipo==7){
            codigoContajTextField.setEditable(false);
            consultaPlanoContasjButton.setEnabled(false);
        }else if (tipo==8){
            dataFinaljDateChooser.setEnabled(false);
            dataIniciojDateChooser.setEnabled(false);
            codigoFornecedorjTextField.setEditable(false);
            razaoSocialjTextField.setEditable(false);
        }
    }

    public void exportarExcel(String caminho, String nomeArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
