/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frmloguin.java
 *
 * Created on 26/10/2009, 23:52:37
 */

package telas.usuario;

import Regras.Formatacao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import telas.ContasPagar.IContasPagar;

/**
 *
 * @author Wolverine
 */
public class FrmAutorizar extends javax.swing.JFrame {
    
    private IContasPagar telasPagar;

    
    /** Creates new form Frmloguin */
    public FrmAutorizar(IContasPagar telaPagar) {
        initComponents();
        this.telasPagar = telaPagar;
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

   

    public boolean senhaScape(char[] s){
        String senha="";
        for (int i=0;i<s.length;i++){
            senha+= s[i];
        }
        String data = Formatacao.getDataDoDia();
        int dia = Integer.parseInt(data.substring(8));
        int mes = Integer.parseInt(data.substring(5, 7));
        int ano = Integer.parseInt(data.substring(0,4));
        String senhaPadrao = "00" + String.valueOf(dia+mes) + String.valueOf(ano);
        if (senha.equalsIgnoreCase(senhaPadrao)){
            return true;
        }
        return false;

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginjPanel = new javax.swing.JPanel();
        senhajPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                botaoFechar(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senhajPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhajPasswordFieldActionPerformed(evt);
            }
        });
        loginjPanel.add(senhajPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel1.setText("Senha de Acesso");
        loginjPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        loginjButton.setText("Login");
        loginjButton.setToolTipText("Login de Usuário");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, -1));

        sairjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door.png"))); // NOI18N
        sairjButton.setText("Sair");
        sairjButton.setToolTipText("Sair do Sistema");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonfecharMovimentoCaixa(evt);
            }
        });
        jPanel3.add(sairjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 6, 80, -1));

        loginjPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 40));

        jLabel2.setText("Nome do Usuário");
        loginjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        loginjPanel.add(nomejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        getContentPane().add(loginjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
       
}//GEN-LAST:event_loginjButtonActionPerformed

    private void sairjButtonfecharMovimentoCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonfecharMovimentoCaixa
       System.exit(0);
}//GEN-LAST:event_sairjButtonfecharMovimentoCaixa

    private void botaoFechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_botaoFechar

    }//GEN-LAST:event_botaoFechar

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      
    }//GEN-LAST:event_formWindowClosing

    private void senhajPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhajPasswordFieldActionPerformed
        
    }//GEN-LAST:event_senhajPasswordFieldActionPerformed


    

    
    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginjButton;
    private javax.swing.JPanel loginjPanel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JPasswordField senhajPasswordField;
    // End of variables declaration//GEN-END:variables


}
